/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sfc.sf2.battle.mapterrain.gui;

import com.sfc.sf2.battle.mapterrain.BattleMapTerrainManager;
import com.sfc.sf2.battle.mapterrain.LandEffectMovementType;
import com.sfc.sf2.battle.mapterrain.actions.BattleMapTerrainActionData;
import com.sfc.sf2.battle.mapterrain.gui.TerrainKeyPanel.TerrainDrawMode;
import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.NonCombinableAction;
import com.sfc.sf2.core.actions.SpinnerAction;
import com.sfc.sf2.core.gui.AbstractMainEditor;
import com.sfc.sf2.core.gui.controls.Console;
import com.sfc.sf2.core.settings.SettingsManager;
import com.sfc.sf2.core.settings.ViewSettings;
import com.sfc.sf2.helpers.PathHelpers;
import com.sfc.sf2.settings.TerrainSettings;
import java.awt.event.ActionEvent;
import java.nio.file.Path;
import java.util.logging.Level;

/**
 *
 * @author wiz
 */
public class BattleMapTerrainMainEditor extends AbstractMainEditor {

    private final ViewSettings viewSettings = new ViewSettings();
    private final TerrainSettings terrainSettings = new TerrainSettings();
    private final BattleMapTerrainManager battlemapterrainManager = new BattleMapTerrainManager();
    
    private int actionBattleIndex = 1;
    private String actionSharedTerrainInfo;
        
    public BattleMapTerrainMainEditor() {
        super();
        SettingsManager.registerSettingsStore("view", viewSettings);
        SettingsManager.registerSettingsStore("terrain", terrainSettings);
        initComponents();
        initCore(console1);
    }
    
    @Override
    protected void initEditor() {
        super.initEditor();
        
        battleMapTerrainViewPanel1.setLayoutPanel(battleMapTerrainLayoutPanel, viewSettings);
        accordionPanel1.setExpanded(false);
        terrainKeyPanel1.setActionListener(this::onTerrainSelectionChanged);
        terrainKeyPanel1.setModeChangedListener(this::onTerrainModeChanged);
        TerrainDrawMode terrainDrawMode = terrainSettings.getTerrainDrawMode();
        battleMapTerrainLayoutPanel.setTerrainDrawMode(terrainDrawMode);
        terrainKeyPanel1.setDrawMode(terrainDrawMode);
    }
    
    @Override
    protected void onDataLoaded() {
        super.onDataLoaded();
        BattleMapTerrainActionData newValue = new BattleMapTerrainActionData((int)jSpinnerBattleIndex.getValue(), battlemapterrainManager.getMapLayout(), battlemapterrainManager.getCoords(), battlemapterrainManager.getTerrain(),
                battlemapterrainManager.getLandEffects(), battlemapterrainManager.getSharedTerrainInfo());
        BattleMapTerrainActionData oldValue = new BattleMapTerrainActionData(actionBattleIndex, battleMapTerrainLayoutPanel.getMapLayout(), battleMapTerrainLayoutPanel.getBattleCoords(), battleMapTerrainLayoutPanel.getTerrain(),
                landEffectTableModel.getTableData(LandEffectMovementType[].class), actionSharedTerrainInfo);
        ActionManager.setAndExecuteAction(new NonCombinableAction<BattleMapTerrainActionData>(this, "Battle Terrain Imported", this::actionBattleMapTerrainLoaded, newValue, oldValue));
    }
    
    private void actionBattleMapTerrainLoaded(BattleMapTerrainActionData value) {
        
        battleMapTerrainLayoutPanel.setMapLayout(value.layout());
        battleMapTerrainLayoutPanel.setBattleCoords(value.coords());
        battleMapTerrainLayoutPanel.setTerrain(value.terrain());
        
        landEffectTable.setLandEffectData(battlemapterrainManager.getLandEffectEnums());
        landEffectTableModel.setTableData(value.landEffects());
        
        actionSharedTerrainInfo = value.sharedTerraininfo();
        terrainKeyPanel1.setSharedTerrainInfo(actionSharedTerrainInfo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        landEffectTableModel = new com.sfc.sf2.battle.mapterrain.models.LandEffectTableModel();
        jPanel13 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel15 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel8 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonImport = new javax.swing.JButton();
        jSpinnerBattleIndex = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        accordionPanel1 = new com.sfc.sf2.core.gui.controls.AccordionPanel();
        fileButtonTerrainEntries = new com.sfc.sf2.core.gui.controls.FileButton();
        directoryButtonPaletteEntries = new com.sfc.sf2.core.gui.controls.DirectoryButton();
        directoryButtonTilesetEntries = new com.sfc.sf2.core.gui.controls.DirectoryButton();
        fileButtonMapEntries = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonLandEffectEntries = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonBattleMapCoords = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonLandEffects = new com.sfc.sf2.core.gui.controls.FileButton();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonExportTerrain = new javax.swing.JButton();
        fileButtonExportTerrain = new com.sfc.sf2.core.gui.controls.FileButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonExportLandEffect = new javax.swing.JButton();
        fileButtonExportLandeffect = new com.sfc.sf2.core.gui.controls.FileButton();
        jPanel11 = new javax.swing.JPanel();
        terrainKeyPanel1 = new com.sfc.sf2.battle.mapterrain.gui.TerrainKeyPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        battleMapTerrainLayoutPanel = new com.sfc.sf2.battle.mapterrain.gui.BattleMapTerrainLayoutPanel();
        battleMapTerrainViewPanel1 = new com.sfc.sf2.battle.mapterrain.gui.BattleMapTerrainViewPanel();
        jPanel4 = new javax.swing.JPanel();
        landEffectTable = new com.sfc.sf2.battle.mapterrain.gui.LandEffectTable();
        infoButton11 = new com.sfc.sf2.core.gui.controls.InfoButton();
        jLabel5 = new javax.swing.JLabel();
        console1 = new com.sfc.sf2.core.gui.controls.Console();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SF2BattleMapTerrainManager");

        jSplitPane1.setDividerLocation(700);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);

        jSplitPane2.setDividerLocation(550);
        jSplitPane2.setOneTouchExpandable(true);

        jSplitPane3.setDividerLocation(300);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Import from :"));
        jPanel3.setPreferredSize(new java.awt.Dimension(590, 135));

        jButtonImport.setText("Import");
        jButtonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportActionPerformed(evt);
            }
        });

        jSpinnerBattleIndex.setModel(new javax.swing.SpinnerNumberModel(1, 0, 255, 1));
        jSpinnerBattleIndex.setName("Battle Index Spinner"); // NOI18N
        jSpinnerBattleIndex.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerBattleIndexStateChanged(evt);
            }
        });

        jLabel3.setText("Battle index :");

        accordionPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Entries data"));

        fileButtonTerrainEntries.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonTerrainEntries.setFilePath(".\\terrainentries.asm");
        fileButtonTerrainEntries.setInfoMessage("");
        fileButtonTerrainEntries.setLabelText("Terrain entries :");
        fileButtonTerrainEntries.setName("Import Terrain Entries"); // NOI18N

        directoryButtonPaletteEntries.setDirectoryPath("..\\graphics\\maps\\mappalettes\\entries.asm");
        directoryButtonPaletteEntries.setInfoMessage("");
        directoryButtonPaletteEntries.setLabelText("Map palette entries :");
        directoryButtonPaletteEntries.setName("Import Palette Entries"); // NOI18N

        directoryButtonTilesetEntries.setDirectoryPath("..\\graphics\\maps\\maptilesets\\entries.asm");
        directoryButtonTilesetEntries.setInfoMessage("");
        directoryButtonTilesetEntries.setLabelText("Map tileset entries :");
        directoryButtonTilesetEntries.setName("Import Tileset Entries"); // NOI18N

        fileButtonMapEntries.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonMapEntries.setFilePath("..\\maps\\entries.asm");
        fileButtonMapEntries.setInfoMessage("");
        fileButtonMapEntries.setLabelText("Map entries :");
        fileButtonMapEntries.setName("Import Map Entries"); // NOI18N

        fileButtonLandEffectEntries.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonLandEffectEntries.setFilePath("..\\..\\sf2enums.asm");
        fileButtonLandEffectEntries.setInfoMessage("");
        fileButtonLandEffectEntries.setLabelText("Land effect enums :");
        fileButtonLandEffectEntries.setName("Import Land Effect Entries"); // NOI18N

        javax.swing.GroupLayout accordionPanel1Layout = new javax.swing.GroupLayout(accordionPanel1);
        accordionPanel1.setLayout(accordionPanel1Layout);
        accordionPanel1Layout.setHorizontalGroup(
            accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accordionPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directoryButtonPaletteEntries, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(directoryButtonTilesetEntries, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonMapEntries, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonTerrainEntries, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonLandEffectEntries, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        accordionPanel1Layout.setVerticalGroup(
            accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accordionPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(directoryButtonPaletteEntries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(directoryButtonTilesetEntries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonMapEntries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonTerrainEntries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonLandEffectEntries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fileButtonBattleMapCoords.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ANY_ASSEMBLY);
        fileButtonBattleMapCoords.setFilePath(".\\global\\battlemapcoords.asm");
        fileButtonBattleMapCoords.setInfoMessage("");
        fileButtonBattleMapCoords.setLabelText("Battlemap coords :");
        fileButtonBattleMapCoords.setName("Import Battle Coords"); // NOI18N

        fileButtonLandEffects.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ANY_ASSEMBLY);
        fileButtonLandEffects.setFilePath(".\\global\\landeffectsettingsandmovecosts.asm");
        fileButtonLandEffects.setInfoMessage("");
        fileButtonLandEffects.setLabelText("Land effects :");
        fileButtonLandEffects.setName("Import Land Effects"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerBattleIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonImport)
                .addGap(6, 6, 6))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accordionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fileButtonBattleMapCoords, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonLandEffects, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accordionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonBattleMapCoords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonLandEffects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonImport)
                    .addComponent(jSpinnerBattleIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Export to :"));
        jPanel5.setPreferredSize(new java.awt.Dimension(32, 135));

        jLabel1.setText("<html>Select target file.</html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonExportTerrain.setText("Export");
        jButtonExportTerrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportTerrainActionPerformed(evt);
            }
        });

        fileButtonExportTerrain.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonExportTerrain.setFilePath(".\\entries\\battle01\\terrain.bin");
        fileButtonExportTerrain.setInfoMessage("");
        fileButtonExportTerrain.setLabelText("Battlemap terrain :");
        fileButtonExportTerrain.setName("Export Terrain"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonExportTerrain, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExportTerrain)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileButtonExportTerrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExportTerrain)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Terrain", jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(271, 110));

        jLabel2.setText("<html>Select target file.</html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonExportLandEffect.setText("Export");
        jButtonExportLandEffect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportLandEffectActionPerformed(evt);
            }
        });

        fileButtonExportLandeffect.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonExportLandeffect.setFilePath(".\\global\\landeffectsettingsandmovecosts.asm");
        fileButtonExportLandeffect.setInfoMessage("");
        fileButtonExportLandeffect.setLabelText("Land effects :");
        fileButtonExportLandeffect.setName("Export Land Effects"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonExportLandeffect, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExportLandEffect)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileButtonExportLandeffect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExportLandEffect)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Land effect", jPanel7);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Terrain");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jSplitPane3.setLeftComponent(jPanel9);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(terrainKeyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(terrainKeyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );

        jSplitPane3.setRightComponent(jPanel11);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane3)
                .addContainerGap())
        );

        jSplitPane2.setLeftComponent(jPanel8);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Map"));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout battleMapTerrainLayoutPanelLayout = new javax.swing.GroupLayout(battleMapTerrainLayoutPanel);
        battleMapTerrainLayoutPanel.setLayout(battleMapTerrainLayoutPanelLayout);
        battleMapTerrainLayoutPanelLayout.setHorizontalGroup(
            battleMapTerrainLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        battleMapTerrainLayoutPanelLayout.setVerticalGroup(
            battleMapTerrainLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(battleMapTerrainLayoutPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(battleMapTerrainViewPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(battleMapTerrainViewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Map", jPanel10);

        landEffectTable.setBorder(javax.swing.BorderFactory.createTitledBorder("Land Effect"));
        landEffectTable.setHorizontalScrolling(true);
        landEffectTable.setModel(landEffectTableModel);
        landEffectTable.setRowBorders(true);

        infoButton11.setMessageText("<html>\"Land effect\" determines how each <i>movement type</i> is affected by each <i>terrain type</i>.<br>Each land effect entry determines defensive bonus and the movement cost that will affect the a unit with the specific movement type on the specific terrain.<br><br><b>Defenses:</b><br>Obstructed: Indicates that this <i>movement type</i> cannot move onto this tile.<br>LE0: By default, provides 0% defensive bonus (no bonus).<br>LE15: By default, provides 15% defensive bonus.<br>LE30: By default, provides 30% defensive bonus.<br><br><b>Movement costs:</b> Higher numbers = slower movement on that tile.</html>");
        infoButton11.setText("");

        jLabel5.setText("Land effect info");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(561, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(landEffectTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(infoButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landEffectTable, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Land Effect", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane2))
        );

        jSplitPane2.setRightComponent(jPanel2);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        jSplitPane1.setTopComponent(jPanel15);
        jSplitPane1.setBottomComponent(console1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1253, 735));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExportTerrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportTerrainActionPerformed
        Path terrainPath = PathHelpers.getBasePath().resolve(fileButtonExportTerrain.getFilePath());
        if (!PathHelpers.createPathIfRequred(terrainPath)) return;
        try {
            battlemapterrainManager.exportDisassembly(terrainPath, battleMapTerrainLayoutPanel.getTerrain());
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Terrrain disasm could not be exported to : " + terrainPath);
        }
    }//GEN-LAST:event_jButtonExportTerrainActionPerformed

    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportActionPerformed
        Path palettesPath = PathHelpers.getBasePath().resolve(directoryButtonPaletteEntries.getDirectoryPath());
        Path tilesetsPath = PathHelpers.getBasePath().resolve(directoryButtonTilesetEntries.getDirectoryPath());
        Path mapEntriesPath = PathHelpers.getBasePath().resolve(fileButtonMapEntries.getFilePath());
        Path terrainEntriesPath = PathHelpers.getBasePath().resolve(fileButtonTerrainEntries.getFilePath());
        Path coordsPath = PathHelpers.getBasePath().resolve(fileButtonBattleMapCoords.getFilePath());
        Path sf2EnumsPath = PathHelpers.getBasePath().resolve(fileButtonLandEffectEntries.getFilePath());
        Path landEffectPath = PathHelpers.getBasePath().resolve(fileButtonLandEffects.getFilePath());
        int battleIndex = (int)jSpinnerBattleIndex.getValue();
        try {
            battlemapterrainManager.importLandEffects(sf2EnumsPath, landEffectPath);
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Land effect data could not be imported from : " + coordsPath);
        }
        try {
            battlemapterrainManager.importDisassembly(palettesPath, tilesetsPath, mapEntriesPath, terrainEntriesPath, coordsPath, battleIndex);
        } catch (Exception ex) {
            battlemapterrainManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Terrrain disasm could not be imported from : " + coordsPath);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportActionPerformed

    private void jButtonExportLandEffectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportLandEffectActionPerformed
        Path landEffectPath = PathHelpers.getBasePath().resolve(fileButtonExportLandeffect.getFilePath());
        if (!PathHelpers.createPathIfRequred(landEffectPath)) return;
        try {
            battlemapterrainManager.exportLandEffects(landEffectPath, landEffectTableModel.getTableData(LandEffectMovementType[].class));
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Land effect disasm could not be exported to : " + landEffectPath);
        }
    }//GEN-LAST:event_jButtonExportLandEffectActionPerformed

    private void jSpinnerBattleIndexStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerBattleIndexStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new SpinnerAction(jSpinnerBattleIndex, jSpinnerBattleIndex.getValue(), actionBattleIndex));
        }
        actionBattleIndex = (int)jSpinnerBattleIndex.getValue();
    }//GEN-LAST:event_jSpinnerBattleIndexStateChanged
    
    private void onTerrainSelectionChanged(ActionEvent e) {
        int terrain = Integer.parseInt(e.getActionCommand());
        battleMapTerrainLayoutPanel.setSelectedTerrainType(terrain);
    }
    
    private void onTerrainModeChanged(ActionEvent e) {
        TerrainDrawMode drawMode = (TerrainDrawMode)e.getSource();
        battleMapTerrainLayoutPanel.setTerrainDrawMode(drawMode);
    }
    
    /**
     * To create a new Main Editor, copy the below code
     * Don't forget to change the new main class (below)
     */
    public static void main(String args[]) {
        AbstractMainEditor.programSetup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleMapTerrainMainEditor().setVisible(true);  // <------ Change this class to new Main Editor class
            }
        });
    }
    /**
     * To create a new Main Editor, copy the above code
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.AccordionPanel accordionPanel1;
    private com.sfc.sf2.battle.mapterrain.gui.BattleMapTerrainLayoutPanel battleMapTerrainLayoutPanel;
    private com.sfc.sf2.battle.mapterrain.gui.BattleMapTerrainViewPanel battleMapTerrainViewPanel1;
    private com.sfc.sf2.core.gui.controls.Console console1;
    private com.sfc.sf2.core.gui.controls.DirectoryButton directoryButtonPaletteEntries;
    private com.sfc.sf2.core.gui.controls.DirectoryButton directoryButtonTilesetEntries;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonBattleMapCoords;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportLandeffect;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportTerrain;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonLandEffectEntries;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonLandEffects;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonMapEntries;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonTerrainEntries;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton11;
    private javax.swing.JButton jButtonExportLandEffect;
    private javax.swing.JButton jButtonExportTerrain;
    private javax.swing.JButton jButtonImport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerBattleIndex;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.sfc.sf2.battle.mapterrain.gui.LandEffectTable landEffectTable;
    private com.sfc.sf2.battle.mapterrain.models.LandEffectTableModel landEffectTableModel;
    private com.sfc.sf2.battle.mapterrain.gui.TerrainKeyPanel terrainKeyPanel1;
    // End of variables declaration//GEN-END:variables
}
