/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.battle.mapterrain.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.ComboAction;
import com.sfc.sf2.core.actions.RadioButtonAction;
import com.sfc.sf2.core.settings.SettingsManager;
import com.sfc.sf2.settings.TerrainSettings;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JRadioButton;

/**
 *
 * @author TiMMy
 */
public class TerrainKeyPanel extends javax.swing.JPanel {

    public enum TerrainDrawMode {
        Icons,
        Colors,
        Numbers,
    }
    
    private ActionListener buttonSelected;
    private ActionListener modeChanged;
    
    private JRadioButton actionTerrainRadioButton;
    private TerrainDrawMode actionTerrainDrawMode;
    
    public TerrainKeyPanel() {
        initComponents();
        infoButtonSharedTerrain.setVisible(false);
    }
    
    public void setDrawMode(TerrainDrawMode drawMode) {
        jComboBoxTerrainView.setSelectedItem(drawMode);
        updateDrawModePanels(drawMode);
    }
    
    public void setActionListener(ActionListener buttonSelected) {
        this.buttonSelected = buttonSelected;
    }
    
    public void removeActionListener() {
        this.buttonSelected = null;
    }
    
    public void setModeChangedListener(ActionListener buttonSelected) {
        this.modeChanged = buttonSelected;
    }
    
    public void removeModeChangedListener() {
        this.modeChanged = null;
    }
    
    private void updateDrawModePanels(TerrainDrawMode terrainDrawMode) {
        TerrainIconPanel1.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel2.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel3.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel4.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel5.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel6.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel7.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel8.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel9.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel10.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel11.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel11.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel12.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel13.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel14.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel15.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel16.setTerrainDrawMode(terrainDrawMode);
        TerrainIconPanel17.setTerrainDrawMode(terrainDrawMode);
    }
    
    public void setSharedTerrainInfo(String sharedTerrainInfo) {
        infoButtonSharedTerrain.setVisible(sharedTerrainInfo != null);
        if (sharedTerrainInfo != null) {
            infoButtonSharedTerrain.setMessageText("This terrain data is used by the following battles:\n" + sharedTerrainInfo + "\nAny changes will affect all of these battles.\n\nTo unlink the battles, you can export this terrain for a specific battle and then update terrainentries.asm");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTerrain = new com.sfc.sf2.core.gui.controls.NameableButtonGroup();
        flatOptionPaneWarningIcon1 = new com.formdev.flatlaf.icons.FlatOptionPaneWarningIcon();
        jComboBoxTerrainView = new javax.swing.JComboBox<>();
        infoButton13 = new com.sfc.sf2.core.gui.controls.InfoButton();
        jLabel2 = new javax.swing.JLabel();
        infoButton12 = new com.sfc.sf2.core.gui.controls.InfoButton();
        infoButtonSharedTerrain = new com.sfc.sf2.core.gui.controls.InfoButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonWall = new javax.swing.JRadioButton();
        infoButton9 = new com.sfc.sf2.core.gui.controls.InfoButton();
        infoButton2 = new com.sfc.sf2.core.gui.controls.InfoButton();
        TerrainIconPanel10 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        TerrainIconPanel3 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonWater = new javax.swing.JRadioButton();
        jRadioButtonPlains = new javax.swing.JRadioButton();
        infoButton10 = new com.sfc.sf2.core.gui.controls.InfoButton();
        infoButton3 = new com.sfc.sf2.core.gui.controls.InfoButton();
        TerrainIconPanel4 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonPath = new javax.swing.JRadioButton();
        infoButton4 = new com.sfc.sf2.core.gui.controls.InfoButton();
        TerrainIconPanel5 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonGrass = new javax.swing.JRadioButton();
        infoButton5 = new com.sfc.sf2.core.gui.controls.InfoButton();
        TerrainIconPanel6 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonForest = new javax.swing.JRadioButton();
        infoButton6 = new com.sfc.sf2.core.gui.controls.InfoButton();
        TerrainIconPanel7 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonHills = new javax.swing.JRadioButton();
        infoButton7 = new com.sfc.sf2.core.gui.controls.InfoButton();
        TerrainIconPanel8 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        TerrainIconPanel1 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonDesert = new javax.swing.JRadioButton();
        jRadioButtonObstructed = new javax.swing.JRadioButton();
        infoButton8 = new com.sfc.sf2.core.gui.controls.InfoButton();
        infoButton1 = new com.sfc.sf2.core.gui.controls.InfoButton();
        TerrainIconPanel9 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        TerrainIconPanel2 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonMountain = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        TerrainIconPanel11 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonTerrain9 = new javax.swing.JRadioButton();
        TerrainIconPanel12 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonTerrain10 = new javax.swing.JRadioButton();
        TerrainIconPanel13 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonTerrain11 = new javax.swing.JRadioButton();
        TerrainIconPanel14 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonTerrain12 = new javax.swing.JRadioButton();
        TerrainIconPanel15 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonTerrain13 = new javax.swing.JRadioButton();
        TerrainIconPanel16 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonTerrain14 = new javax.swing.JRadioButton();
        TerrainIconPanel17 = new com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel();
        jRadioButtonTerrain15 = new javax.swing.JRadioButton();

        buttonGroupTerrain.setName("Terrain Type Group");

        setMaximumSize(new java.awt.Dimension(32767, 500));
        setMinimumSize(new java.awt.Dimension(240, 500));

        jComboBoxTerrainView.setModel(new javax.swing.DefaultComboBoxModel(TerrainDrawMode.values()));
        jComboBoxTerrainView.setName("Terrain View Combo"); // NOI18N
        jComboBoxTerrainView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTerrainViewActionPerformed(evt);
            }
        });

        infoButton13.setMessageText("<html>Terrain can be visualised as a representative icon, a flat color, or their internal number value.<br><br>For the additional terrains (which are not defined by default), icons are misc. placeholders.<br><br>If you want to use custom icons, follow these steps:<br>1. Create the folder : /data/battles/terrain_icons/<br>2. Create a replacement icon that is 8x8 pixels. Icons should be named \"00.png\" to correspond to the terrain value (00-15).<br>3. Restart the Terrain Editor or Battle Editor. Your custom icons should be loaded in.</html>");
        infoButton13.setText("");

        jLabel2.setText("Select a terrain type to paint ");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        infoButton12.setMessageText("<html>Select a terrain type then click and drag on the map to paint that terrain.<br><br>The base game only utilises 9 terrains (plus \"Obstructed\") but can support up to 15.<br>The icons and colors in this context are just generic placeholders.</html> ");
        infoButton12.setText("");

        infoButtonSharedTerrain.setIcon(flatOptionPaneWarningIcon1);
        infoButtonSharedTerrain.setText("");

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(250, 200));

        jPanel1.setPreferredSize(new java.awt.Dimension(250, 200));

        buttonGroupTerrain.add(jRadioButtonWall);
        jRadioButtonWall.setText("Sky / Wall");
        jRadioButtonWall.setActionCommand("0");
        jRadioButtonWall.setName("Sky Radio"); // NOI18N
        jRadioButtonWall.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        infoButton9.setMessageText("<html>For high sky or mountains.<br><i>Default:</i>Only <i>flying</i> units can move through this terrain.</html>");
        infoButton9.setText("");

        infoButton2.setMessageText("<html>Used for open sky, and walls.<br><i>Default:</i>Only <i>flying</i> and <i>hovering</i> units can move through this terrain.</html>");
        infoButton2.setText("");

        TerrainIconPanel10.setNumber(8);
        TerrainIconPanel10.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        TerrainIconPanel3.setNumber(1);
        TerrainIconPanel3.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonWater);
        jRadioButtonWater.setText("Water");
        jRadioButtonWater.setActionCommand("8");
        jRadioButtonWater.setName("Water Radio"); // NOI18N
        jRadioButtonWater.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        buttonGroupTerrain.add(jRadioButtonPlains);
        jRadioButtonPlains.setText("Plains");
        jRadioButtonPlains.setActionCommand("1");
        jRadioButtonPlains.setName("Plains Radio"); // NOI18N
        jRadioButtonPlains.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        infoButton10.setMessageText("<html>For water, rivers, and ocean.<br><i>Default:</i>The only terrain that <i>aquatic</i> units can move through.</html>");
        infoButton10.setText("");

        infoButton3.setMessageText("<html>The default terrain-type. For flat ground or flooring.<br><i>Default:</i>Offers some defense without impeding movement.</html>");
        infoButton3.setText("");

        TerrainIconPanel4.setNumber(2);
        TerrainIconPanel4.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonPath);
        jRadioButtonPath.setText("Path / Bridge");
        jRadioButtonPath.setActionCommand("2");
        jRadioButtonPath.setName("Path Radio"); // NOI18N
        jRadioButtonPath.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        infoButton4.setMessageText("<html>For roads, paths, trails, and bridges.<br><i>Default:</i>Does not impede movement but does not provide any defence bonus.</html>");
        infoButton4.setText("");

        TerrainIconPanel5.setNumber(3);
        TerrainIconPanel5.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonGrass);
        jRadioButtonGrass.setText("Overgrowth");
        jRadioButtonGrass.setActionCommand("3");
        jRadioButtonGrass.setName("Overgrowth Radio"); // NOI18N
        jRadioButtonGrass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        infoButton5.setMessageText("<html>For small obstructions, such as long grass, bushes, uneven ground, or small rubble.<br><i>Default:</i>Offers better defence but slows down <i>regular</i> and <i>centaur</i> units.</html>");
        infoButton5.setText("");

        TerrainIconPanel6.setNumber(4);
        TerrainIconPanel6.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonForest);
        jRadioButtonForest.setText("Forest");
        jRadioButtonForest.setToolTipText("");
        jRadioButtonForest.setActionCommand("4");
        jRadioButtonForest.setName("Forest Radio"); // NOI18N
        jRadioButtonForest.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        infoButton6.setMessageText("<html>For heavily obstructed terrain, such as forests or large rubble.<br><i>Default:</i>Offers higher defence but slows down all ground-based units except <i>stealth</i> units.</html>");
        infoButton6.setText("");

        TerrainIconPanel7.setNumber(5);
        TerrainIconPanel7.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonHills);
        jRadioButtonHills.setText("Hills");
        jRadioButtonHills.setActionCommand("5");
        jRadioButtonHills.setName("Hills Radio"); // NOI18N
        jRadioButtonHills.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        infoButton7.setMessageText("<html>Hills.<br><i>Default:</i>Similar to forest, offers higher defence but slows down all ground-based units except <i>stealth</i> units. <i>regular</i> units are not slowed down as much as forest.</html>");
        infoButton7.setText("");

        TerrainIconPanel8.setNumber(6);
        TerrainIconPanel8.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        TerrainIconPanel1.setNumber(-1);
        TerrainIconPanel1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonDesert);
        jRadioButtonDesert.setText("Sand / Desert");
        jRadioButtonDesert.setActionCommand("6");
        jRadioButtonDesert.setName("Sand Radio"); // NOI18N
        jRadioButtonDesert.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        buttonGroupTerrain.add(jRadioButtonObstructed);
        jRadioButtonObstructed.setSelected(true);
        jRadioButtonObstructed.setText("Obstructed");
        jRadioButtonObstructed.setActionCommand("-1");
        jRadioButtonObstructed.setName("Obstructed Radio"); // NOI18N
        jRadioButtonObstructed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        infoButton8.setMessageText("<html>For sand, desert, or beaches.<br><i>Default:</i>Slow to move on and does not offer any defensive bonus. The only ground terrain that slows down <i>stealth</i> units.</html>");
        infoButton8.setText("");

        infoButton1.setMessageText("<html>Completely obstructed. Useuful for map edges and other  out-of-bounds spaces.<br>No units can move through.</html>\n");
        infoButton1.setText("");

        TerrainIconPanel9.setNumber(7);
        TerrainIconPanel9.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        TerrainIconPanel2.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonMountain);
        jRadioButtonMountain.setText("Sky / Mountain");
        jRadioButtonMountain.setActionCommand("7");
        jRadioButtonMountain.setName("Mountain Radio"); // NOI18N
        jRadioButtonMountain.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonPlains)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonWall)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonObstructed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonGrass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonWater)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonForest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonHills)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonMountain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDesert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonObstructed)
                    .addComponent(infoButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonWall)
                    .addComponent(infoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonPlains)
                    .addComponent(infoButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonPath)
                    .addComponent(infoButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonGrass)
                    .addComponent(infoButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonForest)
                    .addComponent(infoButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonHills)
                    .addComponent(infoButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonDesert)
                    .addComponent(infoButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonMountain)
                    .addComponent(infoButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonWater)
                    .addComponent(infoButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Base Terrains", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(250, 200));

        TerrainIconPanel11.setNumber(9);
        TerrainIconPanel11.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonTerrain9);
        jRadioButtonTerrain9.setText("Additional 1");
        jRadioButtonTerrain9.setActionCommand("9");
        jRadioButtonTerrain9.setName("Additional 1 Radio"); // NOI18N
        jRadioButtonTerrain9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        TerrainIconPanel12.setNumber(10);
        TerrainIconPanel12.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonTerrain10);
        jRadioButtonTerrain10.setText("Additional 2");
        jRadioButtonTerrain10.setActionCommand("10");
        jRadioButtonTerrain10.setName("Additional 2 Radio"); // NOI18N
        jRadioButtonTerrain10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        TerrainIconPanel13.setNumber(11);
        TerrainIconPanel13.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonTerrain11);
        jRadioButtonTerrain11.setText("Additional 3");
        jRadioButtonTerrain11.setActionCommand("11");
        jRadioButtonTerrain11.setName("Additional 3 Radio"); // NOI18N
        jRadioButtonTerrain11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        TerrainIconPanel14.setNumber(12);
        TerrainIconPanel14.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonTerrain12);
        jRadioButtonTerrain12.setText("Additional 4");
        jRadioButtonTerrain12.setActionCommand("12");
        jRadioButtonTerrain12.setName("Additional 4 Radio"); // NOI18N
        jRadioButtonTerrain12.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        TerrainIconPanel15.setNumber(13);
        TerrainIconPanel15.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonTerrain13);
        jRadioButtonTerrain13.setText("Additional 5");
        jRadioButtonTerrain13.setActionCommand("13");
        jRadioButtonTerrain13.setName("Additional 5 Radio"); // NOI18N
        jRadioButtonTerrain13.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        TerrainIconPanel16.setNumber(14);
        TerrainIconPanel16.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonTerrain14);
        jRadioButtonTerrain14.setText("Additional 6");
        jRadioButtonTerrain14.setActionCommand("14");
        jRadioButtonTerrain14.setName("Additional 6 Radio"); // NOI18N
        jRadioButtonTerrain14.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        TerrainIconPanel17.setNumber(15);
        TerrainIconPanel17.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroupTerrain.add(jRadioButtonTerrain15);
        jRadioButtonTerrain15.setText("Additional 7");
        jRadioButtonTerrain15.setActionCommand("15");
        jRadioButtonTerrain15.setName("Additional 7 Radio"); // NOI18N
        jRadioButtonTerrain15.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onTerrainRadioStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonTerrain15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonTerrain14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonTerrain13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonTerrain9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonTerrain10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonTerrain11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TerrainIconPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonTerrain12)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTerrain9))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTerrain10))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTerrain11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTerrain12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTerrain13))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTerrain14))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TerrainIconPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTerrain15))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Additional Terrains", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxTerrainView, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(infoButtonSharedTerrain, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(infoButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTerrainView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoButtonSharedTerrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(infoButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTerrainViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTerrainViewActionPerformed
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ComboAction(jComboBoxTerrainView, jComboBoxTerrainView.getSelectedIndex(), actionTerrainDrawMode.ordinal()));
        }
        if (jComboBoxTerrainView.getSelectedIndex() >= 0) {
            actionTerrainDrawMode = (TerrainDrawMode)jComboBoxTerrainView.getSelectedItem();
            updateDrawModePanels(actionTerrainDrawMode);
            if (modeChanged != null) {
                modeChanged.actionPerformed(new ActionEvent(actionTerrainDrawMode, jComboBoxTerrainView.getSelectedIndex(), null));
            }
            TerrainSettings terrainSettings = SettingsManager.getSettingsStore("terrain");
            terrainSettings.setTerrainDrawMode(actionTerrainDrawMode);
            SettingsManager.saveSettingsFile();
        }
    }//GEN-LAST:event_jComboBoxTerrainViewActionPerformed

    private void onTerrainRadioStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_onTerrainRadioStateChanged
        JRadioButton radioButton = (JRadioButton)evt.getSource();
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new RadioButtonAction(buttonGroupTerrain, radioButton, actionTerrainRadioButton));
        } else {
            int index = Integer.parseInt(radioButton.getActionCommand());
            jTabbedPane1.setSelectedIndex(index < 9 ? 0 : 1);
        }
        actionTerrainRadioButton = radioButton;
        if (buttonSelected != null) {
            ActionEvent event = new ActionEvent(radioButton, evt.getID(), radioButton.getActionCommand(), 0);
            buttonSelected.actionPerformed(event);
        }
    }//GEN-LAST:event_onTerrainRadioStateChanged
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel1;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel10;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel11;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel12;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel13;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel14;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel15;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel16;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel17;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel2;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel3;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel4;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel5;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel6;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel7;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel8;
    private com.sfc.sf2.battle.mapterrain.gui.controls.TerrainIconPanel TerrainIconPanel9;
    private com.sfc.sf2.core.gui.controls.NameableButtonGroup buttonGroupTerrain;
    private com.formdev.flatlaf.icons.FlatOptionPaneWarningIcon flatOptionPaneWarningIcon1;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton1;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton10;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton12;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton13;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton2;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton3;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton4;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton5;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton6;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton7;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton8;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton9;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButtonSharedTerrain;
    private javax.swing.JComboBox<String> jComboBoxTerrainView;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonDesert;
    private javax.swing.JRadioButton jRadioButtonForest;
    private javax.swing.JRadioButton jRadioButtonGrass;
    private javax.swing.JRadioButton jRadioButtonHills;
    private javax.swing.JRadioButton jRadioButtonMountain;
    private javax.swing.JRadioButton jRadioButtonObstructed;
    private javax.swing.JRadioButton jRadioButtonPath;
    private javax.swing.JRadioButton jRadioButtonPlains;
    private javax.swing.JRadioButton jRadioButtonTerrain10;
    private javax.swing.JRadioButton jRadioButtonTerrain11;
    private javax.swing.JRadioButton jRadioButtonTerrain12;
    private javax.swing.JRadioButton jRadioButtonTerrain13;
    private javax.swing.JRadioButton jRadioButtonTerrain14;
    private javax.swing.JRadioButton jRadioButtonTerrain15;
    private javax.swing.JRadioButton jRadioButtonTerrain9;
    private javax.swing.JRadioButton jRadioButtonWall;
    private javax.swing.JRadioButton jRadioButtonWater;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
