/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.palette;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.BasicAction;
import com.sfc.sf2.palette.gui.controls.CRAMColorEditor;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.beans.BeanProperty;
import java.util.EventListener;

/**
 *
 * @author TiMMy
 */
public class CRAMColorPicker extends javax.swing.JPanel {

    private String colorDialogTitle = "CRAM Color";
    private CRAMColor color;
    
    /**
     * Creates new form ColorPicker
     */
    public CRAMColorPicker() {
        initComponents();
    }
    
    public String getDialogTitle() {
        return colorDialogTitle;
    }
    
    @BeanProperty(preferred = true, visualUpdate = true, description = "The title to show on the CRAM Color Chooser popup.")
    public void setDialogTitle(String colorChooserText) {
        this.colorDialogTitle = colorChooserText;
    }
    
    public CRAMColor getCRAMColor() {
        if (color == null) {
            color = new CRAMColor(getBackground());
        }
        return color;
    }
    
    @BeanProperty(preferred = true, visualUpdate = true, description = "The default CRAM color of the picker.")
    public void setCRAMColor(CRAMColor color) {
        this.color = color;
        this.setBackground(color.CRAMColor());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser = new javax.swing.JColorChooser();

        setBackground(new java.awt.Color(200, 0, 200));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        setMaximumSize(new java.awt.Dimension(100, 100));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(30, 30));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        CRAMColor returnCol = CRAMColorEditor.showDialog(this, colorDialogTitle, new CRAMColor(getBackground()));
        if (returnCol != null) {
            CRAMColor oldColor = this.getCRAMColor();
            ActionManager.setAndExecuteAction(new BasicAction<CRAMColor>(this, "Change CRAM Color", this::setColorUpdated, returnCol, oldColor));
        }
    }//GEN-LAST:event_formMouseClicked
    
    public void setColorUpdated(CRAMColor color) {
        this.color = color;
        this.setBackground(color.CRAMColor());
        fireColorChanged();
    }
    
    public synchronized void addColorChangedListener(ColorChangedListener l) {
        listenerList.add(ColorChangedListener.class, l);
    }

    public synchronized void removeColorChangedListener(ColorChangedListener l) {
        listenerList.remove(ColorChangedListener.class, l);
    }
    
    @SuppressWarnings("deprecation")
    public void fireColorChanged() {
        // Guaranteed to return a non-null array
        Object[] listeners = listenerList.getListenerList();
        ActionEvent e = new ActionEvent(this, ActionEvent.ACTION_PERFORMED, "CRAM Color Changed", (int)EventQueue.getMostRecentEventTime());
        // Process the listeners last to first, notifying
        // those that are interested in this event
        for (int i = listeners.length-2; i>=0; i-=2) {
            if (listeners[i]==ColorChangedListener.class) {
                ((ColorChangedListener)listeners[i+1]).colorChanged(e);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser jColorChooser;
    // End of variables declaration//GEN-END:variables
    
    public interface ColorChangedListener extends EventListener {

        /**
         * Invoked when an action occurs.
         * @param e the event to be processed
         */
        public void colorChanged(ActionEvent e);
    }
}
