/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sfc.sf2.vwfont.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.NonCombinableAction;
import com.sfc.sf2.core.actions.RadioButtonAction;
import com.sfc.sf2.core.gui.AbstractMainEditor;
import com.sfc.sf2.core.gui.controls.Console;
import com.sfc.sf2.core.io.FileFormat;
import com.sfc.sf2.core.settings.SettingsManager;
import com.sfc.sf2.core.settings.ViewSettings;
import com.sfc.sf2.helpers.PathHelpers;
import com.sfc.sf2.helpers.RenderScaleHelpers;
import com.sfc.sf2.vwfont.FontSymbol;
import com.sfc.sf2.vwfont.VWFontManager;
import com.sfc.sf2.vwfont.settings.FontSettings;
import java.awt.Color;
import java.nio.file.Path;
import java.util.logging.Level;
import javax.swing.JRadioButton;

/**
 *
 * @author wiz
 */
public class VWFontMainEditor extends AbstractMainEditor {
    
    private final ViewSettings viewSettings = new ViewSettings(10, RenderScaleHelpers.RENDER_SCALE_2X, new Color(200, 200, 255));
    private final FontSettings fontSettings = new FontSettings();
    private final VWFontManager fontManager = new VWFontManager();
    
    private JRadioButton actionPreviousFormat = null;
    
    public VWFontMainEditor() {
        super();
        SettingsManager.registerSettingsStore("view", viewSettings);
        SettingsManager.registerSettingsStore("font", fontSettings);
        initComponents();
        initCore(console1);
    }
    
    @Override
    protected void initEditor() {
        super.initEditor();
        
        viewPanel1.setLayoutPanel(fontSymbolLayoutPanel, viewSettings);
        
        if (fontSettings.getExportFileFormat() == FileFormat.PNG) {
            actionPreviousFormat = jRadioButtonPNG;
            jRadioButtonPNG.setSelected(true);
        } else {
            actionPreviousFormat = jRadioButtonGIF;
            jRadioButtonGIF.setSelected(true);
        }
    }
    
    @Override
    protected void onDataLoaded() {
        super.onDataLoaded();
        ActionManager.setAndExecuteAction(new NonCombinableAction<FontSymbol[]>(this, "Font Symbols Imported", this::actionSymbolsLoaded, fontManager.getFontSymbols(), fontSymbolLayoutPanel.getFontSymbols()));
    }
    
    private void actionSymbolsLoaded(FontSymbol[] symbols) {
        fontSymbolLayoutPanel.setFontSymbols(symbols);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupExport = new com.sfc.sf2.core.gui.controls.NameableButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        infoButton3 = new com.sfc.sf2.core.gui.controls.InfoButton();
        fileButtonImportSymbols = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonImportSymbols = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        infoButton4 = new com.sfc.sf2.core.gui.controls.InfoButton();
        directoryButtonImportImages = new com.sfc.sf2.core.gui.controls.DirectoryButton();
        jButtonImportImages = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        infoButton5 = new com.sfc.sf2.core.gui.controls.InfoButton();
        fileButtonExportSymbols = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonExportSymbols = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        infoButton6 = new com.sfc.sf2.core.gui.controls.InfoButton();
        directoryButtonExportImages = new com.sfc.sf2.core.gui.controls.DirectoryButton();
        jPanel6 = new javax.swing.JPanel();
        infoButton2 = new com.sfc.sf2.core.gui.controls.InfoButton();
        jRadioButtonGIF = new javax.swing.JRadioButton();
        jRadioButtonPNG = new javax.swing.JRadioButton();
        jLabelFormat = new javax.swing.JLabel();
        jButtonExportImages = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fontSymbolLayoutPanel = new com.sfc.sf2.vwfont.gui.FontSymbolLayoutPanel();
        viewPanel1 = new com.sfc.sf2.vwfont.gui.VWFontViewPanel();
        console1 = new com.sfc.sf2.core.gui.controls.Console();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SF2VWFontManager");

        jSplitPane1.setDividerLocation(450);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane2.setDividerLocation(400);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Import from :"));
        jPanel3.setPreferredSize(new java.awt.Dimension(590, 135));

        jLabel2.setText("Import VW font disassembly.");

        infoButton3.setMessageText("<html>The variable width font is the font that is displayed in text boxes (e.g. for character dialog).<br>\"Variable Width\" means that the font is not monospaced.<br>All VW font symbols are stored in the one disassembly file.</html>");
        infoButton3.setText("");

        fileButtonImportSymbols.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonImportSymbols.setFilePath(".\\variablewidthfont.bin");
        fileButtonImportSymbols.setInfoMessage("");
        fileButtonImportSymbols.setLabelText("BIN File :");
        fileButtonImportSymbols.setName("Import Font Symbols"); // NOI18N

        jButtonImportSymbols.setText("Import");
        jButtonImportSymbols.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportSymbolsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 278, Short.MAX_VALUE)
                        .addComponent(jButtonImportSymbols))
                    .addComponent(fileButtonImportSymbols, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportSymbols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImportSymbols)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Disassembly", jPanel4);

        jLabel3.setText("Import VW font symbols from images.");

        infoButton4.setMessageText("<html>Symbol images should be in format \"symbolXX.png\". Supports image formats: PNG or GIF.<br>Will automatically load an image if it is in a supported format.<br><br>Color format should be indexed colors (ideally 4BPP / 16).<br>- Color 0 is transparent.<br>- Color 1 (black) is 'filled' with font symbol.<br>- Color 2 (grey) is the width of the font symbol. The image should include a single Color 2 pixel on the top row of the image.</html>");
        infoButton4.setText("");

        directoryButtonImportImages.setDirectoryPath(".\\export\\");
            directoryButtonImportImages.setInfoMessage("");
            directoryButtonImportImages.setLabelText("Symbols drectory :");
            directoryButtonImportImages.setName("Import Images"); // NOI18N

            jButtonImportImages.setText("Import");
            jButtonImportImages.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonImportImagesActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
            jPanel9.setLayout(jPanel9Layout);
            jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                            .addGap(0, 278, Short.MAX_VALUE)
                            .addComponent(jButtonImportImages))
                        .addComponent(directoryButtonImportImages, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(infoButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(infoButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(directoryButtonImportImages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonImportImages)
                    .addContainerGap())
            );

            jTabbedPane1.addTab("Image", jPanel9);

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jTabbedPane1)
                    .addContainerGap())
            );

            jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Export to :"));
            jPanel5.setPreferredSize(new java.awt.Dimension(32, 135));

            jLabel1.setText("Export VW font disassembly.");

            infoButton5.setMessageText("<html>VW font symbols will be exported to a single binary.</html>");
            infoButton5.setText("");

            fileButtonExportSymbols.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
            fileButtonExportSymbols.setFilePath(".\\variablewidthfont.bin");
            fileButtonExportSymbols.setInfoMessage("");
            fileButtonExportSymbols.setLabelText("BIN file :");
            fileButtonExportSymbols.setName("Export Font Symbols"); // NOI18N

            jButtonExportSymbols.setText("Export");
            jButtonExportSymbols.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonExportSymbolsActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
            jPanel11.setLayout(jPanel11Layout);
            jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fileButtonExportSymbols, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButtonExportSymbols))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(infoButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(infoButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fileButtonExportSymbols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonExportSymbols)
                    .addContainerGap())
            );

            jTabbedPane2.addTab("Disassembly", jPanel11);

            jLabel9.setText("Export VW font symbols to images.");

            infoButton6.setMessageText("<html>VW font symbols will be exported to individual images, in format \"symbolXX.png\". Supported image formats: PNG or GIF.<br><brFormat will be 4BPP / 16 indexed color.<br>- Color 0 is transparent.<br>- Color 1 (black) is 'filled' with font symbol.<br>- Color 2 (grey) is the width of the font symbol. Each image will be given a single Color 2 pixel on the top row of the image.<br>- All other colors are unused.</html>");
            infoButton6.setText("");

            directoryButtonExportImages.setDirectoryPath(".\\export\\");
                directoryButtonExportImages.setInfoMessage("");
                directoryButtonExportImages.setLabelText("Image directory :");
                directoryButtonExportImages.setName("Export Images"); // NOI18N

                jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

                infoButton2.setMessageText("Export the images as .PNG or .GIF format.");
                infoButton2.setText("");

                buttonGroupExport.add(jRadioButtonGIF);
                jRadioButtonGIF.setText("GIF");
                jRadioButtonGIF.addItemListener(new java.awt.event.ItemListener() {
                    public void itemStateChanged(java.awt.event.ItemEvent evt) {
                        jRadioButtonFormatStateChanged(evt);
                    }
                });

                buttonGroupExport.add(jRadioButtonPNG);
                jRadioButtonPNG.setSelected(true);
                jRadioButtonPNG.setText("PNG");
                jRadioButtonPNG.addItemListener(new java.awt.event.ItemListener() {
                    public void itemStateChanged(java.awt.event.ItemEvent evt) {
                        jRadioButtonFormatStateChanged(evt);
                    }
                });

                jLabelFormat.setText("File format :");

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                    jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelFormat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonPNG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonGIF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel6Layout.setVerticalGroup(
                    jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(infoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonGIF)
                            .addComponent(jRadioButtonPNG)
                            .addComponent(jLabelFormat))
                        .addContainerGap())
                );

                jButtonExportImages.setText("Export");
                jButtonExportImages.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonExportImagesActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
                jPanel14.setLayout(jPanel14Layout);
                jPanel14Layout.setHorizontalGroup(
                    jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(directoryButtonExportImages, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExportImages))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                );
                jPanel14Layout.setVerticalGroup(
                    jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(directoryButtonExportImages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonExportImages)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                );

                jTabbedPane2.addTab("Image", jPanel14);

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane2)
                        .addContainerGap())
                );
                jPanel5Layout.setVerticalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                );

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                        .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))
                );

                jSplitPane2.setLeftComponent(jPanel2);

                jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Symbols"));

                javax.swing.GroupLayout fontSymbolLayoutPanelLayout = new javax.swing.GroupLayout(fontSymbolLayoutPanel);
                fontSymbolLayoutPanel.setLayout(fontSymbolLayoutPanelLayout);
                fontSymbolLayoutPanelLayout.setHorizontalGroup(
                    fontSymbolLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 438, Short.MAX_VALUE)
                );
                fontSymbolLayoutPanelLayout.setVerticalGroup(
                    fontSymbolLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 371, Short.MAX_VALUE)
                );

                jScrollPane2.setViewportView(fontSymbolLayoutPanel);

                javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
                jPanel10.setLayout(jPanel10Layout);
                jPanel10Layout.setHorizontalGroup(
                    jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(viewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                );
                jPanel10Layout.setVerticalGroup(
                    jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(viewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                jSplitPane2.setRightComponent(jPanel10);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 805, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane2))
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 411, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jSplitPane2)
                            .addContainerGap()))
                );

                jSplitPane1.setTopComponent(jPanel1);
                jSplitPane1.setRightComponent(console1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                );

                setSize(new java.awt.Dimension(821, 685));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void jButtonExportSymbolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportSymbolsActionPerformed
        Path disasmPath = PathHelpers.getBasePath().resolve(fileButtonExportSymbols.getFilePath());
        if (!PathHelpers.createPathIfRequred(disasmPath)) return;
        try {
            fontManager.exportDisassembly(disasmPath, fontSymbolLayoutPanel.getFontSymbols());
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Font symbol disasm could not be exported to : " + disasmPath);
        }
    }//GEN-LAST:event_jButtonExportSymbolsActionPerformed

    private void jButtonExportImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportImagesActionPerformed
        Path directoryPath = PathHelpers.getBasePath().resolve(directoryButtonExportImages.getDirectoryPath());
        if (!PathHelpers.createPathIfRequred(directoryPath)) return;
        try {
            fontManager.exportAllImages(directoryPath, fontSymbolLayoutPanel.getFontSymbols(), FileFormat.ANY_IMAGE);
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Font symbols images could not be exported to : " + directoryPath);
        }
    }//GEN-LAST:event_jButtonExportImagesActionPerformed

    private void jButtonImportImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportImagesActionPerformed
        Path directoryPath = PathHelpers.getBasePath().resolve(directoryButtonImportImages.getDirectoryPath());
        try {
            FileFormat format = FileFormat.ANY_IMAGE;
            fontManager.importAllImages(directoryPath, format);
        } catch (Exception ex) {
            fontManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Font symbol images could not be imported from : " + directoryPath);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportImagesActionPerformed

    private void jButtonImportSymbolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportSymbolsActionPerformed
        Path disasmPath = PathHelpers.getBasePath().resolve(fileButtonImportSymbols.getFilePath());
        try {
            fontManager.importDisassembly(disasmPath);
        } catch (Exception ex) {
            fontManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Font symbol disasm could not be imported from : " + disasmPath);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportSymbolsActionPerformed

    private void jRadioButtonFormatStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonFormatStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new RadioButtonAction(buttonGroupExport, (JRadioButton)evt.getSource(), actionPreviousFormat));
        }
        actionPreviousFormat = (JRadioButton)evt.getSource();
        switch (actionPreviousFormat.getActionCommand()) {
            case "PNG":
                break;
            case "GIF":
                break;
        }
        FileFormat format = actionPreviousFormat.getActionCommand().equals("PNG") ? FileFormat.PNG : FileFormat.GIF;
        fontSettings.setExportFileFormat(format);
        SettingsManager.saveSettingsFile();
    }//GEN-LAST:event_jRadioButtonFormatStateChanged
    
    /**
     * To create a new Main Editor, copy the below code
     * Don't forget to change the new main class (below)
     */
    public static void main(String args[]) {
        AbstractMainEditor.programSetup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VWFontMainEditor().setVisible(true);  // <------ Change this class to new Main Editor class
            }
        });
    }
    /**
     * To create a new Main Editor, copy the above code
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.NameableButtonGroup buttonGroupExport;
    private com.sfc.sf2.core.gui.controls.Console console1;
    private com.sfc.sf2.core.gui.controls.DirectoryButton directoryButtonExportImages;
    private com.sfc.sf2.core.gui.controls.DirectoryButton directoryButtonImportImages;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportSymbols;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportSymbols;
    private com.sfc.sf2.vwfont.gui.FontSymbolLayoutPanel fontSymbolLayoutPanel;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton2;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton3;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton4;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton5;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton6;
    private javax.swing.JButton jButtonExportImages;
    private javax.swing.JButton jButtonExportSymbols;
    private javax.swing.JButton jButtonImportImages;
    private javax.swing.JButton jButtonImportSymbols;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonGIF;
    private javax.swing.JRadioButton jRadioButtonPNG;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.sfc.sf2.vwfont.gui.VWFontViewPanel viewPanel1;
    // End of variables declaration//GEN-END:variables

}
