/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.map.block.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.ToggleAction;
import com.sfc.sf2.core.gui.controls.AbstractViewPanel;
import javax.swing.JCheckBox;

/**
 *
 * @author TiMMy
 */
public class BlockEditViewPanel extends AbstractViewPanel<EditableBlockSlotPanel> {
        
    public JCheckBox getPriorityCheckBox() { return jCheckBoxPriority; }
    
    /**
     * Creates new form ViewPanel
     */
    public BlockEditViewPanel() {
        super();
        initComponents();
        init(null, jCheckBoxGrid, null, colorPickerBG);
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBG = new javax.swing.JLabel();
        colorPickerBG = new com.sfc.sf2.core.gui.controls.ColorPicker();
        jCheckBoxGrid = new javax.swing.JCheckBox();
        jCheckBoxPriority = new javax.swing.JCheckBox();

        jLabelBG.setText("BG :");

        colorPickerBG.setName("BG Color Picker"); // NOI18N
        colorPickerBG.addColorChangedListener(new com.sfc.sf2.core.gui.controls.ColorPicker.ColorChangedListener() {
            public void colorChanged(java.awt.event.ActionEvent evt) {
                colorPickerBGColorChanged(evt);
            }
        });

        javax.swing.GroupLayout colorPickerBGLayout = new javax.swing.GroupLayout(colorPickerBG);
        colorPickerBG.setLayout(colorPickerBGLayout);
        colorPickerBGLayout.setHorizontalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        colorPickerBGLayout.setVerticalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jCheckBoxGrid.setLabel("Show Grid");
        jCheckBoxGrid.setName("Grid Toggle"); // NOI18N
        jCheckBoxGrid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxGridItemStateChanged(evt);
            }
        });

        jCheckBoxPriority.setText("Show Priority");
        jCheckBoxPriority.setName("Priority Toggle"); // NOI18N
        jCheckBoxPriority.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxPriorityItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxPriority)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabelBG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxGrid)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelBG)
                    .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxPriority))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxGrid)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Blocks View");
    }// </editor-fold>//GEN-END:initComponents

    private void colorPickerBGColorChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorPickerBGColorChanged
        super.onBGColorChanged(evt);
    }//GEN-LAST:event_colorPickerBGColorChanged

    private void jCheckBoxGridItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxGridItemStateChanged
        super.onGridChanged(evt);
    }//GEN-LAST:event_jCheckBoxGridItemStateChanged

    private void jCheckBoxPriorityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxPriorityItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxPriority, jCheckBoxPriority.isSelected()));
        }
        if (layoutPanel != null) {
            layoutPanel.setShowPriority(jCheckBoxPriority.isSelected());
        }
    }//GEN-LAST:event_jCheckBoxPriorityItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.ColorPicker colorPickerBG;
    private javax.swing.JCheckBox jCheckBoxGrid;
    private javax.swing.JCheckBox jCheckBoxPriority;
    private javax.swing.JLabel jLabelBG;
    // End of variables declaration//GEN-END:variables
}
