/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sfc.sf2.map.block.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.CustomAction;
import com.sfc.sf2.core.actions.RadioButtonAction;
import com.sfc.sf2.core.gui.AbstractMainEditor;
import com.sfc.sf2.core.gui.controls.Console;
import com.sfc.sf2.core.settings.SettingsManager;
import com.sfc.sf2.core.settings.ViewSettings;
import com.sfc.sf2.graphics.Tileset;
import com.sfc.sf2.helpers.PathHelpers;
import com.sfc.sf2.helpers.RenderScaleHelpers;
import com.sfc.sf2.map.block.MapBlock;
import com.sfc.sf2.map.block.MapBlocksetManager;
import com.sfc.sf2.map.block.MapBlockset;
import com.sfc.sf2.map.block.actions.BlockChangeActionData;
import com.sfc.sf2.map.block.actions.MapBlocksetActionData;
import java.awt.event.ActionEvent;
import java.nio.file.Path;
import java.util.logging.Level;
import javax.swing.JRadioButton;

/**
 *
 * @author wiz
 */
public class MapBlockMainEditor extends AbstractMainEditor {
    
    private final ViewSettings blockViewSettings = new ViewSettings(10, RenderScaleHelpers.RENDER_SCALE_1X);
    private final ViewSettings TilesetViewSettings = new ViewSettings(20, RenderScaleHelpers.RENDER_SCALE_2X);
    private final ViewSettings blockEditViewSettings = new ViewSettings();
    private final MapBlocksetManager mapblockManager = new MapBlocksetManager();
    
    private JRadioButton actionTileButton;
    
    public MapBlockMainEditor() {
        super();
        SettingsManager.registerSettingsStore("mapBlockset", blockViewSettings);
        SettingsManager.registerSettingsStore("mapTileset", TilesetViewSettings);
        SettingsManager.registerSettingsStore("blockEdit", blockEditViewSettings);
        initComponents();
        initCore(console1);
    }
    
    @Override
    protected void initEditor() {
        super.initEditor();
        
        blocksetViewPanel1.setLayoutPanel(mapBlocksetLayoutPanel, blockViewSettings);
        tilesetViewPanel1.setLayoutPanel(tilesetsLayoutPanel, TilesetViewSettings);
        blockEditViewPanel1.setLayoutPanel(editableBlockSlotPanel, blockEditViewSettings);
        accordionPanel1.setExpanded(false);
        
        editableBlockSlotPanel.setBlockEditedListener(this::onBlockEdited);
        editableBlockSlotPanel.setLeftTileSlotPanel(tileSlotPanelLeft);
        editableBlockSlotPanel.setRightTileSlotPanel(tileSlotPanelRight);
        mapBlocksetLayoutPanel.setEditableBlockPanel(editableBlockSlotPanel);
        tilesetsLayoutPanel.setLeftSlotTilePanel(tileSlotPanelLeft);
        tilesetsLayoutPanel.setRightSlotBlockPanel(tileSlotPanelRight);
        tilesetsLayoutPanel.setBlockSlotPanel(editableBlockSlotPanel);
        
        actionTileButton = jRadioButtonApplyTile;
    }
    
    @Override
    protected void onDataLoaded() {
        super.onDataLoaded();
        MapBlocksetActionData newValue = new MapBlocksetActionData(mapblockManager.getMapBlockset(), mapblockManager.getTilesets());
        MapBlocksetActionData oldValue = new MapBlocksetActionData(mapBlocksetLayoutPanel.getBlockset(), tilesetsLayoutPanel.getTilesets());
        ActionManager.setAndExecuteAction(new CustomAction<MapBlocksetActionData>(this, "Blockset Imported", this::actionBlocksetLoaded, newValue, oldValue));
    }
    
    private void actionBlocksetLoaded(MapBlocksetActionData blocksetData) {  
        
        Tileset[] tilesets = blocksetData.tilesets();
        MapBlockset mapBlockset = blocksetData.blockset();
        if (mapBlockset != null) {
            mapBlocksetLayoutPanel.setBlockset(mapBlockset);
            mapBlocksetLayoutPanel.setTilesets(tilesets);
            mapBlocksetLayoutPanel.setLeftSelectedIndex(-1);
        }
        if (tilesets != null) {
            tilesetsLayoutPanel.setTilesets(tilesets);
            String[] tilesetNames = new String[tilesets.length];
            for (int i = 0; i < tilesets.length; i++) {
                if (tilesets[i] == null) {
                    tilesetNames[i] = "NONE";
                } else {
                    tilesetNames[i] = tilesets[i].getName();
                }
            }
            tilesetViewPanel1.setTilesets(tilesets);
            
            tileSlotPanelLeft.setTile(null);
            tileSlotPanelLeft.setTilesets(tilesets);
            tileSlotPanelRight.setTile(null);
            tileSlotPanelRight.setTilesets(tilesets);
            editableBlockSlotPanel.setTilesets(tilesets);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTileEditing = new com.sfc.sf2.core.gui.controls.NameableButtonGroup();
        jPanel13 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel15 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel30 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButtonImportDirectory = new javax.swing.JButton();
        directoryButtonImportMap = new com.sfc.sf2.core.gui.controls.DirectoryButton();
        accordionPanel1 = new com.sfc.sf2.core.gui.controls.AccordionPanel();
        fileButtonPaletteEntries = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonTilesetEntries = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonTilesets = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonBlockset = new com.sfc.sf2.core.gui.controls.FileButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonImportData = new javax.swing.JButton();
        fileButtonPalette = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonTileset1 = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonTileset2 = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonTileset3 = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonTileset4 = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonTileset5 = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonBlocks = new com.sfc.sf2.core.gui.controls.FileButton();
        jPanel17 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel26 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        fileButtonExportTilesets = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonExportBlockset = new com.sfc.sf2.core.gui.controls.FileButton();
        jPanel28 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButtonExportBlockset = new javax.swing.JButton();
        fileButtonExportBlocksetImage = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonExportBlocksetPriorities = new com.sfc.sf2.core.gui.controls.FileButton();
        directoryButtonExportMap = new com.sfc.sf2.core.gui.controls.DirectoryButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mapBlocksetLayoutPanel = new com.sfc.sf2.map.block.gui.MapBlocksetLayoutPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonAddBlock = new javax.swing.JButton();
        jButtonRemoveBlock = new javax.swing.JButton();
        jButtonCloneBlock = new javax.swing.JButton();
        blocksetViewPanel1 = new com.sfc.sf2.map.block.gui.BlocksetViewPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tilesetsLayoutPanel = new com.sfc.sf2.map.block.gui.TilesetsLayoutPanel();
        tilesetViewPanel1 = new com.sfc.sf2.map.block.gui.TilesetViewPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        editableBlockSlotPanel = new com.sfc.sf2.map.block.gui.EditableBlockSlotPanel();
        blockEditViewPanel1 = new com.sfc.sf2.map.block.gui.BlockEditViewPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tileSlotPanelLeft = new com.sfc.sf2.map.block.gui.TileSlotPanel();
        tileSlotPanelRight = new com.sfc.sf2.map.block.gui.TileSlotPanel();
        jRadioButtonApplyTile = new javax.swing.JRadioButton();
        jRadioButtonSetPriority = new javax.swing.JRadioButton();
        jRadioButtonFlipTile = new javax.swing.JRadioButton();
        infoButton3 = new com.sfc.sf2.core.gui.controls.InfoButton();
        infoButton4 = new com.sfc.sf2.core.gui.controls.InfoButton();
        infoButton5 = new com.sfc.sf2.core.gui.controls.InfoButton();
        console1 = new com.sfc.sf2.core.gui.controls.Console();

        buttonGroupTileEditing.setName("Tile Editing Group");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SF2MapBlockManager");

        jSplitPane1.setDividerLocation(600);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);

        jSplitPane2.setDividerLocation(700);
        jSplitPane2.setOneTouchExpandable(true);

        jSplitPane3.setDividerLocation(350);
        jSplitPane3.setResizeWeight(1.0);

        jPanel31.setMinimumSize(new java.awt.Dimension(300, 300));

        jPanel32.setBorder(javax.swing.BorderFactory.createTitledBorder("Import :"));

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Import from :"));

        jLabel6.setText("Select disassembly files.");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonImportDirectory.setText("Import");
        jButtonImportDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportDirectoryActionPerformed(evt);
            }
        });

        directoryButtonImportMap.setDirectoryPath(".\\entries\\map03\\");
            directoryButtonImportMap.setInfoMessage("");
            directoryButtonImportMap.setLabelText("Map dir :");
            directoryButtonImportMap.setName("Import Map"); // NOI18N

            javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
            jPanel21.setLayout(jPanel21Layout);
            jPanel21Layout.setHorizontalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(directoryButtonImportMap, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel21Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonImportDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
            );
            jPanel21Layout.setVerticalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(directoryButtonImportMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel6)
                        .addComponent(jButtonImportDirectory))
                    .addContainerGap())
            );

            accordionPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Palette, tilesets, & map data"));

            fileButtonPaletteEntries.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
            fileButtonPaletteEntries.setFilePath("..\\graphics\\maps\\mappalettes\\entries.asm");
            fileButtonPaletteEntries.setInfoMessage("");
            fileButtonPaletteEntries.setLabelText("Palette entries :");
            fileButtonPaletteEntries.setName("Import Palette Entries"); // NOI18N

            fileButtonTilesetEntries.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
            fileButtonTilesetEntries.setFilePath("..\\graphics\\maps\\maptilesets\\entries.asm");
            fileButtonTilesetEntries.setInfoMessage("");
            fileButtonTilesetEntries.setLabelText("Tilesets entries :");
            fileButtonTilesetEntries.setName("Import Tileset Entries"); // NOI18N

            fileButtonTilesets.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
            fileButtonTilesets.setFilePath("00-tilesets.asm");
            fileButtonTilesets.setInfoMessage("");
            fileButtonTilesets.setLabelText("Map tilesets :");
            fileButtonTilesets.setName("Import Tilesets"); // NOI18N

            fileButtonBlockset.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
            fileButtonBlockset.setFilePath("0-blocks.bin");
            fileButtonBlockset.setInfoMessage("");
            fileButtonBlockset.setLabelText("Map blockset :");
            fileButtonBlockset.setToolTipText("");
            fileButtonBlockset.setName("Import Blockset"); // NOI18N

            javax.swing.GroupLayout accordionPanel1Layout = new javax.swing.GroupLayout(accordionPanel1);
            accordionPanel1.setLayout(accordionPanel1Layout);
            accordionPanel1Layout.setHorizontalGroup(
                accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(accordionPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fileButtonPaletteEntries, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(fileButtonTilesetEntries, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(fileButtonTilesets, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(fileButtonBlockset, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap())
            );
            accordionPanel1Layout.setVerticalGroup(
                accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(accordionPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(fileButtonPaletteEntries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fileButtonTilesetEntries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fileButtonTilesets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fileButtonBlockset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
            jPanel14.setLayout(jPanel14Layout);
            jPanel14Layout.setHorizontalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(accordionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel14Layout.setVerticalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(accordionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            jTabbedPane1.addTab("Map", jPanel14);

            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Import from :"));
            jPanel3.setPreferredSize(new java.awt.Dimension(590, 135));

            jLabel2.setText("Select individual disassembly files.");
            jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

            jButtonImportData.setText("Import");
            jButtonImportData.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonImportDataActionPerformed(evt);
                }
            });

            fileButtonPalette.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
            fileButtonPalette.setFilePath("..\\graphics\\maps\\mappalettes\\mappalette00.bin");
            fileButtonPalette.setInfoMessage("");
            fileButtonPalette.setLabelText("Palette :");
            fileButtonPalette.setName("Import Palette"); // NOI18N

            fileButtonTileset1.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
            fileButtonTileset1.setFilePath("..\\graphics\\maps\\maptilesets\\maptileset000.bin");
            fileButtonTileset1.setInfoMessage("");
            fileButtonTileset1.setLabelText("Tileset 1 :");
            fileButtonTileset1.setName("Import Tileset 1"); // NOI18N

            fileButtonTileset2.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
            fileButtonTileset2.setFilePath("..\\graphics\\maps\\maptilesets\\maptileset037.bin");
            fileButtonTileset2.setInfoMessage("");
            fileButtonTileset2.setLabelText("Tileset 2 :");
            fileButtonTileset2.setName("Import Tileset 2"); // NOI18N

            fileButtonTileset3.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
            fileButtonTileset3.setFilePath("..\\graphics\\maps\\maptilesets\\maptileset043.bin");
            fileButtonTileset3.setInfoMessage("");
            fileButtonTileset3.setLabelText("Tileset 3 :");
            fileButtonTileset3.setName("Import Tileset 3"); // NOI18N

            fileButtonTileset4.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
            fileButtonTileset4.setFilePath("..\\graphics\\maps\\maptilesets\\maptileset053.bin");
            fileButtonTileset4.setInfoMessage("");
            fileButtonTileset4.setLabelText("Tileset 4 :");
            fileButtonTileset4.setName("Import Tileset 4"); // NOI18N

            fileButtonTileset5.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
            fileButtonTileset5.setFilePath("..\\graphics\\maps\\maptilesets\\maptileset066.bin");
            fileButtonTileset5.setInfoMessage("");
            fileButtonTileset5.setLabelText("Tileset 5 :");
            fileButtonTileset5.setName("Import Tileset 5"); // NOI18N

            fileButtonBlocks.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
            fileButtonBlocks.setFilePath(".\\entries\\map03\\0-blocks.bin");
            fileButtonBlocks.setInfoMessage("");
            fileButtonBlocks.setLabelText("Blocks file :");
            fileButtonBlocks.setName("Import Blocks"); // NOI18N

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fileButtonPalette, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonImportData))
                        .addComponent(fileButtonTileset1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(fileButtonTileset2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(fileButtonTileset3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(fileButtonTileset4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(fileButtonTileset5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(fileButtonBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(fileButtonPalette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fileButtonTileset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fileButtonTileset2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fileButtonTileset3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fileButtonTileset4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fileButtonTileset5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fileButtonBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jButtonImportData))
                    .addContainerGap())
            );

            javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
            jPanel11.setLayout(jPanel11Layout);
            jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addContainerGap())
            );
            jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Data", jPanel11);

            javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
            jPanel32.setLayout(jPanel32Layout);
            jPanel32Layout.setHorizontalGroup(
                jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            );
            jPanel32Layout.setVerticalGroup(
                jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1)
            );

            jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Export :"));
            jPanel17.setPreferredSize(new java.awt.Dimension(32, 135));

            jLabel7.setText("<html>Select new target file.</html>");
            jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

            jButton4.setText("Export");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });

            fileButtonExportTilesets.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
            fileButtonExportTilesets.setFilePath("00-tilesets.asm");
            fileButtonExportTilesets.setInfoMessage("");
            fileButtonExportTilesets.setLabelText("Map tilesets :");
            fileButtonExportTilesets.setName("Export Tilesets Data"); // NOI18N

            fileButtonExportBlockset.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
            fileButtonExportBlockset.setFilePath("0-blocks.bin");
            fileButtonExportBlockset.setInfoMessage("");
            fileButtonExportBlockset.setLabelText("Map blockset :");
            fileButtonExportBlockset.setToolTipText("");
            fileButtonExportBlockset.setName("Export Blockset Data"); // NOI18N

            javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
            jPanel26.setLayout(jPanel26Layout);
            jPanel26Layout.setHorizontalGroup(
                jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel26Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel26Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton4))
                        .addComponent(fileButtonExportTilesets, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(fileButtonExportBlockset, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel26Layout.setVerticalGroup(
                jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel26Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(fileButtonExportTilesets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fileButtonExportBlockset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4))
                    .addContainerGap())
            );

            jTabbedPane2.addTab("Map", jPanel26);

            jLabel8.setText("<html>blockset data to a new image file and 'priority' flag data to text file.<br>Recommended to save as PNG or GIF.<br>Exported color format : 4BPP / 16 indexed colors.<br>Transparent color at index 0.</html>");
            jLabel8.setToolTipText("");
            jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

            jButtonExportBlockset.setText("Export");
            jButtonExportBlockset.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonExportBlocksetActionPerformed(evt);
                }
            });

            fileButtonExportBlocksetImage.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ANY_IMAGE);
            fileButtonExportBlocksetImage.setFilePath(".\\blockset.png");
            fileButtonExportBlocksetImage.setInfoMessage("<html>Exports an image of all of the blocks in the blockset (just like the 'blockset panel'.<br>Can be used with the Sf2MapCreator.</html>");
            fileButtonExportBlocksetImage.setLabelText("Image file :");
            fileButtonExportBlocksetImage.setName("Export Blockset Image"); // NOI18N

            fileButtonExportBlocksetPriorities.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.TXT);
            fileButtonExportBlocksetPriorities.setFilePath(".\\blocksethptiles.txt");
            fileButtonExportBlocksetPriorities.setInfoMessage("<html>Exports a file containing the priority flags for the blockset.</html>");
            fileButtonExportBlocksetPriorities.setLabelText("Block HP tiles :");
            fileButtonExportBlocksetPriorities.setName("Export Blockset Priorities"); // NOI18N

            javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
            jPanel28.setLayout(jPanel28Layout);
            jPanel28Layout.setHorizontalGroup(
                jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel28Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel28Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonExportBlockset))
                        .addComponent(fileButtonExportBlocksetImage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(fileButtonExportBlocksetPriorities, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel28Layout.setVerticalGroup(
                jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel28Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(fileButtonExportBlocksetImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fileButtonExportBlocksetPriorities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonExportBlockset)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );

            jTabbedPane2.addTab("Image", jPanel28);

            directoryButtonExportMap.setDirectoryPath(".\\entries\\map03\\");
                directoryButtonExportMap.setInfoMessage("");
                directoryButtonExportMap.setLabelText("Map dir :");
                directoryButtonExportMap.setName("Export Map"); // NOI18N

                javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
                jPanel17.setLayout(jPanel17Layout);
                jPanel17Layout.setHorizontalGroup(
                    jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(directoryButtonExportMap, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                );
                jPanel17Layout.setVerticalGroup(
                    jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(directoryButtonExportMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                );

                jTabbedPane2.getAccessibleContext().setAccessibleName("tab");

                javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
                jPanel31.setLayout(jPanel31Layout);
                jPanel31Layout.setHorizontalGroup(
                    jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel31Layout.setVerticalGroup(
                    jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel31Layout.createSequentialGroup()
                        .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                );

                jSplitPane3.setLeftComponent(jPanel31);

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Blocks"));
                jPanel1.setPreferredSize(new java.awt.Dimension(10, 300));

                jScrollPane3.setPreferredSize(new java.awt.Dimension(300, 300));

                javax.swing.GroupLayout mapBlocksetLayoutPanelLayout = new javax.swing.GroupLayout(mapBlocksetLayoutPanel);
                mapBlocksetLayoutPanel.setLayout(mapBlocksetLayoutPanelLayout);
                mapBlocksetLayoutPanelLayout.setHorizontalGroup(
                    mapBlocksetLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 452, Short.MAX_VALUE)
                );
                mapBlocksetLayoutPanelLayout.setVerticalGroup(
                    mapBlocksetLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 439, Short.MAX_VALUE)
                );

                jScrollPane3.setViewportView(mapBlocksetLayoutPanel);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                );

                jButtonAddBlock.setText("Add block");
                jButtonAddBlock.setMargin(new java.awt.Insets(2, 5, 3, 5));
                jButtonAddBlock.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonAddBlockActionPerformed(evt);
                    }
                });

                jButtonRemoveBlock.setText("Remove block");
                jButtonRemoveBlock.setToolTipText("");
                jButtonRemoveBlock.setMargin(new java.awt.Insets(2, 5, 3, 5));
                jButtonRemoveBlock.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonRemoveBlockActionPerformed(evt);
                    }
                });

                jButtonCloneBlock.setText("Clone selected");
                jButtonCloneBlock.setMargin(new java.awt.Insets(2, 5, 3, 5));
                jButtonCloneBlock.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonCloneBlockActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                    jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAddBlock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCloneBlock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRemoveBlock)
                        .addContainerGap())
                );
                jPanel7Layout.setVerticalGroup(
                    jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddBlock)
                            .addComponent(jButtonRemoveBlock)
                            .addComponent(jButtonCloneBlock)))
                );

                javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
                jPanel10.setLayout(jPanel10Layout);
                jPanel10Layout.setHorizontalGroup(
                    jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(blocksetViewPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel10Layout.setVerticalGroup(
                    jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blocksetViewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                );

                jSplitPane3.setRightComponent(jPanel10);

                javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
                jPanel30.setLayout(jPanel30Layout);
                jPanel30Layout.setHorizontalGroup(
                    jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 700, Short.MAX_VALUE)
                    .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane3))
                );
                jPanel30Layout.setVerticalGroup(
                    jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 594, Short.MAX_VALUE)
                    .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane3))
                );

                jSplitPane2.setLeftComponent(jPanel30);

                jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                jPanel9.setMinimumSize(new java.awt.Dimension(340, 200));
                jPanel9.setName(""); // NOI18N
                jPanel9.setPreferredSize(new java.awt.Dimension(340, 300));

                jScrollPane4.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Tileset"));

                javax.swing.GroupLayout tilesetsLayoutPanelLayout = new javax.swing.GroupLayout(tilesetsLayoutPanel);
                tilesetsLayoutPanel.setLayout(tilesetsLayoutPanelLayout);
                tilesetsLayoutPanelLayout.setHorizontalGroup(
                    tilesetsLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 778, Short.MAX_VALUE)
                );
                tilesetsLayoutPanelLayout.setVerticalGroup(
                    tilesetsLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 236, Short.MAX_VALUE)
                );

                jScrollPane4.setViewportView(tilesetsLayoutPanel);

                javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                jPanel9.setLayout(jPanel9Layout);
                jPanel9Layout.setHorizontalGroup(
                    jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(tilesetViewPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0))
                );
                jPanel9Layout.setVerticalGroup(
                    jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(tilesetViewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))
                );

                jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel3.setText("Selected block");

                editableBlockSlotPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
                editableBlockSlotPanel.setMaximumSize(new java.awt.Dimension(96, 96));
                editableBlockSlotPanel.setMinimumSize(new java.awt.Dimension(96, 96));
                editableBlockSlotPanel.setPreferredSize(new java.awt.Dimension(96, 96));

                javax.swing.GroupLayout editableBlockSlotPanelLayout = new javax.swing.GroupLayout(editableBlockSlotPanel);
                editableBlockSlotPanel.setLayout(editableBlockSlotPanelLayout);
                editableBlockSlotPanelLayout.setHorizontalGroup(
                    editableBlockSlotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 94, Short.MAX_VALUE)
                );
                editableBlockSlotPanelLayout.setVerticalGroup(
                    editableBlockSlotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 94, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
                jPanel22.setLayout(jPanel22Layout);
                jPanel22Layout.setHorizontalGroup(
                    jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(editableBlockSlotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(blockEditViewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                jPanel22Layout.setVerticalGroup(
                    jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editableBlockSlotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blockEditViewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                );

                jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

                jLabel22.setText("Left click");

                jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                jLabel30.setText("Right click");

                tileSlotPanelLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
                tileSlotPanelLeft.setMaximumSize(new java.awt.Dimension(32, 32));
                tileSlotPanelLeft.setMinimumSize(new java.awt.Dimension(32, 32));
                tileSlotPanelLeft.setPreferredSize(new java.awt.Dimension(32, 32));

                javax.swing.GroupLayout tileSlotPanelLeftLayout = new javax.swing.GroupLayout(tileSlotPanelLeft);
                tileSlotPanelLeft.setLayout(tileSlotPanelLeftLayout);
                tileSlotPanelLeftLayout.setHorizontalGroup(
                    tileSlotPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 30, Short.MAX_VALUE)
                );
                tileSlotPanelLeftLayout.setVerticalGroup(
                    tileSlotPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 30, Short.MAX_VALUE)
                );

                tileSlotPanelRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
                tileSlotPanelRight.setMaximumSize(new java.awt.Dimension(32, 32));
                tileSlotPanelRight.setMinimumSize(new java.awt.Dimension(32, 32));
                tileSlotPanelRight.setPreferredSize(new java.awt.Dimension(32, 32));

                javax.swing.GroupLayout tileSlotPanelRightLayout = new javax.swing.GroupLayout(tileSlotPanelRight);
                tileSlotPanelRight.setLayout(tileSlotPanelRightLayout);
                tileSlotPanelRightLayout.setHorizontalGroup(
                    tileSlotPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 30, Short.MAX_VALUE)
                );
                tileSlotPanelRightLayout.setVerticalGroup(
                    tileSlotPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 30, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
                jPanel23.setLayout(jPanel23Layout);
                jPanel23Layout.setHorizontalGroup(
                    jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(tileSlotPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                                .addComponent(tileSlotPanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))))
                );
                jPanel23Layout.setVerticalGroup(
                    jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tileSlotPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tileSlotPanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))
                );

                buttonGroupTileEditing.add(jRadioButtonApplyTile);
                jRadioButtonApplyTile.setSelected(true);
                jRadioButtonApplyTile.setText("Apply tile");
                jRadioButtonApplyTile.setActionCommand("Apply tiles");
                jRadioButtonApplyTile.setName("Tile Set Radio"); // NOI18N
                jRadioButtonApplyTile.addItemListener(new java.awt.event.ItemListener() {
                    public void itemStateChanged(java.awt.event.ItemEvent evt) {
                        jRadioButtonApplyTileItemStateChanged(evt);
                    }
                });

                buttonGroupTileEditing.add(jRadioButtonSetPriority);
                jRadioButtonSetPriority.setText("Toggle priority flag");
                jRadioButtonSetPriority.setName("Tile Set Priority Radio"); // NOI18N
                jRadioButtonSetPriority.addItemListener(new java.awt.event.ItemListener() {
                    public void itemStateChanged(java.awt.event.ItemEvent evt) {
                        jRadioButtonSetPriorityItemStateChanged(evt);
                    }
                });

                buttonGroupTileEditing.add(jRadioButtonFlipTile);
                jRadioButtonFlipTile.setText("Flip tiles");
                jRadioButtonFlipTile.setName("Tile Flip Radio"); // NOI18N
                jRadioButtonFlipTile.addItemListener(new java.awt.event.ItemListener() {
                    public void itemStateChanged(java.awt.event.ItemEvent evt) {
                        jRadioButtonFlipTileItemStateChanged(evt);
                    }
                });

                infoButton3.setMessageText("<html>Flip each tile in the selected block. Left click to toggle horizontal flip. Right click to toggle vertical flip. Middle click to clear any flipping.</html>");
                infoButton3.setText("");

                infoButton4.setMessageText("<html>Set the priority flag for each tile. Left-click to set. Right-click to unset.<br>'Priority' means that the tile is drawn above the mapSprites (i.e. above characters).<br>Examples include roof tiles or the top tiles for a wall or table.</html>");
                infoButton4.setText("");

                infoButton5.setMessageText("<html> 'Paint' the selected tiles (left or right click) to the selected block.<br>Use left or right click to select a tile above then left or right click on the <i>Selected block</i> panel to apply</html>");
                infoButton5.setText("");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonApplyTile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonFlipTile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonSetPriority)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(infoButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonApplyTile))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jRadioButtonFlipTile)
                                    .addComponent(infoButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(infoButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonSetPriority))
                                .addGap(0, 40, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, 0))
                );

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                    jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(101, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                        .addContainerGap())
                );
                jPanel6Layout.setVerticalGroup(
                    jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))
                );

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                    jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel4Layout.setVerticalGroup(
                    jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jSplitPane2.setRightComponent(jPanel4);

                javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
                jPanel15.setLayout(jPanel15Layout);
                jPanel15Layout.setHorizontalGroup(
                    jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane2)
                );
                jPanel15Layout.setVerticalGroup(
                    jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jSplitPane2)
                        .addContainerGap())
                );

                jSplitPane1.setTopComponent(jPanel15);
                jSplitPane1.setBottomComponent(console1);

                javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
                jPanel13.setLayout(jPanel13Layout);
                jPanel13Layout.setHorizontalGroup(
                    jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                );
                jPanel13Layout.setVerticalGroup(
                    jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                setSize(new java.awt.Dimension(1177, 751));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void jButtonImportDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportDataActionPerformed
        Path palettePath = PathHelpers.getBasePath().resolve(fileButtonPalette.getFilePath());
        Path blocksPath = PathHelpers.getBasePath().resolve(fileButtonBlocks.getFilePath());
        Path tilesetPath1 = PathHelpers.getBasePath().resolve(fileButtonTileset1.getFilePath());
        Path tilesetPath2 = PathHelpers.getBasePath().resolve(fileButtonTileset2.getFilePath());
        Path tilesetPath3 = PathHelpers.getBasePath().resolve(fileButtonTileset3.getFilePath());
        Path tilesetPath4 = PathHelpers.getBasePath().resolve(fileButtonTileset4.getFilePath());
        Path tilesetPath5 = PathHelpers.getBasePath().resolve(fileButtonTileset5.getFilePath());
        try {
            mapblockManager.importDisassembly(palettePath, new Path[] { tilesetPath1, tilesetPath2, tilesetPath3, tilesetPath4, tilesetPath5 }, blocksPath);
        } catch (Exception ex) {
            mapblockManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Map blockset disasm could not be imported from : " + blocksPath);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportDataActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Path mapDirectory = PathHelpers.getBasePath().resolve(directoryButtonExportMap.getDirectoryPath());
        Path mapTilesetDataPath = mapDirectory.resolve(fileButtonExportTilesets.getFilePath());
        Path mapBlocksetDataPath = mapDirectory.resolve(fileButtonExportBlockset.getFilePath());
        if (!PathHelpers.createPathIfRequred(mapDirectory)) return;
        try {
            mapblockManager.exportDisassembly(mapTilesetDataPath, mapBlocksetDataPath, mapBlocksetLayoutPanel.getBlockset(), tilesetsLayoutPanel.getTilesets());
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Map block disasm could not be exported to : " + mapDirectory);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonImportDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportDirectoryActionPerformed
        Path mapDirectory = PathHelpers.getBasePath().resolve(directoryButtonImportMap.getDirectoryPath());
        Path paletteEntriesPath = PathHelpers.getBasePath().resolve(fileButtonPaletteEntries.getFilePath());
        Path tilesetEntriesPath = PathHelpers.getBasePath().resolve(fileButtonTilesetEntries.getFilePath());
        Path mapTilesetDataPath = mapDirectory.resolve(fileButtonTilesets.getFilePath());
        Path mapBlocksetDataPath = mapDirectory.resolve(fileButtonBlockset.getFilePath());
        try {
            mapblockManager.importDisassemblyFromEntries(paletteEntriesPath, tilesetEntriesPath, mapTilesetDataPath, mapBlocksetDataPath);
        } catch (Exception ex) {
            mapblockManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Map blockset disasm could not be imported from : " + mapDirectory);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportDirectoryActionPerformed
    
    private void jButtonAddBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBlockActionPerformed
        if (mapBlocksetLayoutPanel.getBlockset() == null) return;
        MapBlockset blockset = mapBlocksetLayoutPanel.getBlockset();
        MapBlock block = null;
        int index = editableBlockSlotPanel.getBlockIndex();
        if (index >= 0 && index <= 2) {
            Console.logger().warning("WARNING Cannot insert map blocks before first 3 slots.");
            return;
        }
        if (index < 0 || index >= blockset.getBlocks().length-1) {
            index = blockset.getBlocks().length;
            block = blockset.getBlocks()[3];
        } else {
            index++;
            block = blockset.getBlocks()[0];
        }
        BlockChangeActionData data = new BlockChangeActionData(block, index);
        ActionManager.setAndExecuteAction(new CustomAction<BlockChangeActionData>(this, "Add Block", this::actionAddBlock, data, this::actionRemoveBlock, data));
    }//GEN-LAST:event_jButtonAddBlockActionPerformed
    
    private void jButtonRemoveBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveBlockActionPerformed
        if (mapBlocksetLayoutPanel.getBlockset() == null) return;
        MapBlockset blockset = mapBlocksetLayoutPanel.getBlockset();
        int index = editableBlockSlotPanel.getBlockIndex();
        if (index < 0) return;
        if (index <= 2) {
            Console.logger().warning("WARNING Cannot delete first 3 map blocks.");
            return;
        }
        MapBlock block = blockset.getBlocks()[index];
        BlockChangeActionData data = new BlockChangeActionData(block, index);
        ActionManager.setAndExecuteAction(new CustomAction<BlockChangeActionData>(this, "Remove Block", this::actionRemoveBlock, data, this::actionAddBlock, data));
    }//GEN-LAST:event_jButtonRemoveBlockActionPerformed
    
    private void jButtonExportBlocksetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportBlocksetActionPerformed
        Path mapDirectory = PathHelpers.getBasePath().resolve(directoryButtonExportMap.getDirectoryPath());
        Path blocksetImagePath = mapDirectory.resolve(fileButtonExportBlocksetImage.getFilePath());
        Path hpTilesPath = mapDirectory.resolve(fileButtonExportBlocksetPriorities.getFilePath());
        if (!PathHelpers.createPathIfRequred(mapDirectory)) return;
        try {
            mapblockManager.exportImage(blocksetImagePath, hpTilesPath, mapBlocksetLayoutPanel.getItemsPerRow(), mapBlocksetLayoutPanel.getBlockset(), mapBlocksetLayoutPanel.getTilesets());
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Map image & priority data could not be exported to : " + mapDirectory);
        }
    }//GEN-LAST:event_jButtonExportBlocksetActionPerformed

    private void jButtonCloneBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloneBlockActionPerformed
        if (mapBlocksetLayoutPanel.getBlockset() == null) return;
        MapBlockset blockset = mapBlocksetLayoutPanel.getBlockset();
        int index = editableBlockSlotPanel.getBlockIndex();
        if (index < 0 || index >= blockset.getBlocks().length) return;
        if (index <= 2) {
            Console.logger().warning("WARNING Cannot clone from first 3 map slots.");
            return;
        }
        MapBlock block = blockset.getBlocks()[index];
        BlockChangeActionData data = new BlockChangeActionData(block, index+1);
        ActionManager.setAndExecuteAction(new CustomAction<BlockChangeActionData>(this, "Clone Block", this::actionAddBlock, data, this::actionRemoveBlock, data));
    }//GEN-LAST:event_jButtonCloneBlockActionPerformed

    private void jRadioButtonApplyTileItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonApplyTileItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new RadioButtonAction(buttonGroupTileEditing, jRadioButtonApplyTile, actionTileButton));
        }
        EditableBlockSlotPanel blockSlot = tilesetsLayoutPanel.getBlockSlotPanel();
        if (blockSlot != null) {
            blockSlot.setCurrentMode(EditableBlockSlotPanel.BlockSlotEditMode.MODE_PAINT_TILE);
            blockSlot.setShowPriority(blockEditViewPanel1.getPriorityCheckBox().isSelected());
        }
        if (jRadioButtonApplyTile.isSelected()) {
            actionTileButton = jRadioButtonApplyTile;
        }
    }//GEN-LAST:event_jRadioButtonApplyTileItemStateChanged

    private void jRadioButtonFlipTileItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonFlipTileItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new RadioButtonAction(buttonGroupTileEditing, jRadioButtonFlipTile, actionTileButton));
        }
        EditableBlockSlotPanel blockSlot = tilesetsLayoutPanel.getBlockSlotPanel();
        if (blockSlot != null) {
            blockSlot.setCurrentMode(EditableBlockSlotPanel.BlockSlotEditMode.MODE_TOGGLE_FLIP);
            blockSlot.setShowPriority(blockEditViewPanel1.getPriorityCheckBox().isSelected());
        }
        if (jRadioButtonFlipTile.isSelected()) {
            actionTileButton = jRadioButtonFlipTile;
        }
    }//GEN-LAST:event_jRadioButtonFlipTileItemStateChanged

    private void jRadioButtonSetPriorityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonSetPriorityItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new RadioButtonAction(buttonGroupTileEditing, jRadioButtonSetPriority, actionTileButton));
        }
        EditableBlockSlotPanel blockSlot = tilesetsLayoutPanel.getBlockSlotPanel();
        if (blockSlot != null) {
            blockSlot.setCurrentMode(EditableBlockSlotPanel.BlockSlotEditMode.MODE_TOGGLE_PRIORITY);
            blockSlot.setShowPriority(true);
        }
        if (jRadioButtonSetPriority.isSelected()) {
            actionTileButton = jRadioButtonSetPriority;
        }
    }//GEN-LAST:event_jRadioButtonSetPriorityItemStateChanged

    private void actionAddBlock(BlockChangeActionData data) {   
        MapBlockset blockset = mapBlocksetLayoutPanel.getBlockset();                                        
        blockset.insertBlock(data.index(), data.block());
        mapBlocksetLayoutPanel.setLeftSelectedIndex(data.index());
        if (data.index() == blockset.getBlocks().length-1) { //Scroll to bottom
            mapBlocksetLayoutPanel.centerOnMapPoint(Integer.MAX_VALUE, Integer.MAX_VALUE);
        } else {
            //TODO focus on seleted
            //mapBlocksetLayoutPanel.centerOnMapPoint(Integer.MAX_VALUE, Integer.MAX_VALUE);
        }
    }
    
    private void actionRemoveBlock(BlockChangeActionData data) {
        MapBlockset blockset = mapBlocksetLayoutPanel.getBlockset();
        blockset.removeBlock(data.index());
        mapBlocksetLayoutPanel.setLeftSelectedIndex(data.index() <= 3 ? 3 : data.index()-1);
    }
    
    private void onBlockEdited(ActionEvent e) {
        mapBlocksetLayoutPanel.getBlockset().clearIndexedColorImage(false);
        mapBlocksetLayoutPanel.redraw();
    }
    
    /**
     * To create a new Main Editor, copy the below code
     * Don't forget to change the new main class (below)
     */
    public static void main(String args[]) {
        AbstractMainEditor.programSetup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapBlockMainEditor().setVisible(true);  // <------ Change this class to new Main Editor class
            }
        });
    }
    /**
     * To create a new Main Editor, copy the above code
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.AccordionPanel accordionPanel1;
    private com.sfc.sf2.map.block.gui.BlockEditViewPanel blockEditViewPanel1;
    private com.sfc.sf2.map.block.gui.BlocksetViewPanel blocksetViewPanel1;
    private com.sfc.sf2.core.gui.controls.NameableButtonGroup buttonGroupTileEditing;
    private com.sfc.sf2.core.gui.controls.Console console1;
    private com.sfc.sf2.core.gui.controls.DirectoryButton directoryButtonExportMap;
    private com.sfc.sf2.core.gui.controls.DirectoryButton directoryButtonImportMap;
    private com.sfc.sf2.map.block.gui.EditableBlockSlotPanel editableBlockSlotPanel;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonBlocks;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonBlockset;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportBlockset;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportBlocksetImage;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportBlocksetPriorities;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportTilesets;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonPalette;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonPaletteEntries;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonTileset1;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonTileset2;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonTileset3;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonTileset4;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonTileset5;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonTilesetEntries;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonTilesets;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton3;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton4;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton5;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAddBlock;
    private javax.swing.JButton jButtonCloneBlock;
    private javax.swing.JButton jButtonExportBlockset;
    private javax.swing.JButton jButtonImportData;
    private javax.swing.JButton jButtonImportDirectory;
    private javax.swing.JButton jButtonRemoveBlock;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonApplyTile;
    private javax.swing.JRadioButton jRadioButtonFlipTile;
    private javax.swing.JRadioButton jRadioButtonSetPriority;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.sfc.sf2.map.block.gui.MapBlocksetLayoutPanel mapBlocksetLayoutPanel;
    private com.sfc.sf2.map.block.gui.TileSlotPanel tileSlotPanelLeft;
    private com.sfc.sf2.map.block.gui.TileSlotPanel tileSlotPanelRight;
    private com.sfc.sf2.map.block.gui.TilesetViewPanel tilesetViewPanel1;
    private com.sfc.sf2.map.block.gui.TilesetsLayoutPanel tilesetsLayoutPanel;
    // End of variables declaration//GEN-END:variables
}
