/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sfc.sf2.battlesprite.gui;

import com.sfc.sf2.battlesprite.BattleSprite;
import com.sfc.sf2.battlesprite.BattleSpriteManager;
import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.NonCombinableAction;
import com.sfc.sf2.core.actions.RadioButtonAction;
import com.sfc.sf2.core.actions.SpinnerAction;
import com.sfc.sf2.core.actions.ToggleAction;
import com.sfc.sf2.core.gui.AbstractMainEditor;
import com.sfc.sf2.core.gui.controls.Console;
import com.sfc.sf2.core.io.FileFormat;
import com.sfc.sf2.core.settings.SettingsManager;
import com.sfc.sf2.core.settings.ViewSettings;
import com.sfc.sf2.graphics.settings.ExportSettings;
import com.sfc.sf2.helpers.PathHelpers;
import com.sfc.sf2.helpers.RenderScaleHelpers;
import java.nio.file.Path;
import java.util.logging.Level;
import javax.swing.JRadioButton;

/**
 *
 * @author wiz
 */
public class BattleSpriteMainEditor extends AbstractMainEditor {
    
    private final ViewSettings viewSettings = new ViewSettings(RenderScaleHelpers.RENDER_SCALE_2X);
    private final ExportSettings exportSettings = new ExportSettings();
    private final BattleSpriteManager battleSpriteManager = new BattleSpriteManager();
    
    private boolean actionExportFormat = false;
    
    public BattleSpriteMainEditor() {
        super();
        SettingsManager.registerSettingsStore("view", viewSettings);
        SettingsManager.registerSettingsStore("export", exportSettings);
        initComponents();
        initCore(console1);
    }
    
    @Override
    protected void initEditor() {
        super.initEditor();
        
        viewPanel1.setLayoutPanel(battleSpriteLayoutPanel, viewSettings);
        
        jRadioButtonFormatPNG.setSelected(exportSettings.getExportFileFormat() == FileFormat.PNG);
        jRadioButtonFormatGIF.setSelected(exportSettings.getExportFileFormat() != FileFormat.PNG);
        actionExportFormat = jRadioButtonFormatPNG.isSelected();
    }
    
    @Override
    protected void onDataLoaded() {
        super.onDataLoaded();
        ActionManager.setAndExecuteAction(new NonCombinableAction<BattleSprite>(this, "Battlesprite Imported", this::actionBattlespriteLoaded, battleSpriteManager.getBattleSprite(), battleSpriteLayoutPanel.getBattleSprite()));
    }
    
    private void actionBattlespriteLoaded(BattleSprite battleSprite) {
        battleSpriteLayoutPanel.setBattleSprite(battleSprite);
        battleSpriteLayoutPanel.getAnimator().stopAnimation();
        jCheckBoxPreviewIdle.setSelected(false);
        viewPanel1.setPalettesList(battleSprite);
        if (battleSprite != null) {
            jSpinnerIdleSpeed.setValue(battleSprite.getAnimSpeed());
            jSpinnerStatusX.setValue(battleSprite.getStatusOffsetX());
            jSpinnerStatusY.setValue(battleSprite.getStatusOffsetY());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupExport = new com.sfc.sf2.core.gui.controls.NameableButtonGroup();
        jPanel13 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel15 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        infoButton3 = new com.sfc.sf2.core.gui.controls.InfoButton();
        fileButtonImportBattlesprite = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonImportBattlesprite = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        infoButton5 = new com.sfc.sf2.core.gui.controls.InfoButton();
        fileButtonImportImage = new com.sfc.sf2.core.gui.controls.FileButton();
        jCheckBoxUseImagePalette = new javax.swing.JCheckBox();
        infoButton6 = new com.sfc.sf2.core.gui.controls.InfoButton();
        jButtonImportImage = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fileButtonExportBattlesprite = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonExportBattlesprite = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        infoButton8 = new com.sfc.sf2.core.gui.controls.InfoButton();
        fileButtonExportImages = new com.sfc.sf2.core.gui.controls.FileButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonFormatPNG = new javax.swing.JRadioButton();
        jRadioButtonFormatGIF = new javax.swing.JRadioButton();
        infoButton7 = new com.sfc.sf2.core.gui.controls.InfoButton();
        jButtonExportImages = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        battleSpriteLayoutPanel = new com.sfc.sf2.battlesprite.gui.BattleSpriteLayoutPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBoxPreviewIdle = new javax.swing.JCheckBox();
        jCheckBoxShowStatus = new javax.swing.JCheckBox();
        jSpinnerStatusY = new javax.swing.JSpinner();
        jSpinnerStatusX = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSpinnerIdleSpeed = new javax.swing.JSpinner();
        infoButton1 = new com.sfc.sf2.core.gui.controls.InfoButton();
        infoButton2 = new com.sfc.sf2.core.gui.controls.InfoButton();
        viewPanel1 = new com.sfc.sf2.battlesprite.gui.BattlespriteViewPanel();
        console1 = new com.sfc.sf2.core.gui.controls.Console();

        buttonGroupExport.setName("Export Button Group");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SF2BattleSpriteManager");
        setPreferredSize(new java.awt.Dimension(750, 700));

        jSplitPane1.setDividerLocation(550);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);

        jSplitPane2.setDividerLocation(350);
        jSplitPane2.setOneTouchExpandable(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Import from :"));
        jPanel3.setPreferredSize(new java.awt.Dimension(590, 135));

        jLabel2.setText("Import a Battlesprite disassembly.");

        infoButton3.setMessageText("<html>Typical disassembly \\battlesprites\\allies\\ and \\battlesprites\\enemies\\</html>");
        infoButton3.setText("");

        fileButtonImportBattlesprite.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonImportBattlesprite.setFilePath(".\\allies\\allybattlesprite01.bin");
        fileButtonImportBattlesprite.setInfoMessage("");
        fileButtonImportBattlesprite.setLabelText("File :");
        fileButtonImportBattlesprite.setName("Import Battlesprites"); // NOI18N

        jButtonImportBattlesprite.setText("Import");
        jButtonImportBattlesprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportBattlespriteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonImportBattlesprite, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonImportBattlesprite))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportBattlesprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImportBattlesprite)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Disassembly", jPanel4);

        jLabel3.setText("Import battlesprite from images.");

        infoButton5.setMessageText("<html>Enter an image prefix or select an image, palette, or meta file. Examples of valid search patterns:<br>- .\\allies\\export\\allybattlesprite01<br>- .\\allies\\export\\allybattlesprite01-frame<br>- .\\allies\\export\\allybattlesprite01-frame-0<br>- .\\allies\\export\\allybattlesprite01-frame-3.png<br>- .\\allies\\export\\allybattlesprite01.meta<br>- .\\allies\\export\\allybattlesprite01-palette<br>- .\\allies\\export\\allybattlesprite01-palette-0.bin<br><br>Supported image formats: PNG or GIF. Automatically detects valid image formats that match the file pattern.<br><br>Color format should be 4BPP / 16 indexed colors. Images of 8BPP / 256 indexed colors will be converted to 4 BPP / 16 (some colors may be lost).<br>Colors will be convered to CRAM format (the color format used by the SEGA Genesis).<br>Color index 0 is treated as transparent.</html>");
        infoButton5.setText("");

        fileButtonImportImage.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ALL_BATTLE_SPRITES_FORMAT);
        fileButtonImportImage.setFilePath(".\\allies\\export\\allybattlesprite01");
        fileButtonImportImage.setInfoMessage("");
        fileButtonImportImage.setLabelText("Image prefix :");
        fileButtonImportImage.setName("Import Images"); // NOI18N

        jCheckBoxUseImagePalette.setText("Use image palette as 1st palette");
        jCheckBoxUseImagePalette.setActionCommand("");

        infoButton6.setMessageText("<html>Uses the colors from the imported image as the 1st palette (palette0). Image colors will be converted to CRAM color format.</html>");
        infoButton6.setText("");

        jButtonImportImage.setText("Import");
        jButtonImportImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBoxUseImagePalette)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonImportImage))
                    .addComponent(fileButtonImportImage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonImportImage)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(infoButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBoxUseImagePalette)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Image", jPanel9);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Export to :"));
        jPanel5.setPreferredSize(new java.awt.Dimension(32, 135));

        jLabel1.setText("<html>Export battlesprite disassembly.</html>");

        fileButtonExportBattlesprite.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonExportBattlesprite.setFilePath(".\\allies\\allybattlesprite01.bin");
        fileButtonExportBattlesprite.setInfoMessage("");
        fileButtonExportBattlesprite.setLabelText("File :");
        fileButtonExportBattlesprite.setName("Export Battlesprites"); // NOI18N

        jButtonExportBattlesprite.setText("Export");
        jButtonExportBattlesprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportBattlespriteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonExportBattlesprite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonExportBattlesprite))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonExportBattlesprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExportBattlesprite)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Disassembly", jPanel11);

        jLabel9.setText("Export battlesprite to images.");

        infoButton8.setMessageText("<html>Enter an image prefix or select an image, palette, or meta file. Examples of valid search patterns:<br>- .\\allies\\export\\allybattlesprite01<br>- .\\allies\\export\\allybattlesprite01-frame<br>- .\\allies\\export\\allybattlesprite01-frame-0<br>- .\\allies\\export\\allybattlesprite01-frame-3.png<br>- .\\allies\\export\\allybattlesprite01.meta<br>- .\\allies\\export\\allybattlesprite01-palette<br>- .\\allies\\export\\allybattlesprite01-palette-0.bin<br><br>Supported image formats: PNG or GIF.<br><br>Exported color format will be 4BPP / 16 indexed colors.<br>Color index 0 is treated as transparent.</html>");
        infoButton8.setText("");

        fileButtonExportImages.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ALL_BATTLE_SPRITES_FORMAT);
        fileButtonExportImages.setFilePath(".\\allies\\export\\allybattlesprite01");
        fileButtonExportImages.setInfoMessage("<html>Exports the Battlesprite as:<br>- Multiple image files (one per frame) with naming pattern \"battlespriteXX-frame-Y.png).<br>- 1 or more Palette data files (one for each Palette used by the Battlesprite) with naming pattern \"battlespriteXX-palette-Y.bin).<br>- A metadata file with naming pattern \"battlespriteXX.meta\".<br><br><html>Examples of valid search patterns:<br>- .\\allies\\export\\allybattlesprite01<br>- .\\allies\\export\\allybattlesprite01-frame<br>- .\\allies\\export\\allybattlesprite01-frame-0<br>- .\\allies\\export\\allybattlesprite01-frame-3.png<br>- .\\allies\\export\\allybattlesprite01.meta<br>- .\\allies\\export\\allybattlesprite01-palette<br>- .\\allies\\export\\allybattlesprite01-palette-0.bin<br><br>Supported image formats: PNG or GIF.<br><br>Exported color format will be 4BPP / 16 indexed colors.<br>Color index 0 is treated as transparent.</html>");
        fileButtonExportImages.setLabelText("Path prefix :");
        fileButtonExportImages.setName("Export Images"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setText("File format :");

        jRadioButtonFormatPNG.setSelected(true);
        jRadioButtonFormatPNG.setText("PNG");
        jRadioButtonFormatPNG.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonFormatRadioItemStateChanged(evt);
            }
        });

        jRadioButtonFormatGIF.setText("GIF");
        jRadioButtonFormatGIF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonFormatRadioItemStateChanged(evt);
            }
        });

        infoButton7.setMessageText("Export the images as .PNG or .GIF format.");
        infoButton7.setText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonFormatPNG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonFormatGIF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(infoButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonFormatGIF)
                    .addComponent(jRadioButtonFormatPNG)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonExportImages.setText("Export");
        jButtonExportImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportImagesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonExportImages, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExportImages))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonExportImages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExportImages)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Image", jPanel14);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane2.setLeftComponent(jPanel8);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Frames"));

        javax.swing.GroupLayout battleSpriteLayoutPanelLayout = new javax.swing.GroupLayout(battleSpriteLayoutPanel);
        battleSpriteLayoutPanel.setLayout(battleSpriteLayoutPanelLayout);
        battleSpriteLayoutPanelLayout.setHorizontalGroup(
            battleSpriteLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        battleSpriteLayoutPanelLayout.setVerticalGroup(
            battleSpriteLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(battleSpriteLayoutPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Properties"));

        jLabel5.setText("Idle anim speed :");

        jLabel6.setText("Status marker offset :");

        jCheckBoxPreviewIdle.setText("Preview");
        jCheckBoxPreviewIdle.setName("Anim Preview"); // NOI18N
        jCheckBoxPreviewIdle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxPreviewIdleItemStateChanged(evt);
            }
        });

        jCheckBoxShowStatus.setText("Show");
        jCheckBoxShowStatus.setName("Show Status Marker"); // NOI18N
        jCheckBoxShowStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxShowStatusItemStateChanged(evt);
            }
        });

        jSpinnerStatusY.setModel(new javax.swing.SpinnerNumberModel((byte)0, (byte)0, null, (byte)1));
        jSpinnerStatusY.setName("Status Marker Y"); // NOI18N
        jSpinnerStatusY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerStatusYStateChanged(evt);
            }
        });

        jSpinnerStatusX.setModel(new javax.swing.SpinnerNumberModel((byte)0, (byte)0, null, (byte)1));
        jSpinnerStatusX.setName("Status Marker X"); // NOI18N
        jSpinnerStatusX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerStatusXStateChanged(evt);
            }
        });

        jLabel22.setText("X :");

        jLabel23.setText("Y :");

        jSpinnerIdleSpeed.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerIdleSpeed.setName("Idle Anim Speed"); // NOI18N
        jSpinnerIdleSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIdleSpeedStateChanged(evt);
            }
        });

        infoButton1.setMessageText("<html><b>Idle anim speed :</b> The rate that the idle anim (first 2 frames) updates.<br>60 = 1 second. Lower is faster.</html>");
        infoButton1.setText("");

        infoButton2.setMessageText("<html><b>Status marker offset :</b> Indicates where the status effects will be drawn from (e.g. sleep effect).<br>X,Y offset from the frame top-left corner of the battlesprite.<br>Should generally be placed around the head of the idle battlesprite.<br><br><b>INFO :</b> You can click and drag on the battle sprite to move the status marker.</html>");
        infoButton2.setText("");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(infoButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerIdleSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxPreviewIdle))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(infoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerStatusX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerStatusY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxShowStatus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSpinnerIdleSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCheckBoxPreviewIdle)
                    .addComponent(infoButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(infoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerStatusY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerStatusX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addComponent(jCheckBoxShowStatus)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(viewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(jPanel10);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        jSplitPane1.setTopComponent(jPanel15);
        jSplitPane1.setBottomComponent(console1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(921, 737));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExportBattlespriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportBattlespriteActionPerformed
        Path spritePath = PathHelpers.getBasePath().resolve(fileButtonExportBattlesprite.getFilePath());
        if (!PathHelpers.createPathIfRequred(spritePath)) return;
        try {
            battleSpriteManager.exportDisassembly(spritePath, battleSpriteLayoutPanel.getBattleSprite());
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Battle Sprite disasm could not be exported to : " + spritePath);
        }
    }//GEN-LAST:event_jButtonExportBattlespriteActionPerformed

    private void jButtonExportImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportImagesActionPerformed
        Path imagePath = PathHelpers.getBasePath().resolve(fileButtonExportImages.getFilePath());
        if (imagePath.getFileName().toString().contains(".")) {
            if (!PathHelpers.createPathIfRequred(imagePath)) return;
        } else {
            if (!PathHelpers.createPathIfRequred(imagePath.getParent())) return;
        }
        try {
            FileFormat format = jRadioButtonFormatPNG.isSelected() ? FileFormat.PNG : FileFormat.GIF;
            battleSpriteManager.exportImage(imagePath, battleSpriteLayoutPanel.getBattleSprite(), battleSpriteLayoutPanel.getBattleSprite().getCurrentPaletteIndex(), format);
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Battle Sprite image could not be exported to : " + imagePath);
        }
    }//GEN-LAST:event_jButtonExportImagesActionPerformed

    private void jButtonImportImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportImageActionPerformed
        Path spritePath = PathHelpers.getBasePath().resolve(fileButtonImportImage.getFilePath());
        boolean useImagePalette = jCheckBoxUseImagePalette.isSelected();
        try {
            battleSpriteManager.importImage(spritePath, useImagePalette);
        } catch (Exception ex) {
            battleSpriteManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Battle Sprite image could not be imported from : " + spritePath);
        }
        onDataLoaded();
        if (useImagePalette && battleSpriteManager.getBattleSprite() != null) {
            viewPanel1.getjComboBoxPalette().setSelectedIndex(battleSpriteManager.getBattleSprite().getPalettes().length-1);
        }
    }//GEN-LAST:event_jButtonImportImageActionPerformed

    private void jButtonImportBattlespriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportBattlespriteActionPerformed
        Path imagePath = PathHelpers.getBasePath().resolve(fileButtonImportBattlesprite.getFilePath());
        try {
            battleSpriteManager.importDisassembly(imagePath);
        } catch (Exception ex) {
            battleSpriteManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Battle Sprite disasm could not be imported from : " + imagePath);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportBattlespriteActionPerformed

    private void jSpinnerIdleSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIdleSpeedStateChanged
        BattleSprite battleSprite = battleSpriteManager.getBattleSprite();
        if (battleSprite == null) return;
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new SpinnerAction(jSpinnerIdleSpeed, jSpinnerIdleSpeed.getValue(), battleSprite.getAnimSpeed()));
        }
        battleSprite.setAnimSpeed((int)jSpinnerIdleSpeed.getValue());
        if (battleSpriteLayoutPanel.getAnimator().isAnimating()) {
            battleSpriteLayoutPanel.getAnimator().stopAnimation();
            battleSpriteLayoutPanel.getAnimator().startAnimation(battleSprite.getAnimSpeed(), 1, true);
        }
    }//GEN-LAST:event_jSpinnerIdleSpeedStateChanged

    private void jSpinnerStatusXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerStatusXStateChanged
        BattleSprite battleSprite = battleSpriteManager.getBattleSprite();
        if (battleSprite == null) return;
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new SpinnerAction(jSpinnerStatusX, jSpinnerStatusX.getValue(), battleSprite.getStatusOffsetX()));
        }
        battleSprite.setStatusOffsetX((byte)jSpinnerStatusX.getValue());
        if (jCheckBoxShowStatus.isSelected()) {
            battleSpriteLayoutPanel.redraw();
        }
    }//GEN-LAST:event_jSpinnerStatusXStateChanged

    private void jSpinnerStatusYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerStatusYStateChanged
        BattleSprite battleSprite = battleSpriteManager.getBattleSprite();
        if (battleSprite == null) return;
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new SpinnerAction(jSpinnerStatusY, jSpinnerStatusY.getValue(), battleSprite.getStatusOffsetY()));
        }
        battleSprite.setStatusOffsetY((byte)jSpinnerStatusY.getValue());
        if (jCheckBoxShowStatus.isSelected()) {
            battleSpriteLayoutPanel.redraw();
        }
    }//GEN-LAST:event_jSpinnerStatusYStateChanged

    private void jRadioButtonFormatRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonFormatRadioItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            JRadioButton previous = actionExportFormat ? jRadioButtonFormatPNG : jRadioButtonFormatGIF;
            ActionManager.setActionWithoutExecute(new RadioButtonAction(buttonGroupExport, (JRadioButton)evt.getSource(), previous));
        }
        actionExportFormat = jRadioButtonFormatPNG.isSelected();

        if (actionExportFormat) {
            exportSettings.setExportFileFormat(actionExportFormat ? FileFormat.PNG : FileFormat.GIF);
            SettingsManager.saveSettingsFile();
        }
    }//GEN-LAST:event_jRadioButtonFormatRadioItemStateChanged

    private void jCheckBoxPreviewIdleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxPreviewIdleItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxPreviewIdle, jCheckBoxPreviewIdle.isSelected()));
        }
        BattleSprite battleSprite = battleSpriteLayoutPanel.getBattleSprite();
        if (battleSprite != null) {
            if (jCheckBoxPreviewIdle.isSelected()) {
                battleSpriteLayoutPanel.getAnimator().startAnimation(battleSprite.getAnimSpeed(), 1, true);
            } else {
                battleSpriteLayoutPanel.getAnimator().stopAnimation();
                battleSpriteLayoutPanel.redraw();
            }
        }
    }//GEN-LAST:event_jCheckBoxPreviewIdleItemStateChanged

    private void jCheckBoxShowStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxShowStatusItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxShowStatus, jCheckBoxShowStatus.isSelected()));
        }
        battleSpriteLayoutPanel.setShowStatusMarker(jCheckBoxShowStatus.isSelected());
    }//GEN-LAST:event_jCheckBoxShowStatusItemStateChanged

    /**
     * To create a new Main Editor, copy the below code
     * Don't forget to change the new main class (below)
     */
    public static void main(String args[]) {
        AbstractMainEditor.programSetup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleSpriteMainEditor().setVisible(true);  // <------ Change this class to new Main Editor class
            }
        });
    }
    /**
     * To create a new Main Editor, copy the above code
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.battlesprite.gui.BattleSpriteLayoutPanel battleSpriteLayoutPanel;
    private com.sfc.sf2.core.gui.controls.NameableButtonGroup buttonGroupExport;
    private com.sfc.sf2.core.gui.controls.Console console1;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportBattlesprite;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportImages;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportBattlesprite;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportImage;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton1;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton2;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton3;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton5;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton6;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton7;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton8;
    private javax.swing.JButton jButtonExportBattlesprite;
    private javax.swing.JButton jButtonExportImages;
    private javax.swing.JButton jButtonImportBattlesprite;
    private javax.swing.JButton jButtonImportImage;
    private javax.swing.JCheckBox jCheckBoxPreviewIdle;
    private javax.swing.JCheckBox jCheckBoxShowStatus;
    private javax.swing.JCheckBox jCheckBoxUseImagePalette;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonFormatGIF;
    private javax.swing.JRadioButton jRadioButtonFormatPNG;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerIdleSpeed;
    private javax.swing.JSpinner jSpinnerStatusX;
    private javax.swing.JSpinner jSpinnerStatusY;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.sfc.sf2.battlesprite.gui.BattlespriteViewPanel viewPanel1;
    // End of variables declaration//GEN-END:variables

}
