/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.core.gui.controls;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.BasicAction;
import com.sfc.sf2.helpers.PathHelpers;
import java.beans.BeanProperty;
import java.io.File;
import java.nio.file.Path;
import javax.swing.Icon;
import javax.swing.JFileChooser;

/**
 *
 * @author TiMMy
 */
public class DirectoryButton extends javax.swing.JPanel {
        
    /**
     * Creates new form FileButton
     */
    public DirectoryButton() {
        initComponents();
    }

    @Override
    public void setEnabled(boolean enabled) {
        jTextFieldPath.setEnabled(enabled);
        jButtonPath.setEnabled(enabled);
    }
    
    public String getLabelText() {
        return jLabelFile.getText();
    }
    
    @BeanProperty(preferred = true, visualUpdate = true, description = "Defines the single line of text for the label.")
    public void setLabelText(String text) {
        jLabelFile.setText(text);
    }
    
    public String getDirectoryPath() {
        return jTextFieldPath.getText();
    }
    
    @BeanProperty(preferred = true, visualUpdate = true, description = "The default text that will appear in the text field.")
    public void setDirectoryPath(String path) {
        jTextFieldPath.setText(path);
    }
    
    public Icon getButtonIcon() {
        return jButtonPath.getIcon();
    }
    
    @BeanProperty(preferred = true, visualUpdate = true, description = "The icon on the file selector button.")
    public void setButtonIcon(Icon icon) {
        jButtonPath.setIcon(icon);
    }
    
    @BeanProperty(preferred = true, visualUpdate = true, description = "Info button.")
    public void setInfoMessage(String message) {
        infoButton.setMessageText(message);
        infoButton.setVisible(message != null && message.length() > 0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserFiles = new javax.swing.JFileChooser();
        flatFileViewDirectoryIcon = new com.formdev.flatlaf.icons.FlatFileViewDirectoryIcon();
        jLabelFile = new javax.swing.JLabel();
        jTextFieldPath = new javax.swing.JTextField();
        jButtonPath = new javax.swing.JButton();
        infoButton = new com.sfc.sf2.core.gui.controls.InfoButton();

        jFileChooserFiles.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setMinimumSize(new java.awt.Dimension(250, 26));
        setPreferredSize(new java.awt.Dimension(400, 26));

        jLabelFile.setText("Path name :");

        jTextFieldPath.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldPath.setText("jTextField1");
        jTextFieldPath.setMinimumSize(new java.awt.Dimension(50, 26));

        jButtonPath.setIcon(flatFileViewDirectoryIcon);
        jButtonPath.setMaximumSize(new java.awt.Dimension(26, 26));
        jButtonPath.setMinimumSize(new java.awt.Dimension(26, 26));
        jButtonPath.setPreferredSize(new java.awt.Dimension(26, 26));
        jButtonPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPathActionPerformed(evt);
            }
        });

        infoButton.setText("");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jButtonPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelFile)
                    .addComponent(jTextFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPathActionPerformed
        openFileChooser();
    }//GEN-LAST:event_jButtonPathActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoButtonActionPerformed

    private static String PATH_ACTION = "SetPath";
    private void openFileChooser() {
        File file = PathHelpers.getNearestValidParent(Path.of(jTextFieldPath.getText()));
        jFileChooserFiles.setCurrentDirectory(file);
        int returnVal = jFileChooserFiles.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String path = jFileChooserFiles.getSelectedFile().toString();
            path = path.replace(PathHelpers.getBasePath().toString(), ".");
            ActionManager.setAndExecuteAction(new BasicAction<String>(this, "Directory Change", this::setPath, path, jTextFieldPath.getText()));
        }
    }

    private void setPath(String data) {
        jTextFieldPath.setText(data);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.formdev.flatlaf.icons.FlatFileViewDirectoryIcon flatFileViewDirectoryIcon;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton;
    private javax.swing.JButton jButtonPath;
    private javax.swing.JFileChooser jFileChooserFiles;
    private javax.swing.JLabel jLabelFile;
    private javax.swing.JTextField jTextFieldPath;
    // End of variables declaration//GEN-END:variables
}
