/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sfc.sf2.dialog.properties.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.CustomAction;
import com.sfc.sf2.core.gui.AbstractMainEditor;
import com.sfc.sf2.core.gui.controls.Console;
import com.sfc.sf2.dialog.properties.DialogPropertiesManager;
import com.sfc.sf2.dialog.properties.DialogProperty;
import com.sfc.sf2.dialog.properties.actions.DialogPropertiesActionData;
import com.sfc.sf2.helpers.PathHelpers;
import java.io.File;
import java.nio.file.Path;
import java.util.logging.Level;

/**
 *
 * @author wiz
 */
public class DialogPropertiesMainEditor extends AbstractMainEditor {
    
    DialogPropertiesManager dialogpropertiesManager = new DialogPropertiesManager();
    
    public DialogPropertiesMainEditor() {
        super();
        initComponents();
        initCore(console1);
        
        //Handle if standard dialog properties exists or not
        File file = PathHelpers.getBasePath().resolve(fileButtonImportDialog.getFilePath()).toFile();
        if (!file.exists()) {
            fileButtonImportDialog.setFilePath(".\\spritedialogproperties.asm");
            fileButtonExportDialog.setFilePath(".\\spritedialogproperties.asm");
        }
    }
    
    @Override
    protected void initEditor() {
        super.initEditor();
        
        accordionPanel1.setExpanded(false);
        
        dialogPropertiesTable.jTable.getColumnModel().getColumn(0).setMaxWidth(30);
        dialogPropertiesTable.jTable.getColumnModel().getColumn(2).setMaxWidth(60);
        dialogPropertiesTable.jTable.getColumnModel().getColumn(4).setMaxWidth(60);
        dialogPropertiesTable.jTable.setRowHeight(70);
    }
    
    @Override
    protected void onDataLoaded() {
        super.onDataLoaded();
        dialogPropertiesTableModel.setEnums(dialogpropertiesManager.getDialogEnums());
        DialogPropertiesActionData newValue = new DialogPropertiesActionData(dialogpropertiesManager.getDialogProperties());
        DialogPropertiesActionData oldValue = new DialogPropertiesActionData(dialogPropertiesTableModel.getTableData(DialogProperty[].class));
        ActionManager.setAndExecuteAction(new CustomAction<DialogPropertiesActionData>(this, "Dialog Properties Imported", this::actionTilesetLoaded, newValue, oldValue));
    }
    
    private void actionTilesetLoaded(DialogPropertiesActionData data) {
        dialogPropertiesTableModel.setTableData(data.properties());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPropertiesTableModel = new com.sfc.sf2.dialog.properties.models.DialogPropertiesTableModel();
        jPanel13 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel15 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        dialogPropertiesTable = new com.sfc.sf2.dialog.properties.gui.DialogPropertiesTable();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        infoButton2 = new com.sfc.sf2.core.gui.controls.InfoButton();
        fileButtonImportDialog = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonImportDialog = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fileButtonExportDialog = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonExportDialog = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fileButtonImportAllies = new com.sfc.sf2.core.gui.controls.FileButton();
        infoButton1 = new com.sfc.sf2.core.gui.controls.InfoButton();
        jButtonImportAllies = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fileButtonExportAllies = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonExportAllies = new javax.swing.JButton();
        accordionPanel1 = new com.sfc.sf2.core.gui.controls.AccordionPanel();
        fileButtonImportBasePalette = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonImportMapsprites = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonImportPortraits = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonImportEnums = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonImportSpecialSprites = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonImportSpecialSpritePointers = new com.sfc.sf2.core.gui.controls.FileButton();
        console1 = new com.sfc.sf2.core.gui.controls.Console();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SF2DialogPropertiesManager");

        jSplitPane1.setDividerLocation(650);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.85);
        jSplitPane1.setOneTouchExpandable(true);

        jSplitPane2.setDividerLocation(300);
        jSplitPane2.setOneTouchExpandable(true);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Properties"));

        dialogPropertiesTable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        dialogPropertiesTable.setInfoMessage("<html>- Sprite: The mapsprite used when this character is added to a map. For ally dialog properties, the sprite cannot be changed in this system.<br>- Portrait: The portrait used when talking to this character (or as the character portrait for ally characters).<br>- SFX: The sound to play when this character talks.</html>");
        dialogPropertiesTable.setModel(dialogPropertiesTableModel);
        dialogPropertiesTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        dialogPropertiesTable.setName("Dialog Properties Table"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogPropertiesTable, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogPropertiesTable, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(jPanel10);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Import :"));

        jLabel2.setText("Import dialog properties disassembly.");

        infoButton2.setMessageText("<html>Used for:<br>- spritedialogproperties.asm<br>- spritedialogproperties.bin<br>- spritedialogproperties-standard.asm</html>");
        infoButton2.setText("");

        fileButtonImportDialog.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonImportDialog.setFilePath(".\\spritedialogproperties-standard.asm");
        fileButtonImportDialog.setInfoMessage("");
        fileButtonImportDialog.setLabelText("Dialog properties :");
        fileButtonImportDialog.setName("Import General Dialog"); // NOI18N

        jButtonImportDialog.setText("Import");
        jButtonImportDialog.setName(""); // NOI18N
        jButtonImportDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonImportDialog, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonImportDialog)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(infoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImportDialog)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Export :"));
        jPanel5.setPreferredSize(new java.awt.Dimension(32, 135));

        jLabel1.setText("Export dialog properties disassembly.");

        fileButtonExportDialog.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonExportDialog.setFilePath(".\\spritedialogproperties-standard.asm");
        fileButtonExportDialog.setInfoMessage("");
        fileButtonExportDialog.setLabelText("Dialog properties :");
        fileButtonExportDialog.setName("Export General Dialog"); // NOI18N

        jButtonExportDialog.setText("Export");
        jButtonExportDialog.setName(""); // NOI18N
        jButtonExportDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(fileButtonExportDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExportDialog)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonExportDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExportDialog)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("General dialog", jPanel1);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Import :"));

        jLabel4.setText("Import ally dialog properties disassembly.");

        fileButtonImportAllies.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonImportAllies.setFilePath(".\\stats\\allies\\allydialogproperties-standard.asm");
        fileButtonImportAllies.setInfoMessage("");
        fileButtonImportAllies.setLabelText("Dialog properties :");
        fileButtonImportAllies.setName("Import Allies Dialog"); // NOI18N

        infoButton1.setMessageText("<html>Used for:<br>- allydialogproperties-standard.asm</html>");
        infoButton1.setText("");

        jButtonImportAllies.setText("Import");
        jButtonImportAllies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportAlliesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonImportAllies, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonImportAllies)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(infoButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportAllies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImportAllies)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Export :"));
        jPanel9.setPreferredSize(new java.awt.Dimension(32, 135));

        jLabel3.setText("Export allies dialog properties disassembly.");

        fileButtonExportAllies.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonExportAllies.setFilePath(".\\stats\\allies\\allydialogproperties-standard.asm");
        fileButtonExportAllies.setInfoMessage("");
        fileButtonExportAllies.setLabelText("Dialog properties :");
        fileButtonExportAllies.setName("Export Allies Dialog"); // NOI18N

        jButtonExportAllies.setText("Export");
        jButtonExportAllies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportAlliesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonExportAllies, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonExportAllies)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonExportAllies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonExportAllies)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Allies dialog", jPanel2);

        accordionPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Import data :"));

        fileButtonImportBasePalette.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonImportBasePalette.setFilePath(".\\graphics\\tech\\basepalette.bin");
        fileButtonImportBasePalette.setInfoMessage("The game's base palette. Used to show the mapsprites.");
        fileButtonImportBasePalette.setLabelText("Base palette :");
        fileButtonImportBasePalette.setName("Import Base Palette"); // NOI18N

        fileButtonImportMapsprites.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonImportMapsprites.setFilePath(".\\graphics\\mapsprites\\entries.asm");
        fileButtonImportMapsprites.setInfoMessage("The entries file to load mapsprite previews.");
        fileButtonImportMapsprites.setLabelText("Mapsprite entries :");
        fileButtonImportMapsprites.setName("Import Mapsprite Entries"); // NOI18N

        fileButtonImportPortraits.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonImportPortraits.setFilePath(".\\graphics\\portraits\\entries.asm");
        fileButtonImportPortraits.setInfoMessage("The entries file to show preview of portraits.");
        fileButtonImportPortraits.setLabelText("Portrait entries :");
        fileButtonImportPortraits.setName("Import Portrait Entries"); // NOI18N

        fileButtonImportEnums.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonImportEnums.setFilePath("..\\sf2enums.asm");
        fileButtonImportEnums.setInfoMessage("Loads data from SF2Enums, including: SFX file names.");
        fileButtonImportEnums.setLabelText("SF2Enums :");
        fileButtonImportEnums.setName("Import Enums"); // NOI18N

        fileButtonImportSpecialSprites.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonImportSpecialSprites.setFilePath(".\\graphics\\specialsprites\\entries.asm");
        fileButtonImportSpecialSprites.setInfoMessage("The special sprites entries to show preview of special sprites (ie. boss sprites).");
        fileButtonImportSpecialSprites.setLabelText("Special sprite entries :");
        fileButtonImportSpecialSprites.setName("Import Special Sprite Entries"); // NOI18N

        fileButtonImportSpecialSpritePointers.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonImportSpecialSpritePointers.setFilePath(".\\graphics\\specialsprites\\pointers.asm");
        fileButtonImportSpecialSpritePointers.setInfoMessage("Also required to load special sprites.");
        fileButtonImportSpecialSpritePointers.setLabelText("Special sprite pointers :");
        fileButtonImportSpecialSpritePointers.setName("Import Special Sprite Pointers"); // NOI18N

        javax.swing.GroupLayout accordionPanel1Layout = new javax.swing.GroupLayout(accordionPanel1);
        accordionPanel1.setLayout(accordionPanel1Layout);
        accordionPanel1Layout.setHorizontalGroup(
            accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accordionPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonImportMapsprites, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonImportBasePalette, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonImportPortraits, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonImportEnums, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonImportSpecialSprites, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonImportSpecialSpritePointers, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        accordionPanel1Layout.setVerticalGroup(
            accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accordionPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileButtonImportBasePalette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportEnums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportMapsprites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportPortraits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportSpecialSprites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportSpecialSpritePointers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accordionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accordionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Import");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        jSplitPane2.setLeftComponent(jPanel8);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        jSplitPane1.setTopComponent(jPanel15);
        jSplitPane1.setBottomComponent(console1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1049, 838));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExportDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportDialogActionPerformed
        Path dialogPropertiesPath = PathHelpers.getBasePath().resolve(fileButtonExportDialog.getFilePath());
        if (!PathHelpers.createPathIfRequred(dialogPropertiesPath)) return;
        try {
            dialogpropertiesManager.exportDisassembly(dialogPropertiesPath, dialogPropertiesTableModel.getTableData(DialogProperty[].class));
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Dialog properties disasm could not be exported to : " + dialogPropertiesPath);
        }
    }//GEN-LAST:event_jButtonExportDialogActionPerformed

    private void jButtonImportDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportDialogActionPerformed
        Path palettePath = PathHelpers.getBasePath().resolve(fileButtonImportBasePalette.getFilePath());
        Path enumsPath = PathHelpers.getBasePath().resolve(fileButtonImportEnums.getFilePath());
        Path mapspriteEntriesPath = PathHelpers.getBasePath().resolve(fileButtonImportMapsprites.getFilePath());
        Path portraitEntriesPath = PathHelpers.getBasePath().resolve(fileButtonImportPortraits.getFilePath());
        Path dialogPropertiesPath = PathHelpers.getBasePath().resolve(fileButtonImportDialog.getFilePath());
        try {
            dialogpropertiesManager.importImagesAndEnums(palettePath, mapspriteEntriesPath, portraitEntriesPath, enumsPath);
            dialogpropertiesManager.importDisassembly(dialogPropertiesPath);
            dialogPropertiesTableModel.setMapSpritesEditable(true);
        } catch (Exception ex) {
            dialogpropertiesManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Dialog properties could not be imported from : " + dialogPropertiesPath);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportDialogActionPerformed

    private void jButtonExportAlliesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportAlliesActionPerformed
        Path dialogPropertiesPath = PathHelpers.getBasePath().resolve(fileButtonExportAllies.getFilePath());
        if (!PathHelpers.createPathIfRequred(dialogPropertiesPath)) return;
        try {
            dialogpropertiesManager.exportAlliesDisassembly(dialogPropertiesPath, dialogPropertiesTableModel.getTableData(DialogProperty[].class));
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Allies dialog properties disasm could not be exported to : " + dialogPropertiesPath);
        }
    }//GEN-LAST:event_jButtonExportAlliesActionPerformed

    private void jButtonImportAlliesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportAlliesActionPerformed
        Path palettePath = PathHelpers.getBasePath().resolve(fileButtonImportBasePalette.getFilePath());
        Path enumsPath = PathHelpers.getBasePath().resolve(fileButtonImportEnums.getFilePath());
        Path mapspriteEntriesPath = PathHelpers.getBasePath().resolve(fileButtonImportMapsprites.getFilePath());
        Path portraitEntriesPath = PathHelpers.getBasePath().resolve(fileButtonImportPortraits.getFilePath());
        Path dialogPropertiesPath = PathHelpers.getBasePath().resolve(fileButtonImportAllies.getFilePath());
        try {
            dialogpropertiesManager.importImagesAndEnums(palettePath, mapspriteEntriesPath, portraitEntriesPath, enumsPath);
            dialogpropertiesManager.importAlliesDisassembly(dialogPropertiesPath);
            dialogPropertiesTableModel.setMapSpritesEditable(false);
        } catch (Exception ex) {
            dialogpropertiesManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Dialog properties could not be imported from : " + dialogPropertiesPath);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportAlliesActionPerformed

    /**
     * To create a new Main Editor, copy the below code
     * Don't forget to change the new main class (below)
     */
    public static void main(String args[]) {
        AbstractMainEditor.programSetup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogPropertiesMainEditor().setVisible(true);  // <------ Change this class to new Main Editor class
            }
        });
    }
    /**
     * To create a new Main Editor, copy the above code
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.AccordionPanel accordionPanel1;
    private com.sfc.sf2.core.gui.controls.Console console1;
    private com.sfc.sf2.dialog.properties.gui.DialogPropertiesTable dialogPropertiesTable;
    private com.sfc.sf2.dialog.properties.models.DialogPropertiesTableModel dialogPropertiesTableModel;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportAllies;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportDialog;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportAllies;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportBasePalette;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportDialog;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportEnums;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportMapsprites;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportPortraits;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportSpecialSpritePointers;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportSpecialSprites;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton1;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton2;
    private javax.swing.JButton jButtonExportAllies;
    private javax.swing.JButton jButtonExportDialog;
    private javax.swing.JButton jButtonImportAllies;
    private javax.swing.JButton jButtonImportDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
