/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sfc.sf2.core.gui;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.sfc.sf2.core.Manifest;
import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.settings.CoreSettings;
import com.sfc.sf2.core.settings.GlobalSettings;
import com.sfc.sf2.core.settings.SettingsManager;
import com.sfc.sf2.core.gui.controls.Console;
import com.sfc.sf2.helpers.PathHelpers;
import java.net.URI;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TiMMy
 */
public abstract class AbstractMainEditor extends javax.swing.JFrame {
        
    /**
     * Creates new form New Application
     */
    public AbstractMainEditor() {
        initComponents();
        java.awt.EventQueue.invokeLater(() -> {
            initEditor();
            SettingsManager.setSavingAllowed(true); //Slight hack to prevent controls affecting settings on initialisation
        });
    }
    
    protected void initCore(Console console) {
        //Console
        if (console != null) {
            console.initLogger("SF2 Java Suite");
        }
        //Version
        if (!SettingsManager.isRunningInEditor()) {
            String version = Manifest.getProjectVersion();
            if (version != null)
                this.setTitle(this.getTitle() + " - v" + version);
        }
        //Settings
        SettingsManager.loadGlobalSettings();
        SettingsManager.loadSettingsFile();
        if (console != null) {
            console.setLogLevel(SettingsManager.getGlobalSettings().getLogLevel());
        }
        CoreSettings core = SettingsManager.getSettingsStore("core");
        if (!SettingsManager.isRunningInEditor()) {
            //Check if settings panel should be shown
            java.awt.EventQueue.invokeLater(() -> {
                if (!core.arePathsValid()) {
                    Console.logger().info("Could not automatically detect app path : " + PathHelpers.getApplicationpath().toString());
                    jFrameSettings.setVisible(true);
                }
            });
        }
    }
    
    protected void initEditor() {
        
    }
    
    protected void onDataLoaded() {
        
    }
    
    public static void programSetup() {
        //Hack to determine if project is running from editor (IDE) or is a build. (property 'user.dir' is blank if in editor)
        String dir = System.getProperty("user.dir");
        SettingsManager.setRunningInEditor(dir == null || dir.length() == 0);
        SettingsManager.loadGlobalSettings();
        
        //Set look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //Have to load core settings first to check theme                                     
            if (SettingsManager.getGlobalSettings().getIsDarkTheme())
                FlatDarkLaf.setup();
            else
                FlatLightLaf.setup();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(AbstractMainEditor.class.getName()).log(java.util.logging.Level.SEVERE, "FlatLaf theme could not be loaded. Loading default theme instead", ex);
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException e) {
                java.util.logging.Logger.getLogger(AbstractMainEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
            }
        }
        //</editor-fold>
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameSettings = new javax.swing.JFrame();
        jPanelSettings = new javax.swing.JPanel();
        jCheckBoxPrioritise = new javax.swing.JCheckBox();
        infoButton3 = new com.sfc.sf2.core.gui.controls.InfoButton();
        directoryButtonBasePath = new com.sfc.sf2.core.gui.controls.DirectoryButton();
        directoryButtonIncbinPath = new com.sfc.sf2.core.gui.controls.DirectoryButton();
        jRadioThemeLight = new javax.swing.JRadioButton();
        jRadioThemeDark = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonGroupTheme = new com.sfc.sf2.core.gui.controls.NameableButtonGroup();
        jFrameActionHistory = new javax.swing.JFrame();
        jPanelActions = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonUndo = new javax.swing.JButton();
        jButtonRedo = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHistory = new javax.swing.JTable();
        jFrameHelp = new javax.swing.JFrame();
        jPanelHelp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonDiscord = new javax.swing.JButton();
        jButtonGitHubIssues = new javax.swing.JButton();
        jButtonVersionHistory = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemUndo = new javax.swing.JMenuItem();
        jMenuItemRedo = new javax.swing.JMenuItem();
        jMenuItemActionHistory = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jMenuItemSettings = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemHelp = new javax.swing.JMenuItem();

        jFrameSettings.setTitle("Settings");
        jFrameSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFrameSettings.setLocationByPlatform(true);
        jFrameSettings.setMinimumSize(new java.awt.Dimension(500, 200));
        jFrameSettings.setName("Frame Settings"); // NOI18N
        jFrameSettings.setResizable(false);
        jFrameSettings.setSize(new java.awt.Dimension(500, 250));
        jFrameSettings.setType(java.awt.Window.Type.POPUP);
        jFrameSettings.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrameSettingsWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrameSettingsWindowOpened(evt);
            }
        });

        jPanelSettings.setMinimumSize(new java.awt.Dimension(400, 200));
        jPanelSettings.setPreferredSize(new java.awt.Dimension(400, 200));

        jCheckBoxPrioritise.setSelected(true);
        jCheckBoxPrioritise.setText("Prioritise local path");
        jCheckBoxPrioritise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPrioritiseActionPerformed(evt);
            }
        });

        infoButton3.setMessageText("<html>If the .jar file detects that it is inside SF2DISASM then it will assume that the user wants to load data from this SF2DISASM directory.<br>Toggle this off and use the 'base folder' and 'incbin folder' to point to a custom directory.<br><b>Most users do not need to edit this.</b></html>");
        infoButton3.setText("");

        directoryButtonBasePath.setInfoMessage("<html>Base folder is where the .jar file is expected to be run from.<br><b>Most users do not need to edit this path.</b></html>");
        directoryButtonBasePath.setLabelText("Base folder :");
        directoryButtonBasePath.setMinimumSize(new java.awt.Dimension(150, 25));
        directoryButtonBasePath.setPreferredSize(new java.awt.Dimension(200, 25));

        directoryButtonIncbinPath.setInfoMessage("<html>Incbin is the root folder for the disassemby (usually SF2DISASM\\disasm\\)<br><b>Most users do not need to edit this path.</b></html>");
        directoryButtonIncbinPath.setLabelText("incbin folder :");
        directoryButtonIncbinPath.setMinimumSize(new java.awt.Dimension(150, 25));
        directoryButtonIncbinPath.setPreferredSize(new java.awt.Dimension(200, 25));

        buttonGroupTheme.add(jRadioThemeLight);
        jRadioThemeLight.setText("Light");

        buttonGroupTheme.add(jRadioThemeDark);
        jRadioThemeDark.setText("Dark");

        jLabel6.setText("<html>Theme <i>(Requires restart)</i>  :</html>");

        javax.swing.GroupLayout jPanelSettingsLayout = new javax.swing.GroupLayout(jPanelSettings);
        jPanelSettings.setLayout(jPanelSettingsLayout);
        jPanelSettingsLayout.setHorizontalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(directoryButtonBasePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(directoryButtonIncbinPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioThemeLight)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioThemeDark)
                                .addGap(0, 157, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addComponent(jCheckBoxPrioritise)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelSettingsLayout.setVerticalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(infoButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxPrioritise))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(directoryButtonBasePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(directoryButtonIncbinPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRadioThemeDark)
                    .addComponent(jRadioThemeLight)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameSettingsLayout = new javax.swing.GroupLayout(jFrameSettings.getContentPane());
        jFrameSettings.getContentPane().setLayout(jFrameSettingsLayout);
        jFrameSettingsLayout.setHorizontalGroup(
            jFrameSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameSettingsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jFrameSettingsLayout.setVerticalGroup(
            jFrameSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameSettingsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
        );

        buttonGroupTheme.setName("Theme Button Group");

        jFrameActionHistory.setTitle("Action History");
        jFrameActionHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFrameActionHistory.setLocationByPlatform(true);
        jFrameActionHistory.setMinimumSize(new java.awt.Dimension(500, 200));
        jFrameActionHistory.setName("Frame Settings"); // NOI18N
        jFrameActionHistory.setResizable(false);
        jFrameActionHistory.setSize(new java.awt.Dimension(500, 250));
        jFrameActionHistory.setType(java.awt.Window.Type.POPUP);
        jFrameActionHistory.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                jFrameActionHistoryWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        jFrameActionHistory.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrameActionHistoryWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrameActionHistoryWindowOpened(evt);
            }
        });

        jPanelActions.setMinimumSize(new java.awt.Dimension(400, 200));

        jLabel1.setText("<html>A debugging window to see the action history (the undo/redo history).</html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonUndo.setText("Undo");
        jButtonUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUndoActionPerformed(evt);
            }
        });

        jButtonRedo.setText("Redo");
        jButtonRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRedoActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jTableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Index", "Owner", "Command", "New Data", "Old Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableHistory.setEnabled(false);
        jTableHistory.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableHistory);

        javax.swing.GroupLayout jPanelActionsLayout = new javax.swing.GroupLayout(jPanelActions);
        jPanelActions.setLayout(jPanelActionsLayout);
        jPanelActionsLayout.setHorizontalGroup(
            jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanelActionsLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(515, Short.MAX_VALUE))
            .addGroup(jPanelActionsLayout.createSequentialGroup()
                .addComponent(jButtonUndo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRedo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClear))
        );
        jPanelActionsLayout.setVerticalGroup(
            jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUndo)
                    .addComponent(jButtonRedo)
                    .addComponent(jButtonClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameActionHistoryLayout = new javax.swing.GroupLayout(jFrameActionHistory.getContentPane());
        jFrameActionHistory.getContentPane().setLayout(jFrameActionHistoryLayout);
        jFrameActionHistoryLayout.setHorizontalGroup(
            jFrameActionHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameActionHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrameActionHistoryLayout.setVerticalGroup(
            jFrameActionHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameActionHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jFrameHelp.setTitle("Help");
        jFrameHelp.setAlwaysOnTop(true);
        jFrameHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFrameHelp.setLocationByPlatform(true);
        jFrameHelp.setMinimumSize(new java.awt.Dimension(500, 200));
        jFrameHelp.setName("Frame Settings"); // NOI18N
        jFrameHelp.setResizable(false);
        jFrameHelp.setSize(new java.awt.Dimension(500, 250));
        jFrameHelp.setType(java.awt.Window.Type.POPUP);
        jFrameHelp.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrameHelpWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrameHelpWindowOpened(evt);
            }
        });

        jPanelHelp.setMinimumSize(new java.awt.Dimension(300, 100));
        jPanelHelp.setPreferredSize(new java.awt.Dimension(300, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Need help with the tools?");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 25));

        jButtonDiscord.setIcon(new javax.swing.ImageIcon("D:\\TiMMy\\Dev\\ShiningForce2\\SF2JavaToolsSuite\\SF2CoreLibrary\\res\\Core\\Icons\\Logo_Discord.png")); // NOI18N
        jButtonDiscord.setText("SF2 Hacking Discord");
        jButtonDiscord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiscordActionPerformed(evt);
            }
        });

        jButtonGitHubIssues.setIcon(new javax.swing.ImageIcon("D:\\TiMMy\\Dev\\ShiningForce2\\SF2JavaToolsSuite\\SF2CoreLibrary\\res\\Core\\Icons\\Logo_Github.png")); // NOI18N
        jButtonGitHubIssues.setText("Report an issue");
        jButtonGitHubIssues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGitHubIssuesActionPerformed(evt);
            }
        });

        jButtonVersionHistory.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVersionHistory.setText("<html><u>See version history</u></html>");
        jButtonVersionHistory.setBorder(null);
        jButtonVersionHistory.setBorderPainted(false);
        jButtonVersionHistory.setContentAreaFilled(false);
        jButtonVersionHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVersionHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHelpLayout = new javax.swing.GroupLayout(jPanelHelp);
        jPanelHelp.setLayout(jPanelHelpLayout);
        jPanelHelpLayout.setHorizontalGroup(
            jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelHelpLayout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addGroup(jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDiscord, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(jButtonGitHubIssues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVersionHistory))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelHelpLayout.setVerticalGroup(
            jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDiscord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGitHubIssues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVersionHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameHelpLayout = new javax.swing.GroupLayout(jFrameHelp.getContentPane());
        jFrameHelp.getContentPane().setLayout(jFrameHelpLayout);
        jFrameHelpLayout.setHorizontalGroup(
            jFrameHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrameHelpLayout.setVerticalGroup(
            jFrameHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameHelpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SF2 App");

        jSplitPane1.setDividerLocation(450);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSplitPane1.setTopComponent(jPanel15);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        jSplitPane1.setBottomComponent(jPanel1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        jMenuFile.setText("File");

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUndoActionPerformed(evt);
            }
        });

        jMenuItemUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemUndo.setText("Undo");
        jMenuItemUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUndoActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemUndo);

        jMenuItemRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemRedo.setText("Redo");
        jMenuItemRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRedoActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemRedo);

        jMenuItemActionHistory.setText("Action History");
        jMenuItemActionHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActionHistoryActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemActionHistory);

        jMenuBar1.add(jMenuEdit);

        jMenuSettings.setText("Settings");

        jMenuItemSettings.setText("Settings");
        jMenuItemSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSettingsActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItemSettings);

        jMenuBar1.add(jMenuSettings);

        jMenuHelp.setText("Help");

        jMenuItemHelp.setText("Help");
        jMenuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemHelp);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1028, 664));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSettingsActionPerformed
        jFrameSettings.setVisible(true);
    }//GEN-LAST:event_jMenuItemSettingsActionPerformed

    private void jFrameSettingsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameSettingsWindowClosing
        CoreSettings core = SettingsManager.getSettingsStore("core");
        core.setPrioritiseLocalPath(jCheckBoxPrioritise.isSelected());
        core.setBasePath(directoryButtonBasePath.getDirectoryPath());
        core.setIncbinPath(directoryButtonIncbinPath.getDirectoryPath());
        SettingsManager.getGlobalSettings().setIsDarkTheme(jRadioThemeDark.isSelected());
        SettingsManager.saveGlobalSettingsFile();
        SettingsManager.saveSettingsFile();
    }//GEN-LAST:event_jFrameSettingsWindowClosing

    private void jFrameSettingsWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameSettingsWindowOpened
        jFrameSettings.setLocationRelativeTo(this);
        jFrameSettings.setSize(jFrameSettings.getPreferredSize());
        
        GlobalSettings global = SettingsManager.getGlobalSettings();
        CoreSettings core = SettingsManager.getSettingsStore("core");
        jCheckBoxPrioritise.setSelected(core.isPrioritiseLocalPath());
        jRadioThemeLight.setSelected(!global.getIsDarkTheme());
        jRadioThemeDark.setSelected(global.getIsDarkTheme());
        if (core.arePathsValid()) {
            directoryButtonBasePath.setDirectoryPath(core.getBasePath());
            directoryButtonIncbinPath.setDirectoryPath(core.getIncbinPath());
        } else {
            directoryButtonBasePath.setDirectoryPath(PathHelpers.getApplicationpath().toString());
            directoryButtonIncbinPath.setDirectoryPath(PathHelpers.getApplicationpath().toString());
        }
        jCheckBoxPrioritiseActionPerformed(null);
    }//GEN-LAST:event_jFrameSettingsWindowOpened

    private void jCheckBoxPrioritiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPrioritiseActionPerformed
        CoreSettings core = SettingsManager.getSettingsStore("core");
        directoryButtonBasePath.setEnabled(!(jCheckBoxPrioritise.isSelected() && core.areLocalPathsValid()));
        directoryButtonIncbinPath.setEnabled(!(jCheckBoxPrioritise.isSelected() && core.areLocalPathsValid()));
    }//GEN-LAST:event_jCheckBoxPrioritiseActionPerformed

    private void jFrameActionHistoryWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameActionHistoryWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrameActionHistoryWindowClosing

    static String[] HISTORY_COLUMN_NAMES = new String[] { "Owner", "Action", "New Data", "Previous Data" };
    private void jFrameActionHistoryWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameActionHistoryWindowOpened
        jFrameActionHistory.setLocationRelativeTo(this);
        jFrameActionHistory.setSize(jFrameActionHistory.getPreferredSize());
        //Data set on jFrameActionHistoryWindowGainedFocus
    }//GEN-LAST:event_jFrameActionHistoryWindowOpened

    private void jButtonUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUndoActionPerformed
        boolean alwaysOnTop = jFrameActionHistory.isAlwaysOnTop();
        jFrameActionHistory.setAlwaysOnTop(true);
        ActionManager.undo();
        updateActionHistorySelection();
        jFrameActionHistory.setAlwaysOnTop(alwaysOnTop);
    }//GEN-LAST:event_jButtonUndoActionPerformed

    private void jButtonRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRedoActionPerformed
        boolean alwaysOnTop = jFrameActionHistory.isAlwaysOnTop();
        jFrameActionHistory.setAlwaysOnTop(true);
        ActionManager.redo();
        updateActionHistorySelection();
        jFrameActionHistory.setAlwaysOnTop(alwaysOnTop);
    }//GEN-LAST:event_jButtonRedoActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        ActionManager.clearActionhistory();
        jTableHistory.clearSelection();
        Object[][] tableData = ActionManager.getHistoryTableData();
        jTableHistory.setModel(new DefaultTableModel(tableData, HISTORY_COLUMN_NAMES));
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jMenuItemActionHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActionHistoryActionPerformed
        jFrameActionHistory.setVisible(true);
    }//GEN-LAST:event_jMenuItemActionHistoryActionPerformed

    private void jFrameActionHistoryWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameActionHistoryWindowGainedFocus
        Object[][] tableData = ActionManager.getHistoryTableData();
        jTableHistory.setModel(new DefaultTableModel(tableData, HISTORY_COLUMN_NAMES));
        updateActionHistorySelection();
    }//GEN-LAST:event_jFrameActionHistoryWindowGainedFocus
     
    private void updateActionHistorySelection() {
        if (!jFrameActionHistory.isActive()) return;
        int index = ActionManager.getCurrentHistoryIndex()-1;
        if (index == -1 || index >= jTableHistory.getRowCount()) {
            jTableHistory.clearSelection();
        } else {
            jTableHistory.setRowSelectionInterval(index, index);
        }
    }
    private void jMenuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpActionPerformed
        jFrameHelp.setLocationRelativeTo(this);
        jFrameHelp.setVisible(true);
    }//GEN-LAST:event_jMenuItemHelpActionPerformed

    private void jFrameHelpWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameHelpWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrameHelpWindowClosing

    private void jFrameHelpWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameHelpWindowOpened
        
    }//GEN-LAST:event_jFrameHelpWindowOpened

    private void jButtonDiscordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiscordActionPerformed
        try {
            URI link = new URI("https://discord.gg/Yw4npfBDCY");
            java.awt.Desktop.getDesktop().browse(link);
        } catch (Exception ex) {
            Console.logger().severe(ex.toString());
        }
    }//GEN-LAST:event_jButtonDiscordActionPerformed

    private void jButtonGitHubIssuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGitHubIssuesActionPerformed
        try {
            URI link = new URI("https://github.com/ShiningForceCentral/SF2JavaToolSuite/issues");
            java.awt.Desktop.getDesktop().browse(link);
        } catch (Exception ex) {
            Console.logger().severe(ex.toString());
        }
    }//GEN-LAST:event_jButtonGitHubIssuesActionPerformed

    private void jButtonVersionHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVersionHistoryActionPerformed
        try {
            String versionpath = String.format("https://github.com/ShiningForceCentral/SF2JavaToolSuite/blob/main/%s/version.properties", Manifest.getProjectName());
            URI link = new URI(versionpath);
            java.awt.Desktop.getDesktop().browse(link);
        } catch (Exception ex) {
            Console.logger().severe(ex.toString());
        }
    }//GEN-LAST:event_jButtonVersionHistoryActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.NameableButtonGroup buttonGroupTheme;
    private com.sfc.sf2.core.gui.controls.DirectoryButton directoryButtonBasePath;
    private com.sfc.sf2.core.gui.controls.DirectoryButton directoryButtonIncbinPath;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton3;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDiscord;
    private javax.swing.JButton jButtonGitHubIssues;
    private javax.swing.JButton jButtonRedo;
    private javax.swing.JButton jButtonUndo;
    private javax.swing.JButton jButtonVersionHistory;
    private javax.swing.JCheckBox jCheckBoxPrioritise;
    private javax.swing.JFrame jFrameActionHistory;
    private javax.swing.JFrame jFrameHelp;
    private javax.swing.JFrame jFrameSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemActionHistory;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemHelp;
    private javax.swing.JMenuItem jMenuItemRedo;
    private javax.swing.JMenuItem jMenuItemSettings;
    private javax.swing.JMenuItem jMenuItemUndo;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanelActions;
    private javax.swing.JPanel jPanelHelp;
    private javax.swing.JPanel jPanelSettings;
    private javax.swing.JRadioButton jRadioThemeDark;
    private javax.swing.JRadioButton jRadioThemeLight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableHistory;
    // End of variables declaration//GEN-END:variables
}
