<<<<<<< HEAD
version: 1.6.1-Test
=======
version: 1.6.1
>>>>>>> branch 'main' of https://github.com/TiMMyyMMiT/SF2JavaToolSuite.git
release-notes:
<<<<<<< HEAD
v1.6.1-Test: Testing
v1.6.0: Added undo/redo feature.
=======
v1.6.1: Linux platform support.
v1.6.0: Added undo/redo feature. Added settings for all view options.
>>>>>>> branch 'main' of https://github.com/TiMMyyMMiT/SF2JavaToolSuite.git
v1.5.5: Added help menu with discord and GitHub links. More (?) buttons for info.
v1.5.4: Force all (disasm) colors to be CRAM colors.
