version: 1.6.1-Test
release-notes:
v1.6.1-Test: Testing
v1.6.0: Added undo/redo feature.
v1.5.5: Added help menu with discord and GitHub links. More (?) buttons for info.
v1.5.4: Force all (disasm) colors to be CRAM colors.