/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sfc.sf2.battle.mapcoords.gui;

import com.sfc.sf2.battle.mapcoords.BattleMapCoords;
import com.sfc.sf2.battle.mapcoords.BattleMapCoordsManager;
import com.sfc.sf2.battle.mapcoords.actions.MapLoadActionData;
import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.CustomAction;
import com.sfc.sf2.core.actions.NonCombinableAction;
import com.sfc.sf2.core.gui.AbstractMainEditor;
import com.sfc.sf2.core.gui.controls.Console;
import com.sfc.sf2.core.settings.SettingsManager;
import com.sfc.sf2.core.settings.ViewSettings;
import com.sfc.sf2.helpers.PathHelpers;
import java.nio.file.Path;
import java.util.logging.Level;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.TableModelEvent;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author wiz
 */
public class BattleCoordsMainEditor extends AbstractMainEditor {
    
    private final ViewSettings viewSettings = new ViewSettings();
    BattleMapCoordsManager battlemapcoordsManager = new BattleMapCoordsManager();
    
    BattleMapCoords[] coords;
    int selectedCoords;
    int previousCoords = -1;
    
    public BattleCoordsMainEditor() {
        super();
        SettingsManager.registerSettingsStore("view", viewSettings);
        initComponents();
        initCore(console1);
    }
    
    @Override
    protected void initEditor() {
        super.initEditor();
        
        battleMapViewPanel1.setLayoutPanel(battleMapCoordsLayoutPanel, viewSettings);
        accordionPanel1.setExpanded(false);
        battleMapCoordsLayoutPanel.setShowBattleCoords(true);
        
        tableCoords.addTableModelListener(this::onTableFrameDataChanged);
        tableCoords.addListSelectionListener(this::onTableFrameSelectionChanged);
        TableColumnModel columns = tableCoords.jTable.getColumnModel();
        columns.getColumn(0).setMaxWidth(30);
    }
    
    @Override
    protected void onDataLoaded() {
        super.onDataLoaded();
        ActionManager.setAndExecuteAction(new NonCombinableAction<BattleMapCoords[]>(this, "Battle Map Coords Imported", this::actionBattleCoordsLoaded, battlemapcoordsManager.getCoords(), battleMapCoordsTableModel.getTableData(BattleMapCoords[].class)));
    }
    
    private void actionBattleCoordsLoaded(BattleMapCoords[] coords) {
        battleMapCoordsTableModel.setTableData(coords);
        if (coords.length == 0) {
            tableCoords.jTable.clearSelection();
        } else {
            tableCoords.jTable.setRowSelectionInterval(0, 0);
        }
    }
    
    private void UpdateMapLoaded() {
        MapLoadActionData newValue = new MapLoadActionData(selectedCoords, battlemapcoordsManager.getMapLayout());
        MapLoadActionData oldValue = new MapLoadActionData(previousCoords, battleMapCoordsLayoutPanel.getMapLayout());
        ActionManager.setAndExecuteAction(new CustomAction<MapLoadActionData>(this, "Battle Map Loaded", this::actionMapLoaded, newValue, oldValue));
    }
    
    private void actionMapLoaded(MapLoadActionData value) {
        previousCoords = value == null ? -1 : value.coordsIndex();
        if (previousCoords == -1) {
            battleMapCoordsLayoutPanel.setMapLayout(null);
            battleMapCoordsLayoutPanel.setBattleCoords(null);
            tableCoords.jTable.clearSelection();
        } else {
            battleMapCoordsLayoutPanel.setMapLayout(value.layout());
            battleMapCoordsLayoutPanel.setBattleCoords(coords[value.coordsIndex()]);
            tableCoords.jTable.setRowSelectionInterval(previousCoords, previousCoords);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        battleMapCoordsTableModel = new com.sfc.sf2.battle.mapcoords.models.BattleMapCoordsTableModel();
        jPanel13 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel15 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonImport = new javax.swing.JButton();
        fileButtonImportBattleCoords = new com.sfc.sf2.core.gui.controls.FileButton();
        accordionPanel1 = new com.sfc.sf2.core.gui.controls.AccordionPanel();
        fileButtonPaletteEntries = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonTilesetsEntries = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonMapEntries = new com.sfc.sf2.core.gui.controls.FileButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonExport = new javax.swing.JButton();
        fileButtonExportBattleCoords = new com.sfc.sf2.core.gui.controls.FileButton();
        tableCoords = new com.sfc.sf2.core.gui.controls.Table();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        battleMapCoordsLayoutPanel = new com.sfc.sf2.battle.mapcoords.gui.BattleMapCoordsLayoutPanel();
        battleMapViewPanel1 = new com.sfc.sf2.battle.mapcoords.gui.BattleMapViewPanel();
        console1 = new com.sfc.sf2.core.gui.controls.Console();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SF2BattleMapCoordsManager");

        jSplitPane1.setDividerLocation(700);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);

        jSplitPane2.setDividerLocation(500);
        jSplitPane2.setOneTouchExpandable(true);

        jPanel8.setPreferredSize(new java.awt.Dimension(400, 400));

        jPanel9.setPreferredSize(new java.awt.Dimension(400, 400));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Import from :"));
        jPanel3.setPreferredSize(new java.awt.Dimension(590, 135));

        jLabel2.setText("Select disassembly files.");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonImport.setText("Import");
        jButtonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportActionPerformed(evt);
            }
        });

        fileButtonImportBattleCoords.setFilePath(".\\global\\battlemapcoords.asm");
        fileButtonImportBattleCoords.setLabelText("Battle map coords :");
        fileButtonImportBattleCoords.setName("Import Battle Coords"); // NOI18N

        accordionPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Entries"));

        fileButtonPaletteEntries.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonPaletteEntries.setFilePath("..\\graphics\\maps\\mappalettes\\entries.asm");
        fileButtonPaletteEntries.setInfoMessage("");
        fileButtonPaletteEntries.setLabelText("Palette entries :");
        fileButtonPaletteEntries.setName("Import Palette Entries"); // NOI18N

        fileButtonTilesetsEntries.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonTilesetsEntries.setFilePath("..\\graphics\\maps\\maptilesets\\entries.asm");
        fileButtonTilesetsEntries.setInfoMessage("");
        fileButtonTilesetsEntries.setLabelText("Tilesets entries :");
        fileButtonTilesetsEntries.setName("Import Tilesets Entries"); // NOI18N

        fileButtonMapEntries.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonMapEntries.setFilePath("..\\maps\\entries.asm");
        fileButtonMapEntries.setInfoMessage("");
        fileButtonMapEntries.setLabelText("Map entries :");
        fileButtonMapEntries.setName("Import Map Entries"); // NOI18N

        javax.swing.GroupLayout accordionPanel1Layout = new javax.swing.GroupLayout(accordionPanel1);
        accordionPanel1.setLayout(accordionPanel1Layout);
        accordionPanel1Layout.setHorizontalGroup(
            accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accordionPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fileButtonPaletteEntries, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonTilesetsEntries, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonMapEntries, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        accordionPanel1Layout.setVerticalGroup(
            accordionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accordionPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileButtonPaletteEntries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonTilesetsEntries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonMapEntries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accordionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonImport))
                    .addComponent(fileButtonImportBattleCoords, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accordionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportBattleCoords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImport)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Export to :"));
        jPanel5.setPreferredSize(new java.awt.Dimension(32, 135));

        jLabel1.setText("<html>Select target file.</html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonExport.setText("Export");
        jButtonExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportActionPerformed(evt);
            }
        });

        fileButtonExportBattleCoords.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonExportBattleCoords.setFilePath(".\\global\\battlemapcoords.asm");
        fileButtonExportBattleCoords.setInfoMessage("");
        fileButtonExportBattleCoords.setLabelText("Battle map coords :");
        fileButtonExportBattleCoords.setName("Export Map Coords"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonExportBattleCoords, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExport)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileButtonExportBattleCoords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExport)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tableCoords.setBorder(javax.swing.BorderFactory.createTitledBorder("Battle coordinates"));
        tableCoords.setModel(battleMapCoordsTableModel);
        tableCoords.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableCoords.setSingleClickText(true);
        tableCoords.setSpinnerNumberEditor(true);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addComponent(tableCoords, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableCoords, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        jSplitPane2.setLeftComponent(jPanel8);

        jPanel10.setPreferredSize(new java.awt.Dimension(400, 400));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Map"));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout battleMapCoordsLayoutPanelLayout = new javax.swing.GroupLayout(battleMapCoordsLayoutPanel);
        battleMapCoordsLayoutPanel.setLayout(battleMapCoordsLayoutPanelLayout);
        battleMapCoordsLayoutPanelLayout.setHorizontalGroup(
            battleMapCoordsLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        battleMapCoordsLayoutPanelLayout.setVerticalGroup(
            battleMapCoordsLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(battleMapCoordsLayoutPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addComponent(battleMapViewPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(battleMapViewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(jPanel10);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        jSplitPane1.setTopComponent(jPanel15);
        jSplitPane1.setBottomComponent(console1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1194, 885));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportActionPerformed
        Path coordsPath = PathHelpers.getBasePath().resolve(fileButtonExportBattleCoords.getFilePath());
        if (!PathHelpers.createPathIfRequred(coordsPath)) return;
        try {
            battlemapcoordsManager.exportDisassembly(coordsPath, coords);
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Battle coords disasm could not be exported to : " + coordsPath);
        }
    }//GEN-LAST:event_jButtonExportActionPerformed

    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportActionPerformed
        Path mapEntriesPath = PathHelpers.getBasePath().resolve(fileButtonMapEntries.getFilePath());
        Path battleCoordsPath = PathHelpers.getBasePath().resolve(fileButtonImportBattleCoords.getFilePath());
        try {
            coords = battlemapcoordsManager.importDisassembly(battleCoordsPath);
            selectedCoords = 0;
            onDataLoaded();
            loadMap(0);
        } catch (Exception ex) {
            battlemapcoordsManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Battle coords disasm could not be imported from : " + battleCoordsPath);
            onDataLoaded();
        }
    }//GEN-LAST:event_jButtonImportActionPerformed
    
    private void loadMap(int index) {
        if (index < 0 || index >= coords.length) return;
        Path mapEntriesPath = PathHelpers.getBasePath().resolve(fileButtonMapEntries.getFilePath());
        Path paletteEntriesPath = PathHelpers.getBasePath().resolve(fileButtonPaletteEntries.getFilePath());
        Path tilesetEntriesPath = PathHelpers.getBasePath().resolve(fileButtonTilesetsEntries.getFilePath());
        int mapId = -1;
        try {
            mapId = coords[index].getMapIndex();
            battlemapcoordsManager.setCoords(coords);
            battlemapcoordsManager.importMapFromEntries(paletteEntriesPath, tilesetEntriesPath, mapEntriesPath, mapId);
        } catch (Exception ex) {
            battlemapcoordsManager.setMapLayout(null);
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe(String.format("ERROR Battle map disasm could not be imported for map%02d", mapId));
        }
        selectedCoords = index;
        UpdateMapLoaded();
    }
    
    private void onTableFrameDataChanged(TableModelEvent e) {
        int row = tableCoords.jTable.getSelectedRow();
        if (e.getType() == TableModelEvent.DELETE) {
            if (selectedCoords >= coords.length) {
                selectedCoords = coords.length-1;
            }
            if (selectedCoords >= 0) {
                loadMap(selectedCoords);
            }
        } else if ((row != -1 && row == selectedCoords)) {
            if (e.getColumn() == 1) {
                loadMap(row);
            } else {
                battleMapCoordsLayoutPanel.redraw();
            }
        }
    }

    private void onTableFrameSelectionChanged(ListSelectionEvent e) {
        if (ActionManager.isActionTriggering()) return;
        int row = tableCoords.jTable.getSelectedRow();
        if (row == -1) {
            coords = battleMapCoordsTableModel.getTableData(BattleMapCoords[].class);
            actionMapLoaded(null);
        } else if (!e.getValueIsAdjusting()) {
            loadMap(row);
        }
    }
    
    /**
     * To create a new Main Editor, copy the below code
     * Don't forget to change the new main class (below)
     */
    public static void main(String args[]) {
        AbstractMainEditor.programSetup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleCoordsMainEditor().setVisible(true);  // <------ Change this class to new Main Editor class
            }
        });
    }
    /**
     * To create a new Main Editor, copy the above code
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.AccordionPanel accordionPanel1;
    private com.sfc.sf2.battle.mapcoords.gui.BattleMapCoordsLayoutPanel battleMapCoordsLayoutPanel;
    private com.sfc.sf2.battle.mapcoords.models.BattleMapCoordsTableModel battleMapCoordsTableModel;
    private com.sfc.sf2.battle.mapcoords.gui.BattleMapViewPanel battleMapViewPanel1;
    private com.sfc.sf2.core.gui.controls.Console console1;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportBattleCoords;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportBattleCoords;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonMapEntries;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonPaletteEntries;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonTilesetsEntries;
    private javax.swing.JButton jButtonExport;
    private javax.swing.JButton jButtonImport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private com.sfc.sf2.core.gui.controls.Table tableCoords;
    // End of variables declaration//GEN-END:variables
}
