/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.ground.gui;

import com.sfc.sf2.core.gui.controls.AbstractViewPanel;
import com.sfc.sf2.ground.Ground;
import com.sfc.sf2.ground.GroundManager;
import com.sfc.sf2.palette.Palette;
import java.awt.event.ActionEvent;

/**
 *
 * @author TiMMy
 */
public class GroundViewPanel extends AbstractViewPanel<GroundLayoutPanel> {

    /**
     * Creates new form ViewPanel
     */
    public GroundViewPanel() {
        super();
        initComponents();
        init(jComboBoxScale, jCheckBoxGrid, null, colorPickerBG);
        
        paletteButtonRecolor.setupPaletteButton(() -> {
            Ground ground = layoutPanel.getGround();
            return ground == null ? null : ground.getPalette();
        }, this::onPaletteColorChange, GroundManager.PALETTE_INSERT_TO);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBG = new javax.swing.JLabel();
        colorPickerBG = new com.sfc.sf2.core.gui.controls.ColorPicker();
        jCheckBoxGrid = new javax.swing.JCheckBox();
        jLabelScale = new javax.swing.JLabel();
        jComboBoxScale = new javax.swing.JComboBox<>();
        paletteButtonRecolor = new com.sfc.sf2.palette.gui.controls.PaletteButton();
        jLabelRecolor = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("View"));

        jLabelBG.setText("BG :");

        colorPickerBG.setName("BG Color Picker"); // NOI18N
        colorPickerBG.addColorChangedListener(new com.sfc.sf2.core.gui.controls.ColorPicker.ColorChangedListener() {
            public void colorChanged(java.awt.event.ActionEvent evt) {
                colorPickerBGColorChanged(evt);
            }
        });

        javax.swing.GroupLayout colorPickerBGLayout = new javax.swing.GroupLayout(colorPickerBG);
        colorPickerBG.setLayout(colorPickerBGLayout);
        colorPickerBGLayout.setHorizontalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        colorPickerBGLayout.setVerticalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jCheckBoxGrid.setText("Show grid");
        jCheckBoxGrid.setName("Grid Toggle"); // NOI18N
        jCheckBoxGrid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxGridItemStateChanged(evt);
            }
        });

        jLabelScale.setText("Scale :");

        jComboBoxScale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/8x" }));
        jComboBoxScale.setName("Scale Combo"); // NOI18N
        jComboBoxScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxScaleActionPerformed(evt);
            }
        });

        paletteButtonRecolor.setName(""); // NOI18N

        jLabelRecolor.setText("Recolor :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jCheckBoxGrid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelScale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelBG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelRecolor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paletteButtonRecolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCheckBoxGrid)
                    .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelScale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelBG)
                    .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paletteButtonRecolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRecolor))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorPickerBGColorChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorPickerBGColorChanged
        super.onBGColorChanged(evt);
    }//GEN-LAST:event_colorPickerBGColorChanged

    private void jComboBoxScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxScaleActionPerformed
        super.onScaleChanged(evt);
    }//GEN-LAST:event_jComboBoxScaleActionPerformed

    private void jCheckBoxGridItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxGridItemStateChanged
        super.onGridChanged(evt);
    }//GEN-LAST:event_jCheckBoxGridItemStateChanged
    
    private void onPaletteColorChange(ActionEvent e) {
        Palette palette = (Palette)e.getSource();
        if (palette == null) return;
        Ground ground = layoutPanel.getGround();
        if (ground == null) return;
        palette.rebuildIcm();
        ground.getTileset().clearIndexedColorImage(true);
        layoutPanel.redraw();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.ColorPicker colorPickerBG;
    private javax.swing.JCheckBox jCheckBoxGrid;
    private javax.swing.JComboBox<String> jComboBoxScale;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JLabel jLabelRecolor;
    private javax.swing.JLabel jLabelScale;
    private com.sfc.sf2.palette.gui.controls.PaletteButton paletteButtonRecolor;
    // End of variables declaration//GEN-END:variables
}
