version: 1.6.0
release-notes:
v1.6.0: Added undo/redo feature.
v1.5.5: Added help menu with discord and GitHub links. More (?) buttons for info.
v1.5.4: Smoother input for selecting palette items.
v1.5.3: Force all (disasm) colors to be CRAM colors.
v1.5.2: Small bug fix for null errors. Added info on CRAM color.
