/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sfc.sf2.text.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.NonCombinableAction;
import com.sfc.sf2.core.gui.AbstractMainEditor;
import com.sfc.sf2.core.gui.controls.Console;
import com.sfc.sf2.helpers.PathHelpers;
import com.sfc.sf2.helpers.listeners.ListenersHelpers;
import com.sfc.sf2.text.TextManager;
import com.sfc.sf2.text.compression.Symbols;
import java.awt.Rectangle;
import java.beans.PropertyChangeEvent;
import java.io.File;
import java.nio.file.Path;
import java.util.logging.Level;
import javax.swing.DefaultCellEditor;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.TableModelEvent;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author wiz
 */
public class TextMainEditor extends AbstractMainEditor {
    
    private final TextManager textManager = new TextManager();
    TableRowSorter<TableModel> sorter;
    
    public TextMainEditor() {
        super();
        initComponents();
        initCore(console1);
        
        //Handle old Ascii map path and new path
        File file = PathHelpers.getBasePath().resolve("asciitotextsymbolmap.asm").toFile();
        if (file.exists()) {
            fileButtonImportAsciiTable.setFilePath(file.toString());
        }
    }
    
    @Override
    protected void initEditor() {
        super.initEditor();
        
        accordionPanel2.setExpanded(false);
        
        sorter = new TableRowSorter<>(textTableModel);
        tableText.jTable.setRowSorter(sorter);
        tableText.addListSelectionListener(this::onSelectionChanged);
        tableText.addTableModelListener(this::onTableDataChanged);
        tableText.jTable.addPropertyChangeListener("tableCellEditor", this::onTableEditorStarted);
        TableColumnModel columns = tableText.jTable.getColumnModel();
        columns.getColumn(0).setMaxWidth(50);
        columns.getColumn(1).setMaxWidth(50);
        
        ListenersHelpers.addTextFieldChangeListener(jTextFieldFilter, this::onFilterChanged);
    }
    
    @Override
    protected void onDataLoaded() {
        super.onDataLoaded();
        textPreviewLayoutPanel.setBaseTiles(textManager.getBaseTiles());
        textPreviewLayoutPanel.setFontSymbols(textManager.getFontSymbols());
        textPreviewLayoutPanel.setAllyNames(textManager.getAllyNames());
        ActionManager.setAndExecuteAction(new NonCombinableAction<String[]>(this, "Game Script Imported", this::actionScriptLoaded, textManager.getGameScript(), textTableModel.getTableData(String[].class)));
    }
    
    private void actionScriptLoaded(String[] script) {
        textTableModel.setTableData(script);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textTableModel = new com.sfc.sf2.text.models.TextTableModel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel16 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel17 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        accordionPanel2 = new com.sfc.sf2.core.gui.controls.AccordionPanel();
        fileButtonImportBasePalette = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonImportBaseTiles = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonImportVWFont = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonImportAsciiTable = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonImportAllyNames = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonImportAsciiReplace = new com.sfc.sf2.core.gui.controls.FileButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        infoButton3 = new com.sfc.sf2.core.gui.controls.InfoButton();
        directoryButtonImportBanks = new com.sfc.sf2.core.gui.controls.DirectoryButton();
        jButtonImportBanks = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        infoButton4 = new com.sfc.sf2.core.gui.controls.InfoButton();
        fileButtonImportText = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonImportText = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        infoButton5 = new com.sfc.sf2.core.gui.controls.InfoButton();
        fileButtonImportAsm = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonImportAsm = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        infoButton6 = new com.sfc.sf2.core.gui.controls.InfoButton();
        directoryButtonExportBanks = new com.sfc.sf2.core.gui.controls.DirectoryButton();
        jButtonExportBanks = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        infoButton7 = new com.sfc.sf2.core.gui.controls.InfoButton();
        fileButtonExportText = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonExportText = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        textPreviewLayoutPanel = new com.sfc.sf2.text.gui.TextPreviewLayoutPanel();
        jPanel8 = new javax.swing.JPanel();
        jButtonDown1 = new javax.swing.JButton();
        jButtonUp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldFilter = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldJumpTo = new javax.swing.JTextField();
        infoButton1 = new com.sfc.sf2.core.gui.controls.InfoButton();
        infoButton2 = new com.sfc.sf2.core.gui.controls.InfoButton();
        tableText = new com.sfc.sf2.core.gui.controls.Table();
        console1 = new com.sfc.sf2.core.gui.controls.Console();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SF2TextManager");
        setMinimumSize(new java.awt.Dimension(1030, 710));

        jSplitPane1.setDividerLocation(550);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane2.setDividerLocation(450);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Import from :"));
        jPanel3.setPreferredSize(new java.awt.Dimension(590, 135));

        accordionPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview"));

        fileButtonImportBasePalette.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonImportBasePalette.setFilePath("..\\..\\graphics\\tech\\basepalette.bin");
        fileButtonImportBasePalette.setInfoMessage("The game's base palette.");
        fileButtonImportBasePalette.setLabelText("Base palette :");
        fileButtonImportBasePalette.setName("Import Base Palette"); // NOI18N

        fileButtonImportBaseTiles.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonImportBaseTiles.setFilePath("..\\..\\graphics\\tech\\basetiles.bin");
        fileButtonImportBaseTiles.setInfoMessage("The tileset that contains the dialog box frame.");
        fileButtonImportBaseTiles.setLabelText("Base tiles :");
        fileButtonImportBaseTiles.setName("Import Base Tiles"); // NOI18N

        fileButtonImportVWFont.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonImportVWFont.setFilePath("..\\..\\graphics\\tech\\fonts\\variablewidthfont.bin");
        fileButtonImportVWFont.setInfoMessage("<html>Loads in the games <i>variable width font</i> for rendering in the preview</html>");
        fileButtonImportVWFont.setLabelText("VW font :");
        fileButtonImportVWFont.setName("Import VW Font"); // NOI18N

        fileButtonImportAsciiTable.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonImportAsciiTable.setFilePath("..\\..\\..\\code\\common\\scripting\\text\\textfunctions.asm");
        fileButtonImportAsciiTable.setInfoMessage("<html>Loads in <i>table_666E</i> from <i>textfunctions.asm</i>, so that ASCII characters (raw text) can be converted into VWFont symbols.</html>");
        fileButtonImportAsciiTable.setLabelText("ASCII table :");
        fileButtonImportAsciiTable.setName("Import ASCII Table"); // NOI18N

        fileButtonImportAllyNames.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
        fileButtonImportAllyNames.setFilePath("..\\..\\stats\\allies\\allynames.asm");
        fileButtonImportAllyNames.setInfoMessage("<html>Imports the namelist for allies to replace the {LEADER} and {NAME;x} tag in the preview.<br>Load <i>allynames.asm</i> or <i>allynames-capitalized.asm</i></html>");
        fileButtonImportAllyNames.setLabelText("Ally names :");
        fileButtonImportAllyNames.setName("Import Ally Names"); // NOI18N

        fileButtonImportAsciiReplace.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.TXT);
        fileButtonImportAsciiReplace.setFilePath(".\\ascii-replace.txt");
        fileButtonImportAsciiReplace.setInfoMessage("<html>The <i>ascii replace</i> provides some support for non-ascii characters.<br>Refer to the file.</html>");
        fileButtonImportAsciiReplace.setLabelText("ASCII replace :");
        fileButtonImportAsciiReplace.setName("Import ASCII Replace"); // NOI18N

        javax.swing.GroupLayout accordionPanel2Layout = new javax.swing.GroupLayout(accordionPanel2);
        accordionPanel2.setLayout(accordionPanel2Layout);
        accordionPanel2Layout.setHorizontalGroup(
            accordionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accordionPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accordionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonImportBasePalette, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonImportBaseTiles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonImportVWFont, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonImportAsciiTable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonImportAsciiReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fileButtonImportAllyNames, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        accordionPanel2Layout.setVerticalGroup(
            accordionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accordionPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileButtonImportBasePalette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportBaseTiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportVWFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportAsciiTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportAsciiReplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportAllyNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Import script disassembly from directory.");

        infoButton3.setMessageText("<html>Select a disassembly's \"textbanks\" directory, with following files :<br>huffmantreeoffsets.bin, huffmantrees.bin, and all textbankXX.bin files<br>Base path can end with an optional filename prefix.</html>");
        infoButton3.setText("");

        directoryButtonImportBanks.setDirectoryPath(".\\");
            directoryButtonImportBanks.setInfoMessage("");
            directoryButtonImportBanks.setLabelText("Base path :");
            directoryButtonImportBanks.setName("Import Textbanks"); // NOI18N

            jButtonImportBanks.setText("Import");
            jButtonImportBanks.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonImportBanksActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(directoryButtonImportBanks, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButtonImportBanks))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(infoButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(infoButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(directoryButtonImportBanks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonImportBanks)
                    .addContainerGap())
            );

            jTabbedPane1.addTab("Disassembly", jPanel4);

            jLabel3.setText("Import script from text file.");

            infoButton4.setMessageText("<html>Text file must have one of the following formats on each line:<br>- \"Id=line\"<br> or \"id=hex=line\"<br>Where \"id\" is the decimal index of the line, \"hex\" is the hex index of the line, and \"line\" is the line of text.</html>");
            infoButton4.setText("");

            fileButtonImportText.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.TXT);
            fileButtonImportText.setFilePath(".\\export\\gamescript.txt");
            fileButtonImportText.setInfoMessage("");
            fileButtonImportText.setLabelText("Txt game script :");
            fileButtonImportText.setMaximumSize(new java.awt.Dimension(32859, 25));
            fileButtonImportText.setName("Import Text File"); // NOI18N

            jButtonImportText.setText("Import");
            jButtonImportText.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonImportTextActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
            jPanel9.setLayout(jPanel9Layout);
            jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButtonImportText))
                        .addComponent(fileButtonImportText, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(infoButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(infoButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fileButtonImportText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonImportText)
                    .addContainerGap())
            );

            jTabbedPane1.addTab("TXT", jPanel9);

            jLabel13.setText("Import from asm code.");

            infoButton5.setMessageText("<html>Parses the \"txt\" commands of an assembly code file.<br/>Parsed text commands will update currently loaded script.</html>");
            infoButton5.setText("");

            fileButtonImportAsm.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ASM);
            fileButtonImportAsm.setFilePath("..\\map\\cs_intro1.asm");
            fileButtonImportAsm.setInfoMessage("");
            fileButtonImportAsm.setLabelText("ASM file :");
            fileButtonImportAsm.setMaximumSize(new java.awt.Dimension(32859, 25));
            fileButtonImportAsm.setName("Import Dialog ASM"); // NOI18N

            jButtonImportAsm.setText("Import");
            jButtonImportAsm.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonImportAsmActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fileButtonImportAsm, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButtonImportAsm))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(infoButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(infoButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fileButtonImportAsm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonImportAsm)
                    .addContainerGap())
            );

            jTabbedPane1.addTab("ASM", jPanel2);

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(accordionPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(accordionPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Export to :"));
            jPanel5.setPreferredSize(new java.awt.Dimension(32, 135));

            jLabel1.setText("Export script disassemblies.");

            infoButton6.setMessageText("<html<Will create new files : huffmantreeoffsets.bin, huffmantrees.bin, all textbankXX.bin files<br>Base path can end with an optional filename prefix.</html>");
            infoButton6.setText("");

            directoryButtonExportBanks.setDirectoryPath(".\\");
                directoryButtonExportBanks.setInfoMessage("");
                directoryButtonExportBanks.setLabelText("Base path :");
                directoryButtonExportBanks.setName("Export Textbanks"); // NOI18N

                jButtonExportBanks.setText("Export");
                jButtonExportBanks.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonExportBanksActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
                jPanel11.setLayout(jPanel11Layout);
                jPanel11Layout.setHorizontalGroup(
                    jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(directoryButtonExportBanks, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonExportBanks))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                );
                jPanel11Layout.setVerticalGroup(
                    jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(directoryButtonExportBanks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExportBanks)
                        .addContainerGap())
                );

                jTabbedPane2.addTab("Disassembly", jPanel11);

                jLabel9.setText("Export script as text file.");

                infoButton7.setMessageText("<html>Exports a new text file. File will be formated as: \"id=hex=line\"<br>Where \"id\" is the decimal index of the line, \"hex\" is the hex index of the line, and \"line\" is the line of text.</html>");
                infoButton7.setText("");

                fileButtonExportText.setFilePath(".\\export\\gamescript.txt");
                fileButtonExportText.setLabelText("Txt game script :");
                fileButtonExportText.setMaximumSize(new java.awt.Dimension(32859, 25));
                fileButtonExportText.setName("Export Text File"); // NOI18N

                jButtonExportText.setText("Export");
                jButtonExportText.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonExportTextActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
                jPanel14.setLayout(jPanel14Layout);
                jPanel14Layout.setHorizontalGroup(
                    jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileButtonExportText, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonExportText))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                );
                jPanel14Layout.setVerticalGroup(
                    jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileButtonExportText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExportText)
                        .addContainerGap())
                );

                jTabbedPane2.addTab("TXT", jPanel14);

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane2)
                        .addContainerGap())
                );
                jPanel5Layout.setVerticalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, Short.MAX_VALUE)
                        .addContainerGap())
                );

                javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
                jPanel17.setLayout(jPanel17Layout);
                jPanel17Layout.setHorizontalGroup(
                    jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                        .addContainerGap())
                );
                jPanel17Layout.setVerticalGroup(
                    jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                );

                jSplitPane2.setLeftComponent(jPanel17);

                jPanel18.setPreferredSize(new java.awt.Dimension(617, 540));

                jPanel10.setMinimumSize(new java.awt.Dimension(262, 84));
                jPanel10.setPreferredSize(new java.awt.Dimension(557, 153));

                jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview"));
                jPanel7.setMaximumSize(null);
                jPanel7.setMinimumSize(new java.awt.Dimension(262, 74));
                jPanel7.setPreferredSize(new java.awt.Dimension(464, 163));

                textPreviewLayoutPanel.setMinimumSize(new java.awt.Dimension(232, 64));

                javax.swing.GroupLayout textPreviewLayoutPanelLayout = new javax.swing.GroupLayout(textPreviewLayoutPanel);
                textPreviewLayoutPanel.setLayout(textPreviewLayoutPanelLayout);
                textPreviewLayoutPanelLayout.setHorizontalGroup(
                    textPreviewLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 391, Short.MAX_VALUE)
                );
                textPreviewLayoutPanelLayout.setVerticalGroup(
                    textPreviewLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 139, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                    jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textPreviewLayoutPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel7Layout.setVerticalGroup(
                    jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textPreviewLayoutPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));

                jButtonDown1.setText("\\/");
                jButtonDown1.setMargin(new java.awt.Insets(2, 2, 2, 2));
                jButtonDown1.setPreferredSize(new java.awt.Dimension(26, 26));
                jButtonDown1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonDown1ActionPerformed(evt);
                    }
                });

                jButtonUp.setText("/\\");
                    jButtonUp.setMargin(new java.awt.Insets(2, 2, 2, 2));
                    jButtonUp.setPreferredSize(new java.awt.Dimension(26, 26));
                    jButtonUp.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButtonUpActionPerformed(evt);
                        }
                    });

                    jLabel4.setText("Txt lines :");

                    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                    jPanel8.setLayout(jPanel8Layout);
                    jPanel8Layout.setHorizontalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonDown1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );
                    jPanel8Layout.setVerticalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addContainerGap(76, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonDown1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap())
                    );

                    javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
                    jPanel10.setLayout(jPanel10Layout);
                    jPanel10Layout.setHorizontalGroup(
                        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    );
                    jPanel10Layout.setVerticalGroup(
                        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    );

                    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Text"));

                    jLabel10.setText("Filter :");

                    jLabel11.setText("Jump to :");

                    jTextFieldJumpTo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
                    jTextFieldJumpTo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jTextFieldJumpToActionPerformed(evt);
                        }
                    });

                    infoButton1.setMessageText("<html>Filters the textbank by the text entered<br>Filter text is not case-sensitive.<br>Filter supports REGEX.</html>");
                    infoButton1.setText("");

                    infoButton2.setMessageText("<html>Enter a value and press <b>enter</b> to jump to the corresponding <i>Id</i> or <i>Hex Id</i>.<br>Where a value corresponds to both an <i>Id</i> and <i>Hex Id</i>, press <b>enter</b> several times to toggle between the two.</html>");
                    infoButton2.setText("");

                    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                    jPanel6.setLayout(jPanel6Layout);
                    jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldJumpTo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(infoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(infoButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0))
                    );
                    jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(infoButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(infoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldJumpTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))
                    );

                    tableText.setBorder(javax.swing.BorderFactory.createTitledBorder("Textbank"));
                    tableText.setModel(textTableModel);
                    tableText.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
                    tableText.setSingleClickText(true);
                    tableText.setName("Text Banks Table"); // NOI18N

                    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                    jPanel1.setLayout(jPanel1Layout);
                    jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tableText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap())
                    );
                    jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, 0)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tableText, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addContainerGap())
                    );

                    javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
                    jPanel18.setLayout(jPanel18Layout);
                    jPanel18Layout.setHorizontalGroup(
                        jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel18Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap())
                    );
                    jPanel18Layout.setVerticalGroup(
                        jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                    );

                    jSplitPane2.setRightComponent(jPanel18);

                    javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
                    jPanel16.setLayout(jPanel16Layout);
                    jPanel16Layout.setHorizontalGroup(
                        jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1024, Short.MAX_VALUE)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSplitPane2))
                    );
                    jPanel16Layout.setVerticalGroup(
                        jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 550, Short.MAX_VALUE)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSplitPane2))
                    );

                    jSplitPane1.setTopComponent(jPanel16);
                    jSplitPane1.setBottomComponent(console1);

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                    getContentPane().setLayout(layout);
                    layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jSplitPane1)
                            .addContainerGap())
                    );
                    layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                    );

                    setSize(new java.awt.Dimension(1046, 718));
                    setLocationRelativeTo(null);
                }// </editor-fold>//GEN-END:initComponents

    private void jButtonExportBanksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportBanksActionPerformed
        Path basePath = PathHelpers.getBasePath().resolve(directoryButtonExportBanks.getDirectoryPath());
        if (!PathHelpers.createPathIfRequred(basePath)) return;
        try {
            String[] data = textTableModel.getTableData(String[].class);
            textManager.exportDisassembly(basePath, data);
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Text disasms could not be exported to : " + basePath);
        }
    }//GEN-LAST:event_jButtonExportBanksActionPerformed

    private void jButtonExportTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportTextActionPerformed
        Path textPath = PathHelpers.getBasePath().resolve(fileButtonExportText.getFilePath());
        if (!PathHelpers.createPathIfRequred(textPath)) return;
        try {
            String[] data = textTableModel.getTableData(String[].class);
            textManager.exportTxt(textPath, data);
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Text file could not be exported to : " + textPath);
        }
    }//GEN-LAST:event_jButtonExportTextActionPerformed

    private void jButtonImportTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportTextActionPerformed
        Path textPath = PathHelpers.getBasePath().resolve(fileButtonImportText.getFilePath());
        try {
            importAsciiMapping();
            importPreviewResources();
            textManager.importTxt(textPath);
        } catch (Exception ex) {
            textManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Text file could not be imported from : " + textPath);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportTextActionPerformed

    private void jButtonImportBanksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportBanksActionPerformed
        Path basePath = PathHelpers.getBasePath().resolve(directoryButtonImportBanks.getDirectoryPath());
        try {
            importAsciiMapping();
            importPreviewResources();
            textManager.importDisassembly(basePath);
        } catch (Exception ex) {
            textManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Text disasms could not be imported from : " + basePath);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportBanksActionPerformed

    private void jButtonImportAsmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportAsmActionPerformed
        Path asmPath = PathHelpers.getBasePath().resolve(fileButtonImportAsm.getFilePath());
        try {
            textManager.importAsm(asmPath);
        } catch (Exception ex) {
            textManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Text ASM could not be imported from : " + asmPath);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportAsmActionPerformed

    private void jTextFieldJumpToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJumpToActionPerformed
        String text = jTextFieldJumpTo.getText();
        int foundId = -1;
        try {
            foundId = Integer.parseInt(text);
        } catch (NumberFormatException e) { }
        if (foundId == -1 || tableText.jTable.getSelectedRow() == foundId) {    //If decimal value not found or if selection is already at decimal value
            try {
                foundId = Integer.parseInt(text, 16);
            } catch (NumberFormatException e) { }
        }
        if (foundId != -1 && textTableModel.getRowCount() > foundId) {
            tableText.jTable.setRowSelectionInterval(foundId, foundId);
            tableText.jTable.scrollRectToVisible(new Rectangle(tableText.jTable.getCellRect(foundId, 2, true)));
        }
    }//GEN-LAST:event_jTextFieldJumpToActionPerformed

    private void jButtonDown1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDown1ActionPerformed
        if (textPreviewLayoutPanel.hasLinesBelow()) {
            textPreviewLayoutPanel.setLinesOffset(textPreviewLayoutPanel.getLinesOffset()+1);
        }
    }//GEN-LAST:event_jButtonDown1ActionPerformed

    private void jButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpActionPerformed
        if (textPreviewLayoutPanel.hasLinesAbove()) {
            textPreviewLayoutPanel.setLinesOffset(textPreviewLayoutPanel.getLinesOffset()-1);
        }
    }//GEN-LAST:event_jButtonUpActionPerformed

    private void importAsciiMapping() throws Exception {
        Path asciiTablePath = PathHelpers.getBasePath().resolve(fileButtonImportAsciiTable.getFilePath());
        Path asciiReplacePath = PathHelpers.getBasePath().resolve(fileButtonImportAsciiReplace.getFilePath());
        try {   //Optional
            textManager.importAsciiReplaceMap(asciiReplacePath);
            Symbols.setReplaceMap(textManager.getAsciiReplaceMap());
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().warning("WARNING Ascii replacer table could not be imported from : " + asciiReplacePath);
        }
        try {   //ASCII map is no longer optional
            textManager.importAsciiMap(asciiTablePath);
            Symbols.setImportedTable(textManager.getAsciiToSymbolMap());
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Ascii table asm could not be imported from : " + asciiTablePath);
            throw ex;
        }
    }
    
    private void importPreviewResources() {
        Path basePalettePath = PathHelpers.getBasePath().resolve(fileButtonImportBasePalette.getFilePath());
        Path baseTilesPath = PathHelpers.getBasePath().resolve(fileButtonImportBaseTiles.getFilePath());
        Path vwFontPath = PathHelpers.getBasePath().resolve(fileButtonImportVWFont.getFilePath());
        Path allyNamesPath = PathHelpers.getBasePath().resolve(fileButtonImportAllyNames.getFilePath());
        try {   //Optional
            textManager.importBaseTiles(basePalettePath, baseTilesPath);
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().warning("WARNING Base tiles disasms could not be imported from : " + baseTilesPath);
        }
        try {   //Optional
            textManager.importVWFonts(vwFontPath);
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().warning("WARNING VWFont disasms could not be imported from : " + vwFontPath);
        }
        try {   //Optional
            textManager.importAllyNames(allyNamesPath);
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().warning("WARNING Ally names asm could not be imported from : " + allyNamesPath);
        }
    }
    
    private void onFilterChanged(ChangeEvent e) {
        int selected = -1;
        int row = tableText.jTable.getSelectedRow();
        if (row != -1) {
            selected = tableText.jTable.convertRowIndexToModel(row);
        }
        String text = ((JTextField)e.getSource()).getText();
        filterRows(text);
        if (selected != -1) {
            selected = tableText.jTable.convertRowIndexToView(selected);
            tableText.jTable.scrollRectToVisible(new Rectangle(tableText.jTable.getCellRect(selected, 2, true)));
        }
    }
    
    private void filterRows(String filter) {
        RowFilter<TableModel, Object> rf = null;
        //If current expression doesn't parse, don't update.
        try {
            rf = RowFilter.regexFilter("(?i)"+filter, 2);
        } catch (java.util.regex.PatternSyntaxException e) {
            return;
        }
        sorter.setRowFilter(rf);
    }
    
    private void onSelectionChanged(ListSelectionEvent e) {
        int row = tableText.jTable.getSelectedRow();
        if (row == -1) {
            textPreviewLayoutPanel.setText(null);
        } else {
            textPreviewLayoutPanel.setText((String)tableText.jTable.getValueAt(row, 2));
        }
    }
    
    private void onTableDataChanged(TableModelEvent e) {
        int row = tableText.jTable.getSelectedRow();
        if (row == -1) {
            textPreviewLayoutPanel.setText(null);
        } else {
            textPreviewLayoutPanel.setText(textTableModel.getRow(row));
        }
    }
    
    private void onTableEditorStarted(PropertyChangeEvent evt) {
        TableCellEditor editor = tableText.jTable.getCellEditor();
        if (editor != null && editor instanceof DefaultCellEditor) {
            JTextField textEditor = (JTextField)((DefaultCellEditor)editor).getComponent();
            ListenersHelpers.addTextFieldChangeListener(textEditor, new ChangeListener() {
                @Override
                public void stateChanged(ChangeEvent e) {
                    String text = ((JTextField)e.getSource()).getText();
                    textPreviewLayoutPanel.setText(text);
                }
            });
        }
    }
    
    /**
     * To create a new Main Editor, copy the below code
     * Don't forget to change the new main class (below)
     */
    public static void main(String args[]) {
        AbstractMainEditor.programSetup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextMainEditor().setVisible(true);  // <------ Change this class to new Main Editor class
            }
        });
    }
    /**
     * To create a new Main Editor, copy the above code
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.AccordionPanel accordionPanel2;
    private com.sfc.sf2.core.gui.controls.Console console1;
    private com.sfc.sf2.core.gui.controls.DirectoryButton directoryButtonExportBanks;
    private com.sfc.sf2.core.gui.controls.DirectoryButton directoryButtonImportBanks;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportText;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportAllyNames;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportAsciiReplace;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportAsciiTable;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportAsm;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportBasePalette;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportBaseTiles;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportText;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportVWFont;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton1;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton2;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton3;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton4;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton5;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton6;
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton7;
    private javax.swing.JButton jButtonDown1;
    private javax.swing.JButton jButtonExportBanks;
    private javax.swing.JButton jButtonExportText;
    private javax.swing.JButton jButtonImportAsm;
    private javax.swing.JButton jButtonImportBanks;
    private javax.swing.JButton jButtonImportText;
    private javax.swing.JButton jButtonUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldFilter;
    private javax.swing.JTextField jTextFieldJumpTo;
    private com.sfc.sf2.core.gui.controls.Table tableText;
    private com.sfc.sf2.text.gui.TextPreviewLayoutPanel textPreviewLayoutPanel;
    private com.sfc.sf2.text.models.TextTableModel textTableModel;
    // End of variables declaration//GEN-END:variables
}
