/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.spellAnimation.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.ComboAction;
import com.sfc.sf2.core.actions.SpinnerAction;
import com.sfc.sf2.core.actions.ToggleAction;
import com.sfc.sf2.core.gui.controls.AbstractViewPanel;
import com.sfc.sf2.spellAnimation.SpellSubAnimation;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author TiMMy
 */
public class SpellAnimationViewPanel extends AbstractViewPanel<SpellAnimationLayoutPanel> {

    /**
     * Creates new form ViewPanel
     */
    public SpellAnimationViewPanel() {
        super();
        initComponents();
        init(jComboBoxScale, null, null, null);
    }
    
    public void setSubAnimationsList(SpellSubAnimation[] subAnimations) {
        String[] names = new String[subAnimations.length];
        for (int i = 0; i < names.length; i++) {
            names[i] = subAnimations[i].getName();
        }
        jComboBoxAnim.setModel(new DefaultComboBoxModel<>(names));
        jComboBoxAnim.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelScale = new javax.swing.JLabel();
        jComboBoxScale = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxAnim = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSpinnerAnimFrame = new javax.swing.JSpinner();
        jCheckBoxAnimate = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("View"));

        jLabelScale.setText("Scale :");

        jComboBoxScale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/8x" }));
        jComboBoxScale.setName("View Scale Combo"); // NOI18N
        jComboBoxScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxScaleActionPerformed(evt);
            }
        });

        jLabel8.setText("Animation :");

        jComboBoxAnim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAnim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAnimItemStateChanged(evt);
            }
        });

        jLabel9.setText("Anim frame :");

        jSpinnerAnimFrame.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerAnimFrame.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerAnimFrameStateChanged(evt);
            }
        });

        jCheckBoxAnimate.setText("Animate");
        jCheckBoxAnimate.setActionCommand("Animate spell");
        jCheckBoxAnimate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAnimateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxAnim, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerAnimFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxAnimate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabelScale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelScale)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel8)
                        .addComponent(jComboBoxAnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerAnimFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jCheckBoxAnimate)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxScaleActionPerformed
        super.onScaleChanged(evt);
    }//GEN-LAST:event_jComboBoxScaleActionPerformed

    private void jComboBoxAnimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAnimItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ComboAction(jComboBoxAnim, (int)jComboBoxAnim.getSelectedIndex(), layoutPanel.getSubAnimationIndex()));
        }
        layoutPanel.setSubAnimationIndex(jComboBoxAnim.getSelectedIndex());
    }//GEN-LAST:event_jComboBoxAnimItemStateChanged

    private void jSpinnerAnimFrameStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerAnimFrameStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new SpinnerAction(jSpinnerAnimFrame, jSpinnerAnimFrame.getValue(), layoutPanel.getAnimator().getFrame()));
        }
        layoutPanel.getAnimator().setFrame((int)jSpinnerAnimFrame.getValue());
    }//GEN-LAST:event_jSpinnerAnimFrameStateChanged

    private void jCheckBoxAnimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAnimateActionPerformed
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxAnimate, jCheckBoxAnimate.isSelected()));
        }
        if (jCheckBoxAnimate.isSelected()) {
            if (layoutPanel.hasData()) {
                int speed = 1;//spellAnimationLayoutPanel.getSpellAnimation().getSpellSubAnimations()[0].getDuration();
                int frames = layoutPanel.getSpellAnimation().getSpellSubAnimations().length-1;
                layoutPanel.getAnimator().startAnimation(speed, frames, true, false);
            }
        } else {
            layoutPanel.getAnimator().stopAnimation();
        }
    }//GEN-LAST:event_jCheckBoxAnimateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxAnimate;
    private javax.swing.JComboBox<String> jComboBoxAnim;
    private javax.swing.JComboBox<String> jComboBoxScale;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelScale;
    private javax.swing.JSpinner jSpinnerAnimFrame;
    // End of variables declaration//GEN-END:variables
}
