/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.weaponsprite.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.ComboAction;
import com.sfc.sf2.core.gui.controls.AbstractViewPanel;
import javax.swing.JComboBox;

/**
 *
 * @author TiMMy
 */
public class WeaponSpriteViewPanel extends AbstractViewPanel<WeaponSpriteLayoutPanel> {
        
    /**
     * Creates new form ViewPanel
     */
    public WeaponSpriteViewPanel() {
        super();
        initComponents();
        init(jComboBoxScale, jCheckBoxGrid, null, colorPickerBG);
    }

    public JComboBox<String> getjComboBoxPalette() {
        return jComboBoxPalette;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBG = new javax.swing.JLabel();
        colorPickerBG = new com.sfc.sf2.core.gui.controls.ColorPicker();
        jCheckBoxGrid = new javax.swing.JCheckBox();
        jLabelScale = new javax.swing.JLabel();
        jComboBoxScale = new javax.swing.JComboBox<>();
        jComboBoxPalette = new javax.swing.JComboBox<>();
        jLabelPalette = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("View"));

        jLabelBG.setText("BG :");

        colorPickerBG.setName("BG Color Picker"); // NOI18N
        colorPickerBG.addColorChangedListener(new com.sfc.sf2.core.gui.controls.ColorPicker.ColorChangedListener() {
            public void colorChanged(java.awt.event.ActionEvent evt) {
                colorPickerBGColorChanged(evt);
            }
        });

        javax.swing.GroupLayout colorPickerBGLayout = new javax.swing.GroupLayout(colorPickerBG);
        colorPickerBG.setLayout(colorPickerBGLayout);
        colorPickerBGLayout.setHorizontalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        colorPickerBGLayout.setVerticalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jCheckBoxGrid.setLabel("Show Grid");
        jCheckBoxGrid.setName("Grid Toggle"); // NOI18N
        jCheckBoxGrid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxGridItemStateChanged(evt);
            }
        });

        jLabelScale.setText("Scale :");

        jComboBoxScale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/8x" }));
        jComboBoxScale.setName("View Scale Combo"); // NOI18N
        jComboBoxScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxScaleActionPerformed(evt);
            }
        });

        jComboBoxPalette.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        jComboBoxPalette.setName("Palette Combo"); // NOI18N
        jComboBoxPalette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaletteActionPerformed(evt);
            }
        });

        jLabelPalette.setText("Palette : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPalette)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxPalette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jCheckBoxGrid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelScale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelBG)
                    .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxGrid)
                    .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelScale)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jComboBoxPalette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPalette)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorPickerBGColorChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorPickerBGColorChanged
        super.onBGColorChanged(evt);
    }//GEN-LAST:event_colorPickerBGColorChanged

    private void jComboBoxScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxScaleActionPerformed
        super.onScaleChanged(evt);
    }//GEN-LAST:event_jComboBoxScaleActionPerformed

    private void jCheckBoxGridItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxGridItemStateChanged
        super.onGridChanged(evt);
    }//GEN-LAST:event_jCheckBoxGridItemStateChanged

    private void jComboBoxPaletteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaletteActionPerformed
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ComboAction(jComboBoxPalette, (int)jComboBoxPalette.getSelectedIndex(), layoutPanel.getPaletteIndex()));
        }
        if (layoutPanel != null) {
            layoutPanel.setPaletteIndex(jComboBoxPalette.getSelectedIndex());
        }
    }//GEN-LAST:event_jComboBoxPaletteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.ColorPicker colorPickerBG;
    private javax.swing.JCheckBox jCheckBoxGrid;
    private javax.swing.JComboBox<String> jComboBoxPalette;
    private javax.swing.JComboBox<String> jComboBoxScale;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JLabel jLabelPalette;
    private javax.swing.JLabel jLabelScale;
    // End of variables declaration//GEN-END:variables
}
