/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.map.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.BasicAction;
import com.sfc.sf2.core.actions.ToggleAction;
import com.sfc.sf2.core.gui.controls.AbstractViewPanel;
import com.sfc.sf2.core.settings.IViewSettings;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JCheckBox;

/**
 *
 * @author TiMMy
 */
public class MapViewPanel extends AbstractViewPanel<MapLayoutPanel> {
    
    private ActionListener animationToggleListener;
    
    /**
     * Creates new form ViewPanel
     */
    public MapViewPanel() {
        super();
        initComponents();
        init(jComboBoxScale, jCheckBoxGrid, null, colorPickerBG);
    }

    public void setLayoutPanel(MapLayoutPanel layoutPanel, ActionListener animationToggleListener, IViewSettings viewPanelSettings) {
        super.setLayoutPanel(layoutPanel, viewPanelSettings);
        this.animationToggleListener = animationToggleListener;
        
        layoutPanel.setShowPriority(jCheckBoxShowPriority.isSelected());
        layoutPanel.setShowExplorationFlags(jCheckBoxShowExplorationFlags.isSelected());
        layoutPanel.setShowInteractionFlags(false);
    }

    public JCheckBox getjCheckBoxShowExplorationFlags() {
        return jCheckBoxShowExplorationFlags;
    }

    public JCheckBox getjCheckBoxShowAreas() {
        return jCheckBoxShowAreas;
    }

    public JCheckBox getjCheckBoxShowFlagCopies() {
        return jCheckBoxShowFlagCopies;
    }

    public JCheckBox getjCheckBoxShowRoofCopies() {
        return jCheckBoxShowRoofCopies;
    }

    public JCheckBox getjCheckBoxShowStepCopies() {
        return jCheckBoxShowStepCopies;
    }

    public JCheckBox getjCheckBoxShowItems() {
        return jCheckBoxShowItems;
    }

    public JCheckBox getjCheckBoxShowPriority() {
        return jCheckBoxShowPriority;
    }

    public JCheckBox getjCheckBoxShowTriggers() {
        return jCheckBoxShowTriggers;
    }

    public JCheckBox getjCheckBoxShowVehicles() {
        return jCheckBoxShowVehicles;
    }

    public JCheckBox getjCheckBoxShowWarps() {
        return jCheckBoxShowWarps;
    }

    public JCheckBox getjCheckBoxPreviewAnim() {
        return jCheckBoxPreviewAnim;
    }
    
    public JCheckBox getCheckBoxPreviewAnim() {
        return jCheckBoxPreviewAnim;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBG = new javax.swing.JLabel();
        colorPickerBG = new com.sfc.sf2.core.gui.controls.ColorPicker();
        jCheckBoxGrid = new javax.swing.JCheckBox();
        jLabelScale = new javax.swing.JLabel();
        jComboBoxScale = new javax.swing.JComboBox<>();
        jCheckBoxShowPriority = new javax.swing.JCheckBox();
        jCheckBoxShowVehicles = new javax.swing.JCheckBox();
        jCheckBoxShowExplorationFlags = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBoxShowAreas = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        jCheckBoxShowFlagCopies = new javax.swing.JCheckBox();
        jCheckBoxShowStepCopies = new javax.swing.JCheckBox();
        jCheckBoxShowRoofCopies = new javax.swing.JCheckBox();
        jCheckBoxShowTriggers = new javax.swing.JCheckBox();
        jCheckBoxShowItems = new javax.swing.JCheckBox();
        jCheckBoxShowWarps = new javax.swing.JCheckBox();
        jCheckBoxPreviewAnim = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("View"));

        jLabelBG.setText("BG :");

        colorPickerBG.setName("BG Color Picker"); // NOI18N
        colorPickerBG.addColorChangedListener(new com.sfc.sf2.core.gui.controls.ColorPicker.ColorChangedListener() {
            public void colorChanged(java.awt.event.ActionEvent evt) {
                colorPickerBGColorChanged(evt);
            }
        });

        javax.swing.GroupLayout colorPickerBGLayout = new javax.swing.GroupLayout(colorPickerBG);
        colorPickerBG.setLayout(colorPickerBGLayout);
        colorPickerBGLayout.setHorizontalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        colorPickerBGLayout.setVerticalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jCheckBoxGrid.setText("Show grid");
        jCheckBoxGrid.setName("Grid Toggle"); // NOI18N
        jCheckBoxGrid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxGridItemStateChanged(evt);
            }
        });

        jLabelScale.setText("Scale :");

        jComboBoxScale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/8x" }));
        jComboBoxScale.setName("View Scale Combo"); // NOI18N
        jComboBoxScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxScaleActionPerformed(evt);
            }
        });

        jCheckBoxShowPriority.setText("Show priority");
        jCheckBoxShowPriority.setName("Priority Toggle"); // NOI18N
        jCheckBoxShowPriority.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxShowPriorityItemStateChanged(evt);
            }
        });

        jCheckBoxShowVehicles.setText("Vehicles");
        jCheckBoxShowVehicles.setActionCommand("0x800");
        jCheckBoxShowVehicles.setName("Vehicles Toggle"); // NOI18N
        jCheckBoxShowVehicles.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxViewItemStateChanged(evt);
            }
        });

        jCheckBoxShowExplorationFlags.setText("Exploration flags");
        jCheckBoxShowExplorationFlags.setName("Exploration Flags Toggle"); // NOI18N
        jCheckBoxShowExplorationFlags.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxShowExplorationFlagsItemStateChanged(evt);
            }
        });

        jCheckBoxShowAreas.setText("Areas");
        jCheckBoxShowAreas.setActionCommand("0x8");
        jCheckBoxShowAreas.setName("Areas Toggle"); // NOI18N
        jCheckBoxShowAreas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxViewItemStateChanged(evt);
            }
        });

        jCheckBoxShowFlagCopies.setText("Flag Copies");
        jCheckBoxShowFlagCopies.setActionCommand("0x10");
        jCheckBoxShowFlagCopies.setName("Flag Copies Toggle"); // NOI18N
        jCheckBoxShowFlagCopies.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxViewItemStateChanged(evt);
            }
        });

        jCheckBoxShowStepCopies.setText("Step Copies");
        jCheckBoxShowStepCopies.setActionCommand("0x20");
        jCheckBoxShowStepCopies.setName("Step Copies Toggle"); // NOI18N
        jCheckBoxShowStepCopies.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxViewItemStateChanged(evt);
            }
        });

        jCheckBoxShowRoofCopies.setText("Roof Copies");
        jCheckBoxShowRoofCopies.setActionCommand("0x40");
        jCheckBoxShowRoofCopies.setName("Roof Copies Toggle"); // NOI18N
        jCheckBoxShowRoofCopies.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxViewItemStateChanged(evt);
            }
        });

        jCheckBoxShowTriggers.setText("Triggers");
        jCheckBoxShowTriggers.setActionCommand("0x400");
        jCheckBoxShowTriggers.setName("Triggers Toggle"); // NOI18N
        jCheckBoxShowTriggers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxViewItemStateChanged(evt);
            }
        });

        jCheckBoxShowItems.setText("Items");
        jCheckBoxShowItems.setActionCommand("0x100");
        jCheckBoxShowItems.setName("Items Toggle"); // NOI18N
        jCheckBoxShowItems.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxViewItemStateChanged(evt);
            }
        });

        jCheckBoxShowWarps.setText("Warps");
        jCheckBoxShowWarps.setActionCommand("0x80");
        jCheckBoxShowWarps.setName("Warps Toggle"); // NOI18N
        jCheckBoxShowWarps.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxViewItemStateChanged(evt);
            }
        });

        jCheckBoxPreviewAnim.setText("Preview anim");
        jCheckBoxPreviewAnim.setName("Preview Anim Toggle"); // NOI18N
        jCheckBoxPreviewAnim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxPreviewAnimItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelScale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelBG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBoxGrid))
                            .addComponent(jCheckBoxShowPriority, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBoxPreviewAnim, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBoxShowExplorationFlags, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBoxShowAreas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBoxShowWarps, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBoxShowTriggers, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBoxShowItems, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBoxShowVehicles, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBoxShowRoofCopies)
                                .addComponent(jCheckBoxShowStepCopies)
                                .addComponent(jCheckBoxShowFlagCopies)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelScale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxGrid)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabelBG)
                        .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShowPriority)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShowExplorationFlags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShowAreas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShowWarps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShowTriggers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShowItems)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShowVehicles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShowFlagCopies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShowStepCopies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShowRoofCopies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxPreviewAnim)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorPickerBGColorChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorPickerBGColorChanged
        super.onBGColorChanged(evt);
    }//GEN-LAST:event_colorPickerBGColorChanged

    private void jComboBoxScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxScaleActionPerformed
        super.onScaleChanged(evt);
    }//GEN-LAST:event_jComboBoxScaleActionPerformed

    private void jCheckBoxGridItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxGridItemStateChanged
        super.onGridChanged(evt);
    }//GEN-LAST:event_jCheckBoxGridItemStateChanged

    private void jCheckBoxShowPriorityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxShowPriorityItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxShowPriority, jCheckBoxShowPriority.isSelected()));
        }
        layoutPanel.setShowPriority(jCheckBoxShowPriority.isSelected());
    }//GEN-LAST:event_jCheckBoxShowPriorityItemStateChanged

    private void jCheckBoxShowExplorationFlagsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxShowExplorationFlagsItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxShowExplorationFlags, jCheckBoxShowExplorationFlags.isSelected()));
        }
        layoutPanel.setShowExplorationFlags(jCheckBoxShowExplorationFlags.isSelected());
    }//GEN-LAST:event_jCheckBoxShowExplorationFlagsItemStateChanged

    private void jCheckBoxViewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxViewItemStateChanged
        JCheckBox source = (JCheckBox)evt.getSource();
        int value = Integer.decode(source.getActionCommand());
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ToggleAction(source, source.isSelected()));
        }
        layoutPanel.setDrawMode_Toggles(value, source.isSelected());
    }//GEN-LAST:event_jCheckBoxViewItemStateChanged

    private void jCheckBoxPreviewAnimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxPreviewAnimItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setAndExecuteAction(new BasicAction<Boolean>(this, "Toggle Map Animation", this::actionPreviewAnimToggled, jCheckBoxPreviewAnim.isSelected(), !jCheckBoxPreviewAnim.isSelected()));
        }
    }//GEN-LAST:event_jCheckBoxPreviewAnimItemStateChanged

    private void actionPreviewAnimToggled(boolean animate) {
        if (animationToggleListener != null) {
            animationToggleListener.actionPerformed(new ActionEvent(this, animate ? 1 : 0, null));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.ColorPicker colorPickerBG;
    private javax.swing.JCheckBox jCheckBoxGrid;
    private javax.swing.JCheckBox jCheckBoxPreviewAnim;
    private javax.swing.JCheckBox jCheckBoxShowAreas;
    private javax.swing.JCheckBox jCheckBoxShowExplorationFlags;
    private javax.swing.JCheckBox jCheckBoxShowFlagCopies;
    private javax.swing.JCheckBox jCheckBoxShowItems;
    private javax.swing.JCheckBox jCheckBoxShowPriority;
    private javax.swing.JCheckBox jCheckBoxShowRoofCopies;
    private javax.swing.JCheckBox jCheckBoxShowStepCopies;
    private javax.swing.JCheckBox jCheckBoxShowTriggers;
    private javax.swing.JCheckBox jCheckBoxShowVehicles;
    private javax.swing.JCheckBox jCheckBoxShowWarps;
    private javax.swing.JComboBox<String> jComboBoxScale;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JLabel jLabelScale;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
