/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.map.animation.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.BasicAction;
import com.sfc.sf2.core.actions.ToggleAction;
import com.sfc.sf2.core.gui.controls.AbstractViewPanel;
import com.sfc.sf2.core.settings.IViewSettings;
import com.sfc.sf2.map.layout.gui.MapLayoutPanel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JCheckBox;

/**
 *
 * @author TiMMy
 */
public class MapLayoutAnimViewPanel extends AbstractViewPanel<MapLayoutPanel> {
    
    private ActionListener animationToggleListener;

    public JCheckBox getCheckBoxPreviewAnim() {
        return jCheckBoxPreviewAnim;
    }
    
    /**
     * Creates new form ViewPanel
     */
    public MapLayoutAnimViewPanel() {
        super();
        initComponents();
        init(jComboBoxScale, jCheckBoxGrid, null, colorPickerBG);
    }

    public void setLayoutPanel(MapLayoutPanel layoutPanel, ActionListener animationToggleListener, IViewSettings viewPanelSettings) {
        super.setLayoutPanel(layoutPanel, viewPanelSettings);
        this.animationToggleListener = animationToggleListener;
        
        layoutPanel.setShowExplorationFlags(jCheckBoxExportationFlags.isSelected());
        layoutPanel.setShowInteractionFlags(jCheckBoxInteractionFlags.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flatOptionPaneWarningIcon1 = new com.formdev.flatlaf.icons.FlatOptionPaneWarningIcon();
        jLabelBG = new javax.swing.JLabel();
        colorPickerBG = new com.sfc.sf2.core.gui.controls.ColorPicker();
        jCheckBoxGrid = new javax.swing.JCheckBox();
        jLabelScale = new javax.swing.JLabel();
        jComboBoxScale = new javax.swing.JComboBox<>();
        jCheckBoxPriority = new javax.swing.JCheckBox();
        jCheckBoxExportationFlags = new javax.swing.JCheckBox();
        jCheckBoxInteractionFlags = new javax.swing.JCheckBox();
        jCheckBoxPreviewAnim = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Map View"));

        jLabelBG.setText("BG :");

        colorPickerBG.setName("BG Color Picker"); // NOI18N
        colorPickerBG.addColorChangedListener(new com.sfc.sf2.core.gui.controls.ColorPicker.ColorChangedListener() {
            public void colorChanged(java.awt.event.ActionEvent evt) {
                colorPickerBGColorChanged(evt);
            }
        });

        javax.swing.GroupLayout colorPickerBGLayout = new javax.swing.GroupLayout(colorPickerBG);
        colorPickerBG.setLayout(colorPickerBGLayout);
        colorPickerBGLayout.setHorizontalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        colorPickerBGLayout.setVerticalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jCheckBoxGrid.setText("Show Grid");
        jCheckBoxGrid.setName("Grid Toggle"); // NOI18N
        jCheckBoxGrid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxGridItemStateChanged(evt);
            }
        });

        jLabelScale.setText("Scale :");

        jComboBoxScale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/8x" }));
        jComboBoxScale.setName("View Scale Combo"); // NOI18N
        jComboBoxScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxScaleActionPerformed(evt);
            }
        });

        jCheckBoxPriority.setText("Show Priority");
        jCheckBoxPriority.setName("Priority Toggle"); // NOI18N
        jCheckBoxPriority.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxPriorityItemStateChanged(evt);
            }
        });

        jCheckBoxExportationFlags.setText("Exploration Flags");
        jCheckBoxExportationFlags.setActionCommand("Show Exploration Flags");
        jCheckBoxExportationFlags.setName("Exploration Flags Toggle"); // NOI18N
        jCheckBoxExportationFlags.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxExportationFlagsItemStateChanged(evt);
            }
        });

        jCheckBoxInteractionFlags.setText("Interaction Flags");
        jCheckBoxInteractionFlags.setName("Interaction Flags Toggle"); // NOI18N
        jCheckBoxInteractionFlags.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxInteractionFlagsItemStateChanged(evt);
            }
        });

        jCheckBoxPreviewAnim.setText("Preview Animation");
        jCheckBoxPreviewAnim.setName("Animation Toggle"); // NOI18N
        jCheckBoxPreviewAnim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxPreviewAnimItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxExportationFlags)
                    .addComponent(jCheckBoxInteractionFlags))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxPriority)
                    .addComponent(jCheckBoxPreviewAnim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBoxGrid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelBG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelScale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelBG)
                    .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxGrid)
                    .addComponent(jCheckBoxExportationFlags)
                    .addComponent(jCheckBoxPreviewAnim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelScale)
                    .addComponent(jCheckBoxPriority)
                    .addComponent(jCheckBoxInteractionFlags))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorPickerBGColorChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorPickerBGColorChanged
        super.onBGColorChanged(evt);
    }//GEN-LAST:event_colorPickerBGColorChanged

    private void jComboBoxScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxScaleActionPerformed
        super.onScaleChanged(evt);
    }//GEN-LAST:event_jComboBoxScaleActionPerformed

    private void jCheckBoxGridItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxGridItemStateChanged
        super.onGridChanged(evt);
    }//GEN-LAST:event_jCheckBoxGridItemStateChanged

    private void jCheckBoxPriorityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxPriorityItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxPriority, jCheckBoxPriority.isSelected()));
        }
        if (layoutPanel != null) {
            layoutPanel.setShowPriority(jCheckBoxPriority.isSelected());
        }
    }//GEN-LAST:event_jCheckBoxPriorityItemStateChanged

    private void jCheckBoxExportationFlagsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxExportationFlagsItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxExportationFlags, jCheckBoxExportationFlags.isSelected()));
        }
        if (layoutPanel != null) {
            layoutPanel.setShowExplorationFlags(jCheckBoxExportationFlags.isSelected());
        }
    }//GEN-LAST:event_jCheckBoxExportationFlagsItemStateChanged

    private void jCheckBoxInteractionFlagsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxInteractionFlagsItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxInteractionFlags, jCheckBoxInteractionFlags.isSelected()));
        }
        if (layoutPanel != null) {
            layoutPanel.setShowInteractionFlags(jCheckBoxInteractionFlags.isSelected());
        }
    }//GEN-LAST:event_jCheckBoxInteractionFlagsItemStateChanged

    private void jCheckBoxPreviewAnimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxPreviewAnimItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setAndExecuteAction(new BasicAction<Boolean>(this, "Toggle Map Animation", this::actionPreviewAnimToggled, jCheckBoxPreviewAnim.isSelected(), !jCheckBoxPreviewAnim.isSelected()));
        }
    }//GEN-LAST:event_jCheckBoxPreviewAnimItemStateChanged

    private void actionPreviewAnimToggled(boolean animate) {
        if (animationToggleListener != null) {
            animationToggleListener.actionPerformed(new ActionEvent(this, animate ? 1 : 0, null));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.ColorPicker colorPickerBG;
    private com.formdev.flatlaf.icons.FlatOptionPaneWarningIcon flatOptionPaneWarningIcon1;
    private javax.swing.JCheckBox jCheckBoxExportationFlags;
    private javax.swing.JCheckBox jCheckBoxGrid;
    private javax.swing.JCheckBox jCheckBoxInteractionFlags;
    private javax.swing.JCheckBox jCheckBoxPreviewAnim;
    private javax.swing.JCheckBox jCheckBoxPriority;
    private javax.swing.JComboBox<String> jComboBoxScale;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JLabel jLabelScale;
    // End of variables declaration//GEN-END:variables
}
