/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.map.animation.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.BasicAction;
import com.sfc.sf2.core.actions.ToggleAction;
import com.sfc.sf2.core.gui.controls.AbstractViewPanel;
import com.sfc.sf2.core.settings.IViewSettings;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JCheckBox;

/**
 *
 * @author TiMMy
 */
public class TilesetAnimViewPanel extends AbstractViewPanel<MapAnimationTilesetLayoutPanel> {
        
    private MapModifiedTilesetLayoutPanel secondLayoutPanel;
    private ActionListener animationToggleListener;
    
    public JCheckBox getCheckBoxPreviewAnim() {
        return jCheckBoxPreviewAnim;
    }
    
    /**
     * Creates new form ViewPanel
     */
    public TilesetAnimViewPanel() {
        super();
        initComponents();
        init(jComboBoxScale, jCheckBoxGrid, jSpinnerItemsPerRow, colorPickerBG);
    }

    public void setLayoutPanel(MapAnimationTilesetLayoutPanel layoutPanel, MapModifiedTilesetLayoutPanel modifiedTilesetLayoutPanel, ActionListener animationToggleListener, IViewSettings viewPanelSettings) {
        super.setLayoutPanel(layoutPanel, viewPanelSettings);
        this.secondLayoutPanel = modifiedTilesetLayoutPanel;
        this.animationToggleListener = animationToggleListener;
        
        layoutPanel.setShowAnimationFrames(jCheckBoxAnimFrames.isSelected());
        
        secondLayoutPanel.setRenderScaleIndex(jComboBoxScale.getSelectedIndex());
        secondLayoutPanel.setShowGrid(jCheckBoxGrid.isSelected());
        secondLayoutPanel.setItemsPerRow((int)jSpinnerItemsPerRow.getValue());
        secondLayoutPanel.setBGColor(colorPickerBG.getColor());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelItemsPerRow = new javax.swing.JLabel();
        jSpinnerItemsPerRow = new javax.swing.JSpinner();
        jLabelBG = new javax.swing.JLabel();
        colorPickerBG = new com.sfc.sf2.core.gui.controls.ColorPicker();
        jCheckBoxGrid = new javax.swing.JCheckBox();
        jLabelScale = new javax.swing.JLabel();
        jComboBoxScale = new javax.swing.JComboBox<>();
        jCheckBoxAnimFrames = new javax.swing.JCheckBox();
        jCheckBoxPreviewAnim = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Tileset View"));

        jLabelItemsPerRow.setText("Tiles per row :");

        jSpinnerItemsPerRow.setModel(new javax.swing.SpinnerNumberModel(16, 1, null, 1));
        jSpinnerItemsPerRow.setName("Tiles Per Row Spinner"); // NOI18N
        jSpinnerItemsPerRow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerItemsPerRowStateChanged(evt);
            }
        });

        jLabelBG.setText("BG :");

        colorPickerBG.setName("BG Color Picker"); // NOI18N
        colorPickerBG.addColorChangedListener(new com.sfc.sf2.core.gui.controls.ColorPicker.ColorChangedListener() {
            public void colorChanged(java.awt.event.ActionEvent evt) {
                colorPickerBGColorChanged(evt);
            }
        });

        javax.swing.GroupLayout colorPickerBGLayout = new javax.swing.GroupLayout(colorPickerBG);
        colorPickerBG.setLayout(colorPickerBGLayout);
        colorPickerBGLayout.setHorizontalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        colorPickerBGLayout.setVerticalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jCheckBoxGrid.setLabel("Show Grid");
        jCheckBoxGrid.setName("Grid Toggle"); // NOI18N
        jCheckBoxGrid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxGridItemStateChanged(evt);
            }
        });

        jLabelScale.setText("Scale :");

        jComboBoxScale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/8x" }));
        jComboBoxScale.setName("View Scale Combo"); // NOI18N
        jComboBoxScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxScaleActionPerformed(evt);
            }
        });

        jCheckBoxAnimFrames.setSelected(true);
        jCheckBoxAnimFrames.setText("Show Frames");
        jCheckBoxAnimFrames.setName("Anim Frames Toggle"); // NOI18N
        jCheckBoxAnimFrames.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxAnimFramesItemStateChanged(evt);
            }
        });

        jCheckBoxPreviewAnim.setSelected(true);
        jCheckBoxPreviewAnim.setLabel("Preview Anim");
        jCheckBoxPreviewAnim.setName("Preview Anim Toggle"); // NOI18N
        jCheckBoxPreviewAnim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxPreviewAnimItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBoxAnimFrames)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelItemsPerRow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerItemsPerRow, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelBG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBoxPreviewAnim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxGrid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelScale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelItemsPerRow)
                    .addComponent(jSpinnerItemsPerRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBG)
                    .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxAnimFrames))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelScale)
                    .addComponent(jCheckBoxPreviewAnim)
                    .addComponent(jCheckBoxGrid))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerItemsPerRowStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerItemsPerRowStateChanged
        super.onItemsPerRowChanged(evt);
        if (secondLayoutPanel != null) {
            secondLayoutPanel.setItemsPerRow((int)jSpinnerItemsPerRow.getValue());
        }
    }//GEN-LAST:event_jSpinnerItemsPerRowStateChanged

    private void colorPickerBGColorChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorPickerBGColorChanged
        super.onBGColorChanged(evt);
        if (secondLayoutPanel != null) {
            secondLayoutPanel.setBGColor(colorPickerBG.getColor());
        }
    }//GEN-LAST:event_colorPickerBGColorChanged

    private void jComboBoxScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxScaleActionPerformed
        super.onScaleChanged(evt);
        if (secondLayoutPanel != null) {
            secondLayoutPanel.setRenderScaleIndex(jComboBoxScale.getSelectedIndex());
        }
    }//GEN-LAST:event_jComboBoxScaleActionPerformed

    private void jCheckBoxGridItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxGridItemStateChanged
        super.onGridChanged(evt);
        if (secondLayoutPanel != null) {
            secondLayoutPanel.setShowGrid(jCheckBoxGrid.isSelected());
        }
    }//GEN-LAST:event_jCheckBoxGridItemStateChanged

    private void jCheckBoxAnimFramesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxAnimFramesItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxAnimFrames, jCheckBoxAnimFrames.isSelected()));
        }
        if (layoutPanel != null) {
            layoutPanel.setShowAnimationFrames(jCheckBoxAnimFrames.isSelected());
        }
        if (secondLayoutPanel != null) {
            secondLayoutPanel.setShowAnimationFrames(jCheckBoxAnimFrames.isSelected());
        }
    }//GEN-LAST:event_jCheckBoxAnimFramesItemStateChanged

    private void jCheckBoxPreviewAnimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxPreviewAnimItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setAndExecuteAction(new BasicAction<Boolean>(this, "Toggle Map Animation", this::actionPreviewAnimToggled, jCheckBoxPreviewAnim.isSelected(), !jCheckBoxPreviewAnim.isSelected()));
        }
    }//GEN-LAST:event_jCheckBoxPreviewAnimItemStateChanged

    private void actionPreviewAnimToggled(boolean animate) {
        if (animationToggleListener != null) {
            animationToggleListener.actionPerformed(new ActionEvent(this, animate ? 1 : 0, null));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.ColorPicker colorPickerBG;
    private javax.swing.JCheckBox jCheckBoxAnimFrames;
    private javax.swing.JCheckBox jCheckBoxGrid;
    private javax.swing.JCheckBox jCheckBoxPreviewAnim;
    private javax.swing.JComboBox<String> jComboBoxScale;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JLabel jLabelItemsPerRow;
    private javax.swing.JLabel jLabelScale;
    private javax.swing.JSpinner jSpinnerItemsPerRow;
    // End of variables declaration//GEN-END:variables
}
