/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.battle.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.ToggleAction;
import com.sfc.sf2.core.gui.controls.AbstractViewPanel;
import com.sfc.sf2.core.settings.IViewSettings;
import javax.swing.JCheckBox;

/**
 *
 * @author TiMMy
 */
public class BattleViewPanel extends AbstractViewPanel<BattleLayoutPanel> {
        
    private boolean drawTerrain;
    private boolean drawSprites;
    private boolean drawRegions;
    private boolean drawPoints;

    public boolean getDrawTerrain() {
        return drawTerrain;
    }

    public boolean getDrawSprites() {
        return drawSprites;
    }

    public boolean getDrawRegions() {
        return drawRegions;
    }
    
    public boolean getDrawPoints() {
        return drawPoints;
    }

    public JCheckBox getjCheckBoxTerrain() {
        return jCheckBoxTerrain;
    }

    public JCheckBox getjCheckBoxSprites() {
        return jCheckBoxSprites;
    }

    public JCheckBox getjCheckBoxRegions() {
        return jCheckBoxRegions;
    }

    public JCheckBox getjCheckBoxPoints() {
        return jCheckBoxPoints;
    }
    
    /**
     * Creates new form ViewPanel
     */
    public BattleViewPanel() {
        super();
        initComponents();
        init(jComboBoxScale, jCheckBoxGrid, null, colorPickerBG);
        
        drawTerrain = jCheckBoxTerrain.isSelected();
        drawSprites = jCheckBoxSprites.isSelected();
        drawRegions = jCheckBoxRegions.isSelected();
        drawPoints = jCheckBoxPoints.isSelected();
    }

    @Override
    public void setLayoutPanel(BattleLayoutPanel layoutPanel, IViewSettings viewPanelSettings) {
        super.setLayoutPanel(layoutPanel, viewPanelSettings);
        
        layoutPanel.setShowExplorationFlags(jCheckBoxExportationFlags.isSelected());
        layoutPanel.setDrawTerrain(jCheckBoxTerrain.isSelected());
        layoutPanel.setDrawSprites(jCheckBoxSprites.isSelected());
        layoutPanel.setDrawAiRegions(jCheckBoxRegions.isSelected());
        layoutPanel.setDrawAiPoints(jCheckBoxPoints.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flatOptionPaneWarningIcon1 = new com.formdev.flatlaf.icons.FlatOptionPaneWarningIcon();
        jLabelBG = new javax.swing.JLabel();
        colorPickerBG = new com.sfc.sf2.core.gui.controls.ColorPicker();
        jCheckBoxGrid = new javax.swing.JCheckBox();
        jLabelScale = new javax.swing.JLabel();
        jComboBoxScale = new javax.swing.JComboBox<>();
        jCheckBoxExportationFlags = new javax.swing.JCheckBox();
        jCheckBoxTerrain = new javax.swing.JCheckBox();
        jCheckBoxSprites = new javax.swing.JCheckBox();
        jCheckBoxRegions = new javax.swing.JCheckBox();
        jCheckBoxPoints = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Map View"));

        jLabelBG.setText("BG :");

        colorPickerBG.setName("BG Color Picker"); // NOI18N
        colorPickerBG.addColorChangedListener(new com.sfc.sf2.core.gui.controls.ColorPicker.ColorChangedListener() {
            public void colorChanged(java.awt.event.ActionEvent evt) {
                colorPickerBGColorChanged(evt);
            }
        });

        javax.swing.GroupLayout colorPickerBGLayout = new javax.swing.GroupLayout(colorPickerBG);
        colorPickerBG.setLayout(colorPickerBGLayout);
        colorPickerBGLayout.setHorizontalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        colorPickerBGLayout.setVerticalGroup(
            colorPickerBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jCheckBoxGrid.setText("Show Grid");
        jCheckBoxGrid.setName("Grid Toggle"); // NOI18N
        jCheckBoxGrid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxGridItemStateChanged(evt);
            }
        });

        jLabelScale.setText("Scale :");

        jComboBoxScale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/8x" }));
        jComboBoxScale.setName("View Scale Combo"); // NOI18N
        jComboBoxScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxScaleActionPerformed(evt);
            }
        });

        jCheckBoxExportationFlags.setText("Exploration Flags");
        jCheckBoxExportationFlags.setActionCommand("Show Exploration Flags");
        jCheckBoxExportationFlags.setName("Exploration Flags Toggle"); // NOI18N
        jCheckBoxExportationFlags.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxExportationFlagsItemStateChanged(evt);
            }
        });

        jCheckBoxTerrain.setText("Terrain");
        jCheckBoxTerrain.setActionCommand("Show Exploration Flags");
        jCheckBoxTerrain.setName("Show Terrain Toggle"); // NOI18N
        jCheckBoxTerrain.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxTerrainItemStateChanged(evt);
            }
        });

        jCheckBoxSprites.setSelected(true);
        jCheckBoxSprites.setText("Sprites");
        jCheckBoxSprites.setName("Show MapSprites Toggle"); // NOI18N
        jCheckBoxSprites.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxSpritesItemStateChanged(evt);
            }
        });

        jCheckBoxRegions.setText("AI regions");
        jCheckBoxRegions.setName("Show AI Regions Toggle"); // NOI18N
        jCheckBoxRegions.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxRegionsItemStateChanged(evt);
            }
        });

        jCheckBoxPoints.setText("AI points");
        jCheckBoxPoints.setName("Show AI Points Toggle"); // NOI18N
        jCheckBoxPoints.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxPointsItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxExportationFlags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxTerrain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxSprites)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxRegions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxPoints)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxGrid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelScale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(colorPickerBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBG)
                    .addComponent(jCheckBoxGrid)
                    .addComponent(jLabelScale)
                    .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxExportationFlags)
                    .addComponent(jCheckBoxTerrain)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBoxSprites)
                        .addComponent(jCheckBoxRegions)
                        .addComponent(jCheckBoxPoints)))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Blocks View");
    }// </editor-fold>//GEN-END:initComponents

    protected void colorPickerBGColorChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorPickerBGColorChanged
        super.onBGColorChanged(evt);
    }//GEN-LAST:event_colorPickerBGColorChanged

    protected void jComboBoxScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxScaleActionPerformed
        super.onScaleChanged(evt);
    }//GEN-LAST:event_jComboBoxScaleActionPerformed

    protected void jCheckBoxGridItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxGridItemStateChanged
        super.onGridChanged(evt);
    }//GEN-LAST:event_jCheckBoxGridItemStateChanged

    protected void jCheckBoxExportationFlagsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxExportationFlagsItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxExportationFlags, jCheckBoxExportationFlags.isSelected()));
        }
        if (layoutPanel != null) {
            layoutPanel.setShowExplorationFlags(jCheckBoxExportationFlags.isSelected());
        }
    }//GEN-LAST:event_jCheckBoxExportationFlagsItemStateChanged

    private void jCheckBoxTerrainItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxTerrainItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            drawTerrain = jCheckBoxTerrain.isSelected();
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxTerrain, jCheckBoxTerrain.isSelected()));
        }
        if (layoutPanel != null) {
            layoutPanel.setDrawTerrain(jCheckBoxTerrain.isSelected());
        }
    }//GEN-LAST:event_jCheckBoxTerrainItemStateChanged

    private void jCheckBoxSpritesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxSpritesItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            drawSprites = jCheckBoxSprites.isSelected();
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxSprites, jCheckBoxSprites.isSelected()));
        }
        if (layoutPanel != null) {
            layoutPanel.setDrawSprites(jCheckBoxSprites.isSelected());
        }
    }//GEN-LAST:event_jCheckBoxSpritesItemStateChanged

    private void jCheckBoxRegionsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxRegionsItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            drawRegions = jCheckBoxRegions.isSelected();
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxRegions, jCheckBoxRegions.isSelected()));
        }
        if (layoutPanel != null) {
            layoutPanel.setDrawAiRegions(jCheckBoxRegions.isSelected());
        }
    }//GEN-LAST:event_jCheckBoxRegionsItemStateChanged

    private void jCheckBoxPointsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxPointsItemStateChanged
        if (!ActionManager.isActionTriggering()) {
            drawPoints = jCheckBoxPoints.isSelected();
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxPoints, jCheckBoxPoints.isSelected()));
        }
        if (layoutPanel != null) {
            layoutPanel.setDrawAiPoints(jCheckBoxPoints.isSelected());
        }
    }//GEN-LAST:event_jCheckBoxPointsItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.ColorPicker colorPickerBG;
    private com.formdev.flatlaf.icons.FlatOptionPaneWarningIcon flatOptionPaneWarningIcon1;
    private javax.swing.JCheckBox jCheckBoxExportationFlags;
    private javax.swing.JCheckBox jCheckBoxGrid;
    private javax.swing.JCheckBox jCheckBoxPoints;
    private javax.swing.JCheckBox jCheckBoxRegions;
    private javax.swing.JCheckBox jCheckBoxSprites;
    private javax.swing.JCheckBox jCheckBoxTerrain;
    private javax.swing.JComboBox<String> jComboBoxScale;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JLabel jLabelScale;
    // End of variables declaration//GEN-END:variables
}
