/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.battle.gui;

import com.sfc.sf2.battle.mapcoords.BattleMapCoords;
import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.SpinnerAction;
import com.sfc.sf2.core.actions.ToggleAction;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author TiMMy
 */
public class MapCoordsPanel extends javax.swing.JPanel {

    private BattleMapCoords coords;
    private BattleLayoutPanel layoutPanel;
    
    private ActionListener mapIndexChangedListener;
    
    /**
     * Creates new form MapCoordsPanel
     */
    public MapCoordsPanel() {
        initComponents();
    }
    
    public void setup(BattleMapCoords coords, BattleLayoutPanel layoutPanel, ActionListener mapIndexChangedListener) {
        this.coords = coords;
        this.layoutPanel = layoutPanel;
        this.mapIndexChangedListener = mapIndexChangedListener;
        
        if (coords == null) {
            jSpinnerMapIndex.setValue(-1);
            jSpinnerStartX.setValue(0);
            jSpinnerStartY.setValue(0);
            jSpinnerWidth.setValue(0);
            jSpinnerHeight.setValue(0);
            jSpinnerTriggerX.setValue(0);
            jSpinnerTriggerY.setValue(0);
        } else {
            jSpinnerMapIndex.setValue(coords.getMapIndex());
            jSpinnerStartX.setValue(coords.getX());
            jSpinnerStartY.setValue(coords.getY());
            jSpinnerWidth.setValue(coords.getWidth());
            jSpinnerHeight.setValue(coords.getHeight());
            jSpinnerTriggerX.setValue(coords.getTrigX());
            jSpinnerTriggerY.setValue(coords.getTrigY());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerStartY = new javax.swing.JSpinner();
        jSpinnerTriggerY = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerStartX = new javax.swing.JSpinner();
        jSpinnerWidth = new javax.swing.JSpinner();
        jCheckBoxLockPositions = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        infoButton1 = new com.sfc.sf2.core.gui.controls.InfoButton();
        jSpinnerHeight = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jSpinnerMapIndex = new javax.swing.JSpinner();
        jSpinnerTriggerX = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        jLabel11.setText("Trigger Y :");

        jLabel6.setText("Start Y :");

        jLabel5.setText("Start X :");

        jSpinnerStartY.setModel(new javax.swing.SpinnerNumberModel(0, 0, 63, 1));
        jSpinnerStartY.setName("Coords Y Spinner"); // NOI18N
        jSpinnerStartY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerStartYStateChanged(evt);
            }
        });

        jSpinnerTriggerY.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        jSpinnerTriggerY.setName("Coords Trigger Y Spinner"); // NOI18N
        jSpinnerTriggerY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerTriggerYStateChanged(evt);
            }
        });

        jLabel7.setText("Width :");

        jSpinnerStartX.setModel(new javax.swing.SpinnerNumberModel(0, 0, 63, 1));
        jSpinnerStartX.setName("Coords X Spinner"); // NOI18N
        jSpinnerStartX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerStartXStateChanged(evt);
            }
        });

        jSpinnerWidth.setModel(new javax.swing.SpinnerNumberModel(0, 0, 48, 1));
        jSpinnerWidth.setName("Coords Width Spinner"); // NOI18N
        jSpinnerWidth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerWidthStateChanged(evt);
            }
        });

        jCheckBoxLockPositions.setText("Lock unit positions");
        jCheckBoxLockPositions.setName("Lock Positions Toggle"); // NOI18N
        jCheckBoxLockPositions.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxLockPositionsItemStateChanged(evt);
            }
        });

        jLabel8.setText("Height :");

        infoButton1.setMessageText("<html>Changing the Start X and Start Y will move the allies, enemies, AI regions, and AI points. Toggling this on will fix those elements to the map while moving the battle boundaries.<br><br><b>WARNING</b> Points outside of the battle area will not be saved properly. A red alert icon will show any points outside of the battle area.</html>");
        infoButton1.setText("");

        jSpinnerHeight.setModel(new javax.swing.SpinnerNumberModel(0, 0, 48, 1));
        jSpinnerHeight.setName("Coords Height Spinner"); // NOI18N
        jSpinnerHeight.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerHeightStateChanged(evt);
            }
        });

        jLabel9.setText("Trigger X :");

        jSpinnerMapIndex.setModel(new javax.swing.SpinnerNumberModel(0, 0, 256, 1));
        jSpinnerMapIndex.setName("Map Index Spinner"); // NOI18N
        jSpinnerMapIndex.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerMapIndexStateChanged(evt);
            }
        });

        jSpinnerTriggerX.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        jSpinnerTriggerX.setName("Coords Trigger X Spinner"); // NOI18N
        jSpinnerTriggerX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerTriggerXStateChanged(evt);
            }
        });

        jLabel3.setText("Map :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerMapIndex))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxLockPositions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerStartY))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerStartX, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(8, 8, 8)
                        .addComponent(jSpinnerWidth))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerHeight))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerTriggerX))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerTriggerY, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerMapIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(infoButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxLockPositions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerStartX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerStartY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerTriggerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerTriggerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerStartYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerStartYStateChanged
        if (coords == null) return;
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new SpinnerAction(jSpinnerStartY, jSpinnerStartY.getValue(), coords.getY()));
        }
        int newVal = (int)jSpinnerStartY.getModel().getValue();
        if (jCheckBoxLockPositions.isSelected()) {
            int yShift = coords.getY() - newVal;
            layoutPanel.getBattle().getSpriteset().shiftPositions(0, yShift);
        }
        coords.setY(newVal);
        layoutPanel.redraw();
    }//GEN-LAST:event_jSpinnerStartYStateChanged

    private void jSpinnerTriggerYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerTriggerYStateChanged
        if (coords == null) return;
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new SpinnerAction(jSpinnerTriggerY, jSpinnerTriggerY.getValue(), coords.getTrigY()));
        }
        int oldVal = coords.getTrigY();
        int newVal = (int)jSpinnerTriggerY.getModel().getValue();
        if (oldVal < newVal && newVal >= 64) {
            newVal = 255;
            jSpinnerTriggerY.getModel().setValue(newVal);
        } else if (oldVal > newVal && newVal >= 64) {
            newVal = 63;
            jSpinnerTriggerY.getModel().setValue(newVal);
        }
        coords.setTrigY(newVal);
        layoutPanel.redraw();
    }//GEN-LAST:event_jSpinnerTriggerYStateChanged

    private void jSpinnerStartXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerStartXStateChanged
        if (coords == null) return;
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new SpinnerAction(jSpinnerStartX, jSpinnerStartX.getValue(), coords.getX()));
        }
        int newVal = (int)jSpinnerStartX.getModel().getValue();
        BattleMapCoords coords = layoutPanel.getBattle().getBattleCoords();
        if (jCheckBoxLockPositions.isSelected()) {
            int xShift = coords.getX() - newVal;
            layoutPanel.getBattle().getSpriteset().shiftPositions(xShift, 0);
        }
        coords.setX(newVal);
        layoutPanel.redraw();
    }//GEN-LAST:event_jSpinnerStartXStateChanged

    private void jSpinnerWidthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerWidthStateChanged
        if (coords == null) return;
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new SpinnerAction(jSpinnerWidth, jSpinnerWidth.getValue(), coords.getWidth()));
        }
        coords.setWidth((int)jSpinnerWidth.getModel().getValue());
        layoutPanel.redraw();
    }//GEN-LAST:event_jSpinnerWidthStateChanged

    private void jSpinnerHeightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerHeightStateChanged
        if (coords == null) return;
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new SpinnerAction(jSpinnerHeight, jSpinnerHeight.getValue(), coords.getHeight()));
        }
        coords.setWidth((int)jSpinnerHeight.getModel().getValue());
        layoutPanel.redraw();
    }//GEN-LAST:event_jSpinnerHeightStateChanged

    private void jSpinnerMapIndexStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerMapIndexStateChanged
        if (coords == null) return;
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new SpinnerAction(jSpinnerMapIndex, jSpinnerMapIndex.getValue(), coords.getMapIndex()));
        }
        int newMapIndex = (int)jSpinnerMapIndex.getModel().getValue();
        if (newMapIndex != coords.getMapIndex()) {
            if (mapIndexChangedListener != null) {
                mapIndexChangedListener.actionPerformed(new ActionEvent(jSpinnerMapIndex, newMapIndex, "Change Map"));
            }
        }
    }//GEN-LAST:event_jSpinnerMapIndexStateChanged

    private void jSpinnerTriggerXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerTriggerXStateChanged
        if (coords == null) return;
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new SpinnerAction(jSpinnerTriggerX, jSpinnerTriggerX.getValue(), coords.getTrigX()));
        }
        int oldVal = coords.getTrigX();
        int newVal = (int)jSpinnerTriggerX.getModel().getValue();
        if (oldVal < newVal && newVal >= 64) {
            newVal = 255;
            jSpinnerTriggerX.getModel().setValue(newVal);
        } else if (oldVal > newVal && newVal >= 64) {
            newVal = 63;
            jSpinnerTriggerX.getModel().setValue(newVal);
        }
        coords.setTrigX(newVal);
        layoutPanel.redraw();
    }//GEN-LAST:event_jSpinnerTriggerXStateChanged

    private void jCheckBoxLockPositionsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxLockPositionsItemStateChanged
        if (coords == null) return;
        if (!ActionManager.isActionTriggering()) {
            ActionManager.setActionWithoutExecute(new ToggleAction(jCheckBoxLockPositions, jCheckBoxLockPositions.isSelected()));
        }
    }//GEN-LAST:event_jCheckBoxLockPositionsItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.InfoButton infoButton1;
    private javax.swing.JCheckBox jCheckBoxLockPositions;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinnerHeight;
    private javax.swing.JSpinner jSpinnerMapIndex;
    private javax.swing.JSpinner jSpinnerStartX;
    private javax.swing.JSpinner jSpinnerStartY;
    private javax.swing.JSpinner jSpinnerTriggerX;
    private javax.swing.JSpinner jSpinnerTriggerY;
    private javax.swing.JSpinner jSpinnerWidth;
    // End of variables declaration//GEN-END:variables
}
