/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.palette.gui.controls;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.BasicAction;
import com.sfc.sf2.palette.CRAMColor;
import com.sfc.sf2.palette.Palette;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.EventListener;

/**
 *
 * @author TiMMy
 */
public class PaletteButton extends javax.swing.JButton {

    private Palette palette;
    private CRAMColor[] originalColors;
    
    private int[] limitColorIndices;
    
    private PaletteListener paletteListener;
    private ActionListener colorChangeListener;
    
    /**
     * Creates new form PaletteButton
     */
    public PaletteButton() {
        initComponents();
        
        palettePane.setColorEditor(cRAMColorEditor);
        palettePane.setRecordActions(false);
        palettePane.setColorChangeListener(this::onColorChanged);
        paletteEditor.setLocationRelativeTo(this);
    }
    
    public void setupPaletteButton(PaletteListener paletteListener, ActionListener colorChangeListener) {
        setupPaletteButton(paletteListener, colorChangeListener, null);
    }
    
    public void setupPaletteButton(PaletteListener paletteListener, ActionListener colorChangeListener, int[] limitColorIndices) {
        this.limitColorIndices = limitColorIndices;
        this.paletteListener = paletteListener;
        this.colorChangeListener = colorChangeListener;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paletteEditor = new javax.swing.JDialog();
        palettePane = new com.sfc.sf2.palette.gui.PalettePane();
        jSeparator = new javax.swing.JSeparator();
        cRAMColorEditor = new com.sfc.sf2.palette.gui.controls.CRAMColorEditor();
        jButtonConfirm = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        paletteEditor.setTitle("Palette Editor");
        paletteEditor.setBounds(new java.awt.Rectangle(0, 0, 532, 320));
        paletteEditor.setMaximumSize(new java.awt.Dimension(520, 295));
        paletteEditor.setMinimumSize(new java.awt.Dimension(520, 295));
        paletteEditor.setPreferredSize(new java.awt.Dimension(520, 295));
        paletteEditor.setResizable(false);
        paletteEditor.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                paletteEditorWindowClosing(evt);
            }
        });

        jButtonConfirm.setText("Confirm");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paletteEditorLayout = new javax.swing.GroupLayout(paletteEditor.getContentPane());
        paletteEditor.getContentPane().setLayout(paletteEditorLayout);
        paletteEditorLayout.setHorizontalGroup(
            paletteEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paletteEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paletteEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator)
                    .addGroup(paletteEditorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(paletteEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paletteEditorLayout.createSequentialGroup()
                                .addComponent(jButtonCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonConfirm))
                            .addGroup(paletteEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cRAMColorEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(palettePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );
        paletteEditorLayout.setVerticalGroup(
            paletteEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paletteEditorLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(palettePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cRAMColorEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paletteEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirm)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonReset))
                .addGap(14, 14, 14))
        );

        setIcon(new javax.swing.ImageIcon("D:\\TiMMy\\Dev\\ShiningForce2\\SF2JavaToolsSuite\\SF2PaletteManager\\res\\Palette\\Icons\\Palette.png")); // NOI18N
        setMaximumSize(new java.awt.Dimension(32, 32));
        setMinimumSize(new java.awt.Dimension(32, 32));
        setPreferredSize(new java.awt.Dimension(32, 32));
        addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPaletteEditor(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        ActionManager.setActionWithoutExecute(new BasicAction<CRAMColor[]>(palette, "Palette Change", this::actionPaletteChanged, palette.getColors(), originalColors));
        palette = null;
        paletteEditor.dispose();
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void actionPaletteChanged(CRAMColor[] colors) {
        Palette palette = paletteListener.getPalette();
        palette.setColors(colors, palette.isFirstColorTransparent());
        if (colorChangeListener != null) {
            colorChangeListener.actionPerformed(new ActionEvent(palette, -1, "Reset"));
        }
    }
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        jButtonResetActionPerformed(evt);
        palette = null;
        paletteEditor.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void showPaletteEditor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPaletteEditor
        palette = paletteListener.getPalette();
        palettePane.setPalette(palette, limitColorIndices);
        if (palette == null) {
            originalColors = null;
            paletteEditor.setTitle("Palette Editor");
        } else {
            originalColors = palette.getColors().clone();
            paletteEditor.setTitle("Palette Editor: " + palette.getName());
        }
        paletteEditor.setVisible(true);
    }//GEN-LAST:event_showPaletteEditor

    private void paletteEditorWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_paletteEditorWindowClosing
        jButtonCancelActionPerformed(null);
    }//GEN-LAST:event_paletteEditorWindowClosing

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        if (palette == null) return;
        palette.setColors(originalColors, palette.isFirstColorTransparent());
        if (palette != null && colorChangeListener != null) {
            colorChangeListener.actionPerformed(new ActionEvent(palette, -1, "Reset"));
            palettePane.refreshColorPanes();
        }
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void onColorChanged(ActionEvent e) {
        if (colorChangeListener != null) {
            colorChangeListener.actionPerformed(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.palette.gui.controls.CRAMColorEditor cRAMColorEditor;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JDialog paletteEditor;
    private com.sfc.sf2.palette.gui.PalettePane palettePane;
    // End of variables declaration//GEN-END:variables

    public interface PaletteListener extends EventListener {
        public Palette getPalette();
    }
}
