/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.palette.gui.controls;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.CustomAction;
import com.sfc.sf2.palette.actions.PaletteColorSwapActionData;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.EventListener;
import com.sfc.sf2.palette.IPaletteGraphic;
import com.sfc.sf2.palette.Palette;
import com.sfc.sf2.palette.actions.PaletteChangeActionData;

/**
 *
 * @author TiMMy
 */
public class PaletteButton extends javax.swing.JButton {

    private Palette originalPalette;
    private byte[] originalPixels;
    
    private int[] limitColorIndices;
    
    private PaletteGraphicsListener getPaletteListener;
    private ActionListener colorChangeListener;
    
    /**
     * Creates new form PaletteButton
     */
    public PaletteButton() {
        initComponents();
        
        palettePane.setColorEditor(cRAMColorEditor);
        palettePane.setColorChangeListener(this::onColorChanged, this::onColorsSwapped);
        paletteEditor.setLocationRelativeTo(this);
        
        ActionManager.setupInputMaps(palettePane);
    }
    
    public void setupPaletteButton(PaletteGraphicsListener paletteListener, ActionListener colorChangeListener) {
        setupPaletteButton(paletteListener, colorChangeListener, null);
    }
    
    public void setupPaletteButton(PaletteGraphicsListener paletteListener, ActionListener colorChangeListener, int[] limitColorIndices) {
        this.getPaletteListener = paletteListener;
        this.colorChangeListener = colorChangeListener;
        this.limitColorIndices = limitColorIndices;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paletteEditor = new javax.swing.JDialog();
        palettePane = new com.sfc.sf2.palette.gui.PalettePane();
        jSeparator = new javax.swing.JSeparator();
        cRAMColorEditor = new com.sfc.sf2.palette.gui.controls.CRAMColorEditor();
        jButtonConfirm = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        paletteEditor.setTitle("Palette Editor");
        paletteEditor.setBounds(new java.awt.Rectangle(0, 0, 532, 320));
        paletteEditor.setMinimumSize(new java.awt.Dimension(560, 300));
        paletteEditor.setPreferredSize(new java.awt.Dimension(560, 300));
        paletteEditor.setResizable(false);
        paletteEditor.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                paletteEditorWindowClosing(evt);
            }
        });

        jButtonConfirm.setText("Confirm");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paletteEditorLayout = new javax.swing.GroupLayout(paletteEditor.getContentPane());
        paletteEditor.getContentPane().setLayout(paletteEditorLayout);
        paletteEditorLayout.setHorizontalGroup(
            paletteEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paletteEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paletteEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(palettePane, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addComponent(jSeparator)
                    .addGroup(paletteEditorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(cRAMColorEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paletteEditorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConfirm)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        paletteEditorLayout.setVerticalGroup(
            paletteEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paletteEditorLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(palettePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cRAMColorEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paletteEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirm)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setIcon(new javax.swing.ImageIcon(getClass().getResource("/Palette/Icons/Palette.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(32, 32));
        setMinimumSize(new java.awt.Dimension(32, 32));
        setPreferredSize(new java.awt.Dimension(32, 32));
        addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPaletteEditor(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        IPaletteGraphic graphics = getPaletteListener.getPaletteGraphics();
        PaletteChangeActionData oldValue = new PaletteChangeActionData(originalPalette, originalPixels);
        PaletteChangeActionData newValue = new PaletteChangeActionData(palettePane.getPalette(), graphics.getPixels());
        ActionManager.setActionWithoutExecute(new CustomAction<PaletteChangeActionData>(this, "Palette Change", this::actionPaletteChanged, newValue, oldValue));
        originalPalette = null;
        originalPixels = null;
        ActionManager.clearActionsFromOwner(palettePane);  //Clear all palette editing actions
        paletteEditor.dispose();
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void actionPaletteChanged(PaletteChangeActionData value) {
        IPaletteGraphic graphics = getPaletteListener.getPaletteGraphics();
        if (graphics != null) {
            graphics.setPalette(value.palette());
            if (value.pixelData() != null) {
                graphics.setPixels(value.pixelData());
            }
        }
        if (colorChangeListener != null) {
            colorChangeListener.actionPerformed(new ActionEvent(value, -1, "PaletteChange"));
        }
    }
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        jButtonResetActionPerformed(evt);
        originalPalette = null;
        originalPixels = null;
        paletteEditor.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void showPaletteEditor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPaletteEditor
        originalPixels = null;
        originalPalette = null;
        
        IPaletteGraphic graphics = getPaletteListener.getPaletteGraphics();
        if (graphics != null) {
            originalPalette = graphics.getPalette();
            originalPixels = graphics.getPixels();
        }
        
        palettePane.setPixelData(originalPixels);        
        palettePane.setPalette(originalPalette, limitColorIndices);
        if (originalPalette == null) {
            paletteEditor.setTitle("Palette Editor");
        } else {
            paletteEditor.setTitle("Palette Editor: " + originalPalette.getName());
        }
        paletteEditor.setVisible(true);
    }//GEN-LAST:event_showPaletteEditor

    private void paletteEditorWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_paletteEditorWindowClosing
        jButtonCancelActionPerformed(null);
        ActionManager.clearActionsFromOwner(palettePane);  //Clear all palette editing actions
    }//GEN-LAST:event_paletteEditorWindowClosing

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        IPaletteGraphic graphics = getPaletteListener.getPaletteGraphics();
        int selected = palettePane.getCurrentSelected();
        ActionManager.setExternalActionTriggering(true);
        
        PaletteChangeActionData oldValue = new PaletteChangeActionData(palettePane.getPalette(), graphics == null ? null : graphics.getPixels());
        PaletteChangeActionData newValue = new PaletteChangeActionData(originalPalette, originalPixels);
        ActionManager.setActionWithoutExecute(new CustomAction<PaletteChangeActionData>(palettePane, "Reset", this::actionPaletteChanged, newValue, oldValue));
        
        if (graphics != null) {
            graphics.setPalette(originalPalette);
            if (originalPixels != null) {
                graphics.setPixels(originalPixels);
            }
        }
        
        palettePane.setPalette(originalPalette);
        palettePane.setColorPaneSelected(selected);
        ActionManager.setExternalActionTriggering(false);
        
        if (colorChangeListener != null) {
            colorChangeListener.actionPerformed(new ActionEvent(this, -1, "Reset"));
        }
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void onColorChanged(ActionEvent e) {
        IPaletteGraphic graphics = getPaletteListener.getPaletteGraphics();
        if (graphics != null) {
            Palette palette = palettePane.getPalette();
            graphics.setPalette(palette);
            palette.rebuildIcm();
        }
        if (colorChangeListener != null) {
            colorChangeListener.actionPerformed(e);
        }
    }
    
    private void onColorsSwapped(PaletteColorSwapActionData colorSwapData) {
        if (getPaletteListener == null) return;
        
        if (colorSwapData.swapPixels()) {
            IPaletteGraphic graphics = getPaletteListener.getPaletteGraphics();
            if (graphics != null) {
                graphics.setPixels(colorSwapData.pixelData());
            }
        } else {
            palettePane.setPixelData(originalPixels);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.palette.gui.controls.CRAMColorEditor cRAMColorEditor;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JDialog paletteEditor;
    private com.sfc.sf2.palette.gui.PalettePane palettePane;
    // End of variables declaration//GEN-END:variables

    public interface PaletteGraphicsListener extends EventListener {
        public IPaletteGraphic getPaletteGraphics();
    }
    
    public interface ColorsSwappedListener extends EventListener {
        public void colorsSwapped(PaletteColorSwapActionData value);
    }
}
